package com.lifepilot.interaction.web.controller;

import com.lifepilot.interaction.web.model.ErrorResponse;
import com.lifepilot.mcp.config.McpServerConfig;
import com.lifepilot.mcp.registry.McpServerRegistry;
import com.lifepilot.mcp.transport.TransportType;
import com.lifepilot.skill.config.SkillConfigProperties;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.model.SkillSource;
import com.lifepilot.skill.registry.SkillRegistry;
import com.lifepilot.skill.markdown.MarkdownSkillLoader;
import com.lifepilot.skill.markdown.MarkdownSkillParser;
import com.lifepilot.skill.markdown.MarkdownSkillSerializer;
import com.lifepilot.tool.ToolContract;
import com.lifepilot.tool.registry.DynamicToolRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.concurrent.TimeUnit;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Skill / MCP Server 管理 REST Controller。
 *
 * <p>提供 Skill 列表/详情/注销和 MCP Server 列表/连接/断开/工具查询端点。</p>
 *
 * @author zsg
 * @since 2026-02-27
 */
@RestController
@RequestMapping("/api")
public class SkillController {

    private static final Logger log = LoggerFactory.getLogger(SkillController.class);

    private final SkillRegistry skillRegistry;
    private final McpServerRegistry mcpServerRegistry;
    private final DynamicToolRegistry toolRegistry;
    private final MarkdownSkillParser markdownParser;
    private final MarkdownSkillSerializer markdownSerializer;
    private final MarkdownSkillLoader markdownLoader;
    private final SkillConfigProperties skillConfig;
    private final Path skillsDirectory;

    public SkillController(SkillRegistry skillRegistry,
                           McpServerRegistry mcpServerRegistry,
                           DynamicToolRegistry toolRegistry,
                           MarkdownSkillParser markdownParser,
                           MarkdownSkillSerializer markdownSerializer,
                           MarkdownSkillLoader markdownLoader,
                           SkillConfigProperties skillConfig) {
        this.skillRegistry = skillRegistry;
        this.mcpServerRegistry = mcpServerRegistry;
        this.toolRegistry = toolRegistry;
        this.markdownParser = markdownParser;
        this.markdownSerializer = markdownSerializer;
        this.markdownLoader = markdownLoader;
        this.skillConfig = skillConfig;
        this.skillsDirectory = Path.of(skillConfig.getDirectory());
    }

    // ── Skill 端点 ──────────────────────────────────────────

    /**
     * 获取 Skill 列表（支持筛选）。
     *
     * <p>对齐文档约定的查询参数：
     * <ul>
     *   <li>name：按 id/name/description 模糊匹配</li>
     *   <li>sourceType：按来源类型筛选（builtin/userDefined/autoGenerated，大小写不敏感）</li>
     *   <li>toolName：按 suggestedTools 是否包含指定 Tool ID 筛选</li>
     * </ul>
     * 若未提供任何筛选参数，则返回所有已注册 Skill。</p>
     *
     * @param name       名称搜索关键字
     * @param sourceType 来源类型：builtin/userDefined/autoGenerated
     * @param toolName   关联的 Tool ID
     * @return Skill 定义列表
     */
    @GetMapping("/skills")
    public ResponseEntity<?> listSkills(
            @RequestParam(required = false) String name,
            @RequestParam(required = false) String sourceType,
            @RequestParam(required = false) String toolName) {
        log.debug("查询 Skill 列表: name={}, sourceType={}, toolName={}", name, sourceType, toolName);

        var all = skillRegistry.listAll();

        var filtered = all.stream()
                .filter(skill -> {
                    // 名称模糊匹配（id / name / description）
                    if (name != null && !name.isBlank()) {
                        String q = name.toLowerCase();
                        String id = skill.id() != null ? skill.id().toLowerCase() : "";
                        String skillName = skill.name() != null ? skill.name().toLowerCase() : "";
                        String desc = skill.description() != null ? skill.description().toLowerCase() : "";
                        if (!id.contains(q) && !skillName.contains(q) && !desc.contains(q)) {
                            return false;
                        }
                    }

                    // 来源类型筛选
                    if (sourceType != null && !sourceType.isBlank()) {
                        SkillSource source = skill.source();
                        String normalized = sourceType.trim().toLowerCase();
                        boolean match = switch (normalized) {
                            case "builtin" -> source instanceof SkillSource.Builtin;
                            case "userdefined", "user-defined", "yaml", "markdown" ->
                                    source instanceof SkillSource.UserDefined;
                            case "autogenerated", "auto-generated", "auto" ->
                                    source instanceof SkillSource.AutoGenerated;
                            case "marketplace" ->
                                    source instanceof SkillSource.Marketplace;
                            default -> true; // 未识别的值时不做过滤，避免意外返回空
                        };
                        if (!match) {
                            return false;
                        }
                    }

                    // 按 Tool 过滤（suggestedTools 包含）
                    if (toolName != null && !toolName.isBlank()) {
                        var suggested = skill.suggestedTools();
                        if (suggested == null || suggested.isEmpty()
                                || !suggested.contains(toolName)) {
                            return false;
                        }
                    }

                    return true;
                })
                .toList();

        return ResponseEntity.ok(filtered);
    }

    /**
     * 获取指定 Skill 详情。
     *
     * @param id Skill ID
     * @return Skill 定义，不存在返回 404
     */
    @GetMapping("/skills/{id}")
    public ResponseEntity<?> getSkill(@PathVariable String id) {
        return skillRegistry.find(id)
                .<ResponseEntity<?>>map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                        new ErrorResponse(404, "Skill 不存在: id=" + id, Instant.now())));
    }

    /**
     * 创建 Skill。
     *
     * @param request 创建请求（包含 markdownContent 或完整 Skill 定义）
     * @return 201 创建成功，400 参数错误
     */
    @PostMapping("/skills")
    public ResponseEntity<?> createSkill(@RequestBody Map<String, Object> request) {
        log.debug("创建 Skill: request={}", request);

        try {
            // 优先支持 markdownContent（SKILL.md 格式），否则走结构化 JSON 创建路径
            String markdownContent = getString(request, "markdownContent");
            if (markdownContent != null && !markdownContent.isBlank()) {
                // ── 路径 1：客户端直接提交 SKILL.md 内容 ─────────────────
                var parseResult = markdownParser.parse(markdownContent);

                if (!parseResult.success() || parseResult.definition() == null) {
                    return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                            .body(new ErrorResponse(400, "SKILL.md 解析失败: " + String.join("; ", parseResult.errors()), Instant.now()));
                }

                SkillDefinition definition = parseResult.definition();

                // 检查是否已存在
                if (skillRegistry.find(definition.id()).isPresent()) {
                    return ResponseEntity.status(HttpStatus.CONFLICT)
                            .body(new ErrorResponse(409, "Skill ID 已存在: " + definition.id(), Instant.now()));
                }

                // 保存到文件系统（文件夹结构）
                Path skillFolder = skillsDirectory.resolve(definition.id());
                if (!Files.exists(skillFolder)) {
                    Files.createDirectories(skillFolder);
                }
                Path skillFile = skillFolder.resolve(skillConfig.getSkillFilename());
                Files.writeString(skillFile, markdownContent);

                // 通过 MarkdownSkillLoader 加载（设置正确的 source）
                Optional<SkillDefinition> loaded = markdownLoader.loadFolder(skillFolder);
                if (loaded.isEmpty()) {
                    Files.deleteIfExists(skillFile);
                    return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                            .body(new ErrorResponse(400, "Skill 注册失败，请检查定义", Instant.now()));
                }

                boolean registered = skillRegistry.register(loaded.get());
                if (!registered) {
                    Files.deleteIfExists(skillFile);
                    return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                            .body(new ErrorResponse(400, "Skill 注册失败，请检查定义", Instant.now()));
                }

                log.info("Skill 创建成功: id={}, name={}", definition.id(), definition.name());
                return ResponseEntity.status(HttpStatus.CREATED).body(loaded.get());
            }

            // ── 路径 2：Web UI 通过结构化 JSON 创建 Skill ─────────────────
            String id = getString(request, "id");
            String name = getString(request, "name");
            String description = getString(request, "description");
            String version = getString(request, "version");
            String instructions = getString(request, "instructions");

            if (id == null || id.isBlank()) {
                return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                        .body(new ErrorResponse(400, "Skill ID 不能为空", Instant.now()));
            }
            if (name == null || name.isBlank()) {
                return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                        .body(new ErrorResponse(400, "Skill 名称不能为空", Instant.now()));
            }
            if (instructions == null || instructions.isBlank()) {
                return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                        .body(new ErrorResponse(400, "instructions 不能为空", Instant.now()));
            }

            // 检查是否已存在
            if (skillRegistry.find(id).isPresent()) {
                return ResponseEntity.status(HttpStatus.CONFLICT)
                        .body(new ErrorResponse(409, "Skill ID 已存在: " + id, Instant.now()));
            }

            @SuppressWarnings("unchecked")
            List<String> suggestedTools = (List<String>) request.getOrDefault("suggestedTools", List.of());
            @SuppressWarnings("unchecked")
            Map<String, String> metadata = (Map<String, String>) request.getOrDefault("metadata", Map.of());

            // 构建 SkillDefinition
            SkillDefinition definition = SkillDefinition.builder()
                    .id(id)
                    .name(name)
                    .description(description != null ? description : "")
                    .version(version != null && !version.isBlank() ? version : "1.0.0")
                    .source(new SkillSource.UserDefined(
                            skillsDirectory.resolve(id).toString()
                    ))
                    .instructions(instructions)
                    .suggestedTools(suggestedTools)
                    .metadata(metadata)
                    .build();

            // 序列化为 SKILL.md 并保存到文件系统（文件夹结构）
            String serializedMarkdown = markdownSerializer.serialize(definition);
            Path skillFolder = skillsDirectory.resolve(id);
            if (!Files.exists(skillFolder)) {
                Files.createDirectories(skillFolder);
            }
            Path skillFile = skillFolder.resolve(skillConfig.getSkillFilename());
            Files.writeString(skillFile, serializedMarkdown);

            // 注册到 SkillRegistry
            boolean registered = skillRegistry.register(definition);
            if (!registered) {
                Files.deleteIfExists(skillFile);
                return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                        .body(new ErrorResponse(400, "Skill 注册失败，请检查定义", Instant.now()));
            }

            log.info("Skill 创建成功: id={}, name={}", definition.id(), definition.name());
            return ResponseEntity.status(HttpStatus.CREATED).body(definition);
        } catch (IOException e) {
            log.error("创建 Skill 失败", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ErrorResponse(500, "创建失败: " + e.getMessage(), Instant.now()));
        } catch (Exception e) {
            log.error("创建 Skill 失败", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ErrorResponse(500, "创建失败: " + e.getMessage(), Instant.now()));
        }
    }

    /**
     * 更新 Skill（仅用户定义的 Skill 可编辑）。
     *
     * @param id Skill ID
     * @param request 更新请求（包含 markdownContent）
     * @return 200 更新成功，404 不存在，400 参数错误
     */
    @PutMapping("/skills/{id}")
    public ResponseEntity<?> updateSkill(@PathVariable String id,
                                         @RequestBody Map<String, Object> request) {
        log.debug("更新 Skill: id={}, request={}", id, request);
        
        // 检查 Skill 是否存在
        Optional<SkillDefinition> existingOpt = skillRegistry.find(id);
        if (existingOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(new ErrorResponse(404, "Skill 不存在: id=" + id, Instant.now()));
        }

        SkillDefinition existing = existingOpt.get();

        // 检查是否为用户定义类型（只有用户定义的 Skill 可以更新）
        if (!(existing.source() instanceof SkillSource.UserDefined)) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(new ErrorResponse(400, "只能更新用户创建的 Skill", Instant.now()));
        }

        try {
            // 优先处理 markdownContent 更新路径
            String markdownContent = getString(request, "markdownContent");
            if (markdownContent != null && !markdownContent.isBlank()) {
                var parseResult = markdownParser.parse(markdownContent);

                if (!parseResult.success() || parseResult.definition() == null) {
                    return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                            .body(new ErrorResponse(400, "SKILL.md 解析失败: " + String.join("; ", parseResult.errors()), Instant.now()));
                }

                SkillDefinition definition = parseResult.definition();

                // 检查 ID 是否匹配
                if (!definition.id().equals(id)) {
                    return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                            .body(new ErrorResponse(400, "SKILL.md 中的 ID 必须与路径参数一致", Instant.now()));
                }

                // 更新文件系统（文件夹结构）
                Path skillFolder = skillsDirectory.resolve(id);
                if (!Files.exists(skillFolder)) {
                    Files.createDirectories(skillFolder);
                }
                Path skillFile = skillFolder.resolve(skillConfig.getSkillFilename());
                Files.writeString(skillFile, markdownContent);

                // 通过 MarkdownSkillLoader 加载（设置正确的 source）
                Optional<SkillDefinition> loaded = markdownLoader.loadFolder(skillFolder);
                if (loaded.isEmpty()) {
                    return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                            .body(new ErrorResponse(400, "Skill 更新失败，请检查定义", Instant.now()));
                }

                boolean registered = skillRegistry.register(loaded.get());
                if (!registered) {
                    return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                            .body(new ErrorResponse(400, "Skill 更新失败，请检查定义", Instant.now()));
                }

                log.info("Skill 更新成功: id={}", id);
                return ResponseEntity.ok(loaded.get());
            }

            // ── 结构化 JSON 更新路径（供 Web UI 使用） ─────────────────
            SkillDefinition.SkillDefinitionBuilder builder = existing.toBuilder();

            String name = getString(request, "name");
            if (name != null && !name.isBlank()) {
                builder.name(name);
            }

            String description = getString(request, "description");
            if (description != null) {
                builder.description(description);
            }

            String version = getString(request, "version");
            if (version != null && !version.isBlank()) {
                builder.version(version);
            }

            String instructions = getString(request, "instructions");
            if (instructions != null && !instructions.isBlank()) {
                builder.instructions(instructions);
            }

            @SuppressWarnings("unchecked")
            List<String> suggestedTools = (List<String>) request.get("suggestedTools");
            if (suggestedTools != null) {
                builder.suggestedTools(suggestedTools);
            }

            @SuppressWarnings("unchecked")
            Map<String, String> metadata = (Map<String, String>) request.get("metadata");
            if (metadata != null) {
                builder.metadata(metadata);
            }

            SkillDefinition updated = builder.build();

            // 序列化为 SKILL.md 并写回文件（文件夹结构）
            String serializedMarkdown = markdownSerializer.serialize(updated);
            Path skillFolder = skillsDirectory.resolve(id);
            if (!Files.exists(skillFolder)) {
                Files.createDirectories(skillFolder);
            }
            Path skillFile = skillFolder.resolve(skillConfig.getSkillFilename());
            Files.writeString(skillFile, serializedMarkdown);

            boolean registered = skillRegistry.register(updated);
            if (!registered) {
                return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                        .body(new ErrorResponse(400, "Skill 更新失败，请检查定义", Instant.now()));
            }

            log.info("Skill 更新成功: id={}", id);
            return ResponseEntity.ok(updated);
        } catch (IOException e) {
            log.error("更新 Skill 失败: id={}", id, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ErrorResponse(500, "更新失败: " + e.getMessage(), Instant.now()));
        } catch (Exception e) {
            log.error("更新 Skill 失败: id={}", id, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ErrorResponse(500, "更新失败: " + e.getMessage(), Instant.now()));
        }
    }

    /**
     * 注销指定 Skill（Builtin 类型不可注销）。
     *
     * @param id Skill ID
     * @return 204 成功，400 Builtin 不可注销，404 不存在
     */
    @DeleteMapping("/skills/{id}")
    public ResponseEntity<?> unregisterSkill(@PathVariable String id) {
        var skillOpt = skillRegistry.find(id);
        if (skillOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                    new ErrorResponse(404, "Skill 不存在: id=" + id, Instant.now()));
        }

        // Builtin Skill 不可注销
        if (skillOpt.get().source() instanceof SkillSource.Builtin) {
            log.warn("尝试注销内置 Skill 被拒绝: id={}", id);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(
                    new ErrorResponse(400, "内置 Skill 不可注销: id=" + id, Instant.now()));
        }

        skillRegistry.unregister(id);
        
        // 删除 Skill 文件夹
        try {
            Path skillFolder = skillsDirectory.resolve(id);
            if (Files.exists(skillFolder) && Files.isDirectory(skillFolder)) {
                // 递归删除文件夹内容
                try (var walk = Files.walk(skillFolder)) {
                    walk.sorted(java.util.Comparator.reverseOrder())
                            .forEach(path -> {
                                try { Files.deleteIfExists(path); } catch (IOException ignored) {}
                            });
                }
            }
        } catch (IOException e) {
            log.warn("删除 Skill 文件夹失败: id={}, error={}", id, e.getMessage());
        }
        
        log.info("Skill 已注销: id={}", id);
        return ResponseEntity.noContent().build();
    }

    /**
     * 启用 Skill（通过 metadata.status=enabled 控制）。
     *
     * <p>仅允许用户定义的 Skill 修改状态，Builtin Skill 保持始终可用。</p>
     *
     * @param id Skill ID
     * @return 204 成功，404 不存在，400 类型不支持
     */
    @PostMapping("/skills/{id}/enable")
    public ResponseEntity<?> enableSkill(@PathVariable String id) {
        log.info("启用 Skill: id={}", id);

        Optional<SkillDefinition> skillOpt = skillRegistry.find(id);
        if (skillOpt.isEmpty()) {
            log.warn("Skill 不存在: id={}", id);
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(new ErrorResponse(404, "Skill 不存在: id=" + id, Instant.now()));
        }

        SkillDefinition skill = skillOpt.get();

        // 仅允许用户定义或市场安装的 Skill 修改状态
        if (!(skill.source() instanceof SkillSource.UserDefined)
                && !(skill.source() instanceof SkillSource.Marketplace)) {
            log.warn("尝试启用非用户定义 Skill 被拒绝: id={}", id);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(new ErrorResponse(400, "只能启用/禁用用户创建或市场安装的 Skill", Instant.now()));
        }

        Map<String, String> metadata = new HashMap<>(skill.metadata() != null ? skill.metadata() : Map.of());
        metadata.put("status", "enabled");

        SkillDefinition updated = skill.toBuilder()
                .metadata(metadata)
                .build();

        // 写回 SKILL.md 文件
        try {
            String serializedMarkdown = markdownSerializer.serialize(updated);
            Path skillFolder = skillsDirectory.resolve(id);
            if (!Files.exists(skillFolder)) {
                Files.createDirectories(skillFolder);
            }
            Path skillFile = skillFolder.resolve(skillConfig.getSkillFilename());
            Files.writeString(skillFile, serializedMarkdown);
        } catch (IOException e) {
            log.error("写回 Skill 文件失败（启用）: id={}", id, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ErrorResponse(500, "启用失败: " + e.getMessage(), Instant.now()));
        }

        skillRegistry.register(updated);
        log.info("Skill 启用成功: id={}", id);
        return ResponseEntity.noContent().build();
    }

    /**
     * 禁用 Skill（通过 metadata.status=disabled 控制）。
     *
     * <p>仅允许用户定义的 Skill 修改状态，Builtin Skill 保持始终可用。</p>
     *
     * @param id Skill ID
     * @return 204 成功，404 不存在，400 类型不支持
     */
    @PostMapping("/skills/{id}/disable")
    public ResponseEntity<?> disableSkill(@PathVariable String id) {
        log.info("禁用 Skill: id={}", id);

        Optional<SkillDefinition> skillOpt = skillRegistry.find(id);
        if (skillOpt.isEmpty()) {
            log.warn("Skill 不存在: id={}", id);
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(new ErrorResponse(404, "Skill 不存在: id=" + id, Instant.now()));
        }

        SkillDefinition skill = skillOpt.get();

        // 仅允许用户定义或市场安装的 Skill 修改状态
        if (!(skill.source() instanceof SkillSource.UserDefined)
                && !(skill.source() instanceof SkillSource.Marketplace)) {
            log.warn("尝试禁用非用户定义 Skill 被拒绝: id={}", id);
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(new ErrorResponse(400, "只能启用/禁用用户创建或市场安装的 Skill", Instant.now()));
        }

        Map<String, String> metadata = new HashMap<>(skill.metadata() != null ? skill.metadata() : Map.of());
        metadata.put("status", "disabled");

        SkillDefinition updated = skill.toBuilder()
                .metadata(metadata)
                .build();

        // 写回 SKILL.md 文件
        try {
            String serializedMarkdown = markdownSerializer.serialize(updated);
            Path skillFolder = skillsDirectory.resolve(id);
            if (!Files.exists(skillFolder)) {
                Files.createDirectories(skillFolder);
            }
            Path skillFile = skillFolder.resolve(skillConfig.getSkillFilename());
            Files.writeString(skillFile, serializedMarkdown);
        } catch (IOException e) {
            log.error("写回 Skill 文件失败（禁用）: id={}", id, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ErrorResponse(500, "禁用失败: " + e.getMessage(), Instant.now()));
        }

        skillRegistry.register(updated);
        log.info("Skill 禁用成功: id={}", id);
        return ResponseEntity.noContent().build();
    }

    // ── Skill Markdown 端点 ─────────────────────────────────

    /**
     * 获取指定 Skill 的 Markdown 内容。
     *
     * @param id Skill ID
     * @return Markdown 文本（text/markdown），不存在返回 404
     */
    @GetMapping(value = "/skills/{id}/markdown", produces = "text/markdown")
    public ResponseEntity<?> getSkillMarkdown(@PathVariable String id) {
        Optional<SkillDefinition> skillOpt = skillRegistry.find(id);
        if (skillOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(new ErrorResponse(404, "Skill 不存在: id=" + id, Instant.now()));
        }

        String markdown = markdownSerializer.serialize(skillOpt.get());
        return ResponseEntity.ok(markdown);
    }

    /**
     * 通过 Markdown 内容更新指定 Skill。
     *
     * <p>接收纯文本 SKILL.md 内容，解析后写入文件并注册到 SkillRegistry。</p>
     *
     * @param id      Skill ID
     * @param content Markdown 文本内容
     * @return 更新后的 SkillDefinition JSON，解析失败返回 400，不存在返回 404
     */
    @PutMapping(value = "/skills/{id}/markdown", consumes = "text/plain")
    public ResponseEntity<?> updateSkillMarkdown(@PathVariable String id,
                                                  @RequestBody String content) {
        // 检查 Skill 是否存在
        Optional<SkillDefinition> existingOpt = skillRegistry.find(id);
        if (existingOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(new ErrorResponse(404, "Skill 不存在: id=" + id, Instant.now()));
        }

        // 仅用户定义的 Skill 可通过 Markdown 更新
        if (!(existingOpt.get().source() instanceof SkillSource.UserDefined)) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(new ErrorResponse(400, "只能更新用户创建的 Skill", Instant.now()));
        }

        // 解析 Markdown 内容
        var parseResult = markdownParser.parse(content);
        if (!parseResult.success() || parseResult.definition() == null) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(new ErrorResponse(400, "SKILL.md 解析失败: " + String.join("; ", parseResult.errors()), Instant.now()));
        }

        SkillDefinition parsed = parseResult.definition();

        // 验证 ID 一致性
        if (!parsed.id().equals(id)) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(new ErrorResponse(400, "SKILL.md 中的 ID 必须与路径参数一致", Instant.now()));
        }

        try {
            // 写入文件
            Path skillFolder = skillsDirectory.resolve(id);
            if (!Files.exists(skillFolder)) {
                Files.createDirectories(skillFolder);
            }
            Path skillFile = skillFolder.resolve(skillConfig.getSkillFilename());
            Files.writeString(skillFile, content);

            // 通过 MarkdownSkillLoader 加载（设置正确的 source）
            Optional<SkillDefinition> loaded = markdownLoader.loadFolder(skillFolder);
            if (loaded.isEmpty()) {
                return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                        .body(new ErrorResponse(400, "Skill 更新失败，请检查定义", Instant.now()));
            }

            skillRegistry.register(loaded.get());
            log.info("Skill Markdown 更新成功: id={}", id);
            return ResponseEntity.ok(loaded.get());
        } catch (IOException e) {
            log.error("Skill Markdown 更新失败: id={}", id, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ErrorResponse(500, "更新失败: " + e.getMessage(), Instant.now()));
        }
    }

    // ── 辅助方法 ──────────────────────────────────────────

    private String getString(Map<String, Object> map, String key) {
        Object value = map.get(key);
        return value != null ? value.toString() : null;
    }

    // ── MCP Server 端点 ─────────────────────────────────────

    /**
     * 获取 MCP 环境状态（npx 可用性等）。
     *
     * <p>前端据此展示环境依赖提示，例如 Node.js 未安装时引导用户安装。</p>
     *
     * @return 包含 npxAvailable 的状态 Map
     */
    @GetMapping("/mcp/status")
    public ResponseEntity<?> getMcpStatus() {
        boolean npxAvailable = checkNpxAvailable();
        return ResponseEntity.ok(Map.of("npxAvailable", npxAvailable));
    }

    /**
     * 获取所有 MCP Server 列表。
     *
     * @return MCP Server 扁平化 DTO 列表
     */
    @GetMapping("/mcp/servers")
    public ResponseEntity<?> listMcpServers() {
        log.debug("查询 MCP Server 列表");
        var dtos = mcpServerRegistry.listServers().stream()
                .map(this::toMcpServerDto)
                .toList();
        return ResponseEntity.ok(dtos);
    }

    /**
     * 获取指定 MCP Server 详情。
     *
     * @param name Server 名称
     * @return Server 扁平化 DTO，不存在返回 404
     */
    @GetMapping("/mcp/servers/{name}")
    public ResponseEntity<?> getMcpServer(@PathVariable String name) {
        return mcpServerRegistry.getServer(name)
                .map(this::toMcpServerDto)
                .<ResponseEntity<?>>map(ResponseEntity::ok)
                .orElseGet(() -> ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                        new ErrorResponse(404, "MCP Server 不存在: name=" + name, Instant.now())));
    }

    /**
     * 连接指定 MCP Server。
     *
     * @param name Server 名称
     * @return 202 已接受，404 不存在
     */
    @PostMapping("/mcp/servers/{name}/connect")
    public ResponseEntity<?> connectMcpServer(@PathVariable String name) {
        var serverOpt = mcpServerRegistry.getServer(name);
        if (serverOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                    new ErrorResponse(404, "MCP Server 不存在: name=" + name, Instant.now()));
        }

        mcpServerRegistry.connectServer(serverOpt.get().config());
        log.info("MCP Server 连接请求已接受: name={}", name);
        return ResponseEntity.accepted().build();
    }

    /**
     * 断开指定 MCP Server。
     *
     * @param name Server 名称
     * @return 204 成功，404 不存在
     */
    @PostMapping("/mcp/servers/{name}/disconnect")
    public ResponseEntity<?> disconnectMcpServer(@PathVariable String name) {
        var serverOpt = mcpServerRegistry.getServer(name);
        if (serverOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                    new ErrorResponse(404, "MCP Server 不存在: name=" + name, Instant.now()));
        }

        mcpServerRegistry.disconnectServer(name);
        log.info("MCP Server 已断开: name={}", name);
        return ResponseEntity.noContent().build();
    }

    /**
     * 获取指定 MCP Server 的工具列表。
     *
     * @param name Server 名称
     * @return 工具列表，Server 不存在返回 404
     */
    @GetMapping("/mcp/servers/{name}/tools")
    public ResponseEntity<?> getMcpServerTools(@PathVariable String name) {
        var serverOpt = mcpServerRegistry.getServer(name);
        if (serverOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                    new ErrorResponse(404, "MCP Server 不存在: name=" + name, Instant.now()));
        }

        List<ToolContract> tools = toolRegistry.getToolsByServer(name);
        return ResponseEntity.ok(tools);
    }

    /**
     * 获取 MCP Server 连接日志。
     *
     * @param name 服务器名称
     * @return 连接日志列表（按时间倒序）
     */
    @GetMapping("/mcp/servers/{name}/connection-logs")
    public ResponseEntity<?> getMcpServerConnectionLogs(@PathVariable String name) {
        var serverOpt = mcpServerRegistry.getServer(name);
        if (serverOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(
                    new ErrorResponse(404, "MCP Server 不存在: name=" + name, Instant.now()));
        }

        var logs = mcpServerRegistry.getConnectionLogs(name);
        return ResponseEntity.ok(logs);
    }

    /**
     * 创建 MCP Server。
     *
     * @param request 创建请求（包含 name 和 config）
     * @return 201 创建成功，400 参数错误
     */
    @PostMapping("/mcp/servers")
    public ResponseEntity<?> createMcpServer(@RequestBody Map<String, Object> request) {
        log.debug("创建 MCP Server: request={}", request);
        
        try {
            String name = getString(request, "name");
            if (name == null || name.isBlank()) {
                return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                        .body(new ErrorResponse(400, "name 不能为空", Instant.now()));
            }

            // 检查是否已存在
            if (mcpServerRegistry.getServer(name).isPresent()) {
                return ResponseEntity.status(HttpStatus.CONFLICT)
                        .body(new ErrorResponse(409, "MCP Server 已存在: name=" + name, Instant.now()));
            }

            // 构建配置
            McpServerConfig config = buildMcpServerConfig(name, request);
            
            // 初始化并连接
            mcpServerRegistry.initializeAll(List.of(config));
            if (config.autoConnect()) {
                mcpServerRegistry.connectServer(config);
            }

            log.info("MCP Server 创建成功: name={}", name);
            return ResponseEntity.status(HttpStatus.CREATED)
                    .body(mcpServerRegistry.getServer(name).orElse(null));
        } catch (IllegalArgumentException e) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(new ErrorResponse(400, e.getMessage(), Instant.now()));
        } catch (Exception e) {
            log.error("创建 MCP Server 失败", e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ErrorResponse(500, "创建失败: " + e.getMessage(), Instant.now()));
        }
    }

    /**
     * 更新 MCP Server。
     *
     * @param name Server 名称
     * @param request 更新请求（包含 config）
     * @return 200 更新成功，404 不存在，400 参数错误
     */
    @PutMapping("/mcp/servers/{name}")
    public ResponseEntity<?> updateMcpServer(@PathVariable String name,
                                             @RequestBody Map<String, Object> request) {
        log.debug("更新 MCP Server: name={}, request={}", name, request);
        
        // 检查是否存在
        var existingOpt = mcpServerRegistry.getServer(name);
        if (existingOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(new ErrorResponse(404, "MCP Server 不存在: name=" + name, Instant.now()));
        }

        try {
            // 先断开连接
            mcpServerRegistry.disconnectServer(name);

            // 构建新配置（保持名称不变）
            McpServerConfig config = buildMcpServerConfig(name, request);
            
            // 重新初始化并连接
            mcpServerRegistry.initializeAll(List.of(config));
            if (config.autoConnect()) {
                mcpServerRegistry.connectServer(config);
            }

            log.info("MCP Server 更新成功: name={}", name);
            return ResponseEntity.ok(mcpServerRegistry.getServer(name).orElse(null));
        } catch (IllegalArgumentException e) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                    .body(new ErrorResponse(400, e.getMessage(), Instant.now()));
        } catch (Exception e) {
            log.error("更新 MCP Server 失败: name={}", name, e);
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .body(new ErrorResponse(500, "更新失败: " + e.getMessage(), Instant.now()));
        }
    }

    /**
     * 删除 MCP Server。
     *
     * @param name Server 名称
     * @return 204 删除成功，404 不存在
     */
    @DeleteMapping("/mcp/servers/{name}")
    public ResponseEntity<?> deleteMcpServer(@PathVariable String name) {
        log.debug("删除 MCP Server: name={}", name);
        
        var serverOpt = mcpServerRegistry.getServer(name);
        if (serverOpt.isEmpty()) {
            return ResponseEntity.status(HttpStatus.NOT_FOUND)
                    .body(new ErrorResponse(404, "MCP Server 不存在: name=" + name, Instant.now()));
        }

        // 断开连接（这会注销工具）
        mcpServerRegistry.disconnectServer(name);
        
        // 注意：McpServerRegistry 没有公开的 remove 方法，但断开连接后工具已注销
        // 如果需要完全移除注册表条目，需要扩展 McpServerRegistry
        
        log.info("MCP Server 已删除: name={}", name);
        return ResponseEntity.noContent().build();
    }

    // ── MCP Server 辅助方法 ──────────────────────────────────────────

    private McpServerConfig buildMcpServerConfig(String name, Map<String, Object> request) {
        @SuppressWarnings("unchecked")
        Map<String, Object> configMap = (Map<String, Object>) request.get("config");
        if (configMap == null) {
            throw new IllegalArgumentException("config 不能为空");
        }

        // 解析 transport
        String transportStr = getString(configMap, "transport");
        if (transportStr == null || transportStr.isBlank()) {
            throw new IllegalArgumentException("transport 不能为空");
        }
        TransportType transport = parseTransportType(transportStr);

        // 解析其他字段
        String command = getString(configMap, "command");
        @SuppressWarnings("unchecked")
        List<String> args = configMap.get("args") instanceof List<?> 
                ? (List<String>) configMap.get("args") 
                : new ArrayList<>();
        String url = getString(configMap, "url");
        @SuppressWarnings("unchecked")
        Map<String, String> env = configMap.get("env") instanceof Map<?, ?>
                ? (Map<String, String>) configMap.get("env")
                : Map.of();

        // 解析可选字段
        Duration timeout = parseDuration(configMap.get("timeout"), McpServerConfig.DEFAULT_TIMEOUT);
        boolean autoConnect = getBooleanOrDefault(configMap, "autoConnect", false);
        boolean reconnect = getBooleanOrDefault(configMap, "reconnect", true);
        Duration reconnectDelay = parseDuration(configMap.get("reconnectDelay"), 
                McpServerConfig.DEFAULT_RECONNECT_DELAY);
        int maxReconnectAttempts = getIntOrDefault(configMap, "maxReconnectAttempts", 
                McpServerConfig.DEFAULT_MAX_RECONNECT_ATTEMPTS);
        Duration healthCheckInterval = parseDuration(configMap.get("healthCheckInterval"), 
                McpServerConfig.DEFAULT_HEALTH_CHECK_INTERVAL);

        return McpServerConfig.builder()
                .name(name)
                .transport(transport)
                .command(command)
                .args(args)
                .url(url)
                .env(env)
                .timeout(timeout)
                .autoConnect(autoConnect)
                .reconnect(reconnect)
                .reconnectDelay(reconnectDelay)
                .maxReconnectAttempts(maxReconnectAttempts)
                .healthCheckInterval(healthCheckInterval)
                .build();
    }

    private TransportType parseTransportType(String transportStr) {
        return switch (transportStr.toUpperCase()) {
            case "STDIO" -> TransportType.STDIO;
            case "STREAMABLE_HTTP", "HTTP" -> TransportType.STREAMABLE_HTTP;
            case "SSE", "SSE_LEGACY" -> TransportType.SSE_LEGACY;
            default -> throw new IllegalArgumentException("不支持的传输类型: " + transportStr);
        };
    }

    private Duration parseDuration(Object value, Duration defaultValue) {
        if (value == null) return defaultValue;
        if (value instanceof Number) {
            return Duration.ofSeconds(((Number) value).longValue());
        }
        if (value instanceof String str) {
            try {
                return Duration.parse(str);
            } catch (Exception e) {
                return Duration.ofSeconds(Long.parseLong(str));
            }
        }
        return defaultValue;
    }

    private boolean getBooleanOrDefault(Map<String, Object> map, String key, boolean defaultValue) {
        Object value = map.get(key);
        if (value == null) return defaultValue;
        if (value instanceof Boolean) return (Boolean) value;
        return Boolean.parseBoolean(value.toString());
    }

    private int getIntOrDefault(Map<String, Object> map, String key, int defaultValue) {
        Object value = map.get(key);
        if (value == null) return defaultValue;
        if (value instanceof Number) return ((Number) value).intValue();
        try {
            return Integer.parseInt(value.toString());
        } catch (NumberFormatException e) {
            return defaultValue;
        }
    }

    // ── npx 可用性检查 ──────────────────────────────────────────

    /**
     * 检查 npx 是否可用。
     *
     * <p>Windows 上 npx 是 .cmd 批处理脚本，需要通过 {@code cmd /c} 执行。</p>
     */
    private boolean checkNpxAvailable() {
        try {
            ProcessBuilder pb;
            if (System.getProperty("os.name", "").toLowerCase().contains("win")) {
                pb = new ProcessBuilder("cmd", "/c", "npx", "--version");
            } else {
                pb = new ProcessBuilder("npx", "--version");
            }
            var process = pb.redirectErrorStream(true).start();
            boolean finished = process.waitFor(5, TimeUnit.SECONDS);
            if (!finished) {
                process.destroyForcibly();
                return false;
            }
            return process.exitValue() == 0;
        } catch (Exception e) {
            return false;
        }
    }

    // ── McpServerEntry → 前端 DTO 转换 ──────────────────────────────

    /**
     * 将 McpServerEntry 转换为前端期望的扁平 DTO。
     *
     * <p>前端 McpServer 类型期望 name/state/toolCount 等顶层字段，
     * 而 McpServerEntry 的 name 嵌套在 config 中，且 client 字段不应序列化。</p>
     */
    private Map<String, Object> toMcpServerDto(com.lifepilot.mcp.registry.McpServerEntry entry) {
        var dto = new HashMap<String, Object>();
        var config = entry.config();
        dto.put("name", config.name());
        dto.put("state", entry.state().name());
        dto.put("toolCount", toolRegistry.getToolsByServer(config.name()).size());
        dto.put("connectedSince", entry.connectedSince() != null ? entry.connectedSince().toString() : null);
        dto.put("lastError", entry.lastError());

        // 嵌套 config 供前端编辑用
        var configDto = new HashMap<String, Object>();
        // 前端 Select 使用小写值：stdio / sse
        configDto.put("transport", switch (config.transport()) {
            case STDIO -> "stdio";
            case SSE_LEGACY -> "sse";
            case STREAMABLE_HTTP -> "streamable_http";
        });
        configDto.put("command", config.command());
        configDto.put("args", config.args());
        configDto.put("env", config.env());
        configDto.put("url", config.url());
        configDto.put("autoConnect", config.autoConnect());
        configDto.put("reconnect", config.reconnect());
        // 前端期望的字段名和单位
        configDto.put("timeoutSeconds", config.timeout().toSeconds());
        configDto.put("maxRetries", config.maxReconnectAttempts());
        dto.put("config", configDto);

        return dto;
    }
}
