package com.lifepilot.interaction.web.controller;

import com.lifepilot.interaction.web.model.ApiResponse;
import com.lifepilot.mcp.config.McpServerConfig;
import com.lifepilot.mcp.registry.McpServerRegistry;
import com.lifepilot.mcp.transport.TransportType;
import com.lifepilot.skill.config.SkillConfigProperties;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.model.SkillSource;
import com.lifepilot.skill.registry.SkillRegistry;
import com.lifepilot.tool.ToolContract;
import com.lifepilot.tool.registry.DynamicToolRegistry;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import org.springframework.web.bind.annotation.*;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.concurrent.TimeUnit;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Skill / MCP Server 管理 REST Controller。
 *
 * <p>提供 Skill 列表/详情/注销和 MCP Server 列表/连接/断开/工具查询端点。</p>
 *
 * <p>TODO Phase B.6: Skill 创建/更新/Markdown 读写端点原依赖旧
 * {@code com.lifepilot.skill.markdown.MarkdownSkillParser / MarkdownSkillSerializer / MarkdownSkillLoader}，
 * 随 v2 Parser 重写已拆除。相关端点暂时抛 501 Not Implemented，
 * 待 Phase B.6 接入新 {@code com.lifepilot.skill.MarkdownSkillParser} + {@code SkillInstaller} 后恢复。</p>
 *
 * @author zsg
 * @since 2026-02-27
 */
@RestController
@RequestMapping("/api")
@ConditionalOnProperty(name = "lifepilot.gateway.channels.web.enabled", havingValue = "true")
public class SkillController {

    private static final Logger log = LoggerFactory.getLogger(SkillController.class);

    private final SkillRegistry skillRegistry;
    private final McpServerRegistry mcpServerRegistry;
    private final DynamicToolRegistry toolRegistry;
    private final SkillConfigProperties skillConfig;
    private final Path skillsDirectory;

    public SkillController(SkillRegistry skillRegistry,
                           McpServerRegistry mcpServerRegistry,
                           DynamicToolRegistry toolRegistry,
                           SkillConfigProperties skillConfig) {
        this.skillRegistry = skillRegistry;
        this.mcpServerRegistry = mcpServerRegistry;
        this.toolRegistry = toolRegistry;
        this.skillConfig = skillConfig;
        this.skillsDirectory = Path.of(skillConfig.getDirectory());
    }

    // ── Skill 端点 ──────────────────────────────────────────

    /**
     * 获取 Skill 列表（支持筛选）。
     *
     * <p>对齐文档约定的查询参数：
     * <ul>
     *   <li>name：按 id/name/description 模糊匹配</li>
     *   <li>sourceType：按来源类型筛选（userDefined/autoGenerated/marketplace，大小写不敏感）</li>
     *   <li>toolName：按 suggestedTools 是否包含指定 Tool ID 筛选</li>
     * </ul>
     * 若未提供任何筛选参数，则返回所有已注册 Skill。</p>
     *
     * @param name       名称搜索关键字
     * @param sourceType 来源类型：userDefined/autoGenerated/marketplace
     * @param toolName   关联的 Tool ID
     * @return Skill 定义列表
     */
    @GetMapping("/skills")
    public ApiResponse<?> listSkills(
            @RequestParam(required = false) String name,
            @RequestParam(required = false) String sourceType,
            @RequestParam(required = false) String toolName) {
        log.debug("查询 Skill 列表: name={}, sourceType={}, toolName={}", name, sourceType, toolName);

        var all = skillRegistry.listAll();

        var filtered = all.stream()
                .filter(skill -> {
                    // 名称模糊匹配（id / name / description）
                    if (name != null && !name.isBlank()) {
                        String q = name.toLowerCase();
                        String id = skill.id() != null ? skill.id().toLowerCase() : "";
                        String skillName = skill.name() != null ? skill.name().toLowerCase() : "";
                        String desc = skill.description() != null ? skill.description().toLowerCase() : "";
                        if (!id.contains(q) && !skillName.contains(q) && !desc.contains(q)) {
                            return false;
                        }
                    }

                    // 来源类型筛选
                    if (sourceType != null && !sourceType.isBlank()) {
                        SkillSource source = skill.source();
                        String normalized = sourceType.trim().toLowerCase();
                        boolean match = switch (normalized) {
                            case "userdefined", "user-defined", "yaml", "markdown" ->
                                    source instanceof SkillSource.UserDefined;
                            case "autogenerated", "auto-generated", "auto" ->
                                    source instanceof SkillSource.AutoGenerated;
                            case "marketplace" ->
                                    source instanceof SkillSource.Marketplace;
                            default -> true; // 未识别的值时不做过滤，避免意外返回空
                        };
                        if (!match) {
                            return false;
                        }
                    }

                    // 按 Tool 过滤（suggestedTools 包含）
                    if (toolName != null && !toolName.isBlank()) {
                        var suggested = skill.suggestedTools();
                        if (suggested == null || suggested.isEmpty()
                                || !suggested.contains(toolName)) {
                            return false;
                        }
                    }

                    return true;
                })
                .toList();

        return ApiResponse.ok(filtered);
    }

    /**
     * 获取指定 Skill 详情。
     *
     * @param id Skill ID
     * @return Skill 定义，不存在返回 404
     */
    @GetMapping("/skills/{id}")
    public ApiResponse<?> getSkill(@PathVariable String id) {
        var skill = skillRegistry.find(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Skill 不存在: id=" + id));
        return ApiResponse.ok(skill);
    }

    /**
     * 创建 Skill。
     *
     * <p>TODO Phase B.6: 原实现依赖老 Parser/Serializer/Loader，已随 v2 重写拆除。</p>
     */
    @PostMapping("/skills")
    public ApiResponse<?> createSkill(@RequestBody Map<String, Object> request) {
        // TODO Phase B.6: 接入新 MarkdownSkillParser + SkillInstaller 重建创建流程
        throw new ResponseStatusException(HttpStatus.NOT_IMPLEMENTED,
                "Skill 创建端点待 Phase B.6 重接新 parser + SkillInstaller");
    }

    /**
     * 更新 Skill（仅用户定义的 Skill 可编辑）。
     *
     * <p>TODO Phase B.6: 原实现依赖老 Parser/Serializer/Loader，已随 v2 重写拆除。</p>
     */
    @PutMapping("/skills/{id}")
    public ApiResponse<?> updateSkill(@PathVariable String id,
                                      @RequestBody Map<String, Object> request) {
        // TODO Phase B.6: 接入新 MarkdownSkillParser + SkillInstaller 重建更新流程
        throw new ResponseStatusException(HttpStatus.NOT_IMPLEMENTED,
                "Skill 更新端点待 Phase B.6 重接新 parser + SkillInstaller");
    }

    /**
     * 注销指定 Skill。
     *
     * @param id Skill ID
     * @return 204 成功，404 不存在
     */
    @DeleteMapping("/skills/{id}")
    public ApiResponse<?> unregisterSkill(@PathVariable String id) {
        var skillOpt = skillRegistry.find(id);
        if (skillOpt.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Skill 不存在: id=" + id);
        }

        skillRegistry.unregister(id);

        // 删除 Skill 文件夹
        try {
            Path skillFolder = skillsDirectory.resolve(id);
            if (Files.exists(skillFolder) && Files.isDirectory(skillFolder)) {
                // 递归删除文件夹内容
                try (var walk = Files.walk(skillFolder)) {
                    walk.sorted(java.util.Comparator.reverseOrder())
                            .forEach(path -> {
                                try { Files.deleteIfExists(path); } catch (IOException e) { log.debug("删除文件失败: {}", path, e); }
                            });
                }
            }
        } catch (IOException e) {
            log.warn("删除 Skill 文件夹失败: id={}, error={}", id, e.getMessage());
        }

        log.info("Skill 已注销: id={}", id);
        return ApiResponse.ok();
    }

    /**
     * 启用 Skill（通过 metadata.status=enabled 控制）。
     *
     * <p>TODO Phase B.6: 原实现会把状态写回 SKILL.md（靠老 Serializer），已随 v2 重写拆除。
     * 当前仅更新内存注册表，待 Phase B.6 接入新 parser/serializer 后恢复文件回写。</p>
     *
     * @param id Skill ID
     * @return 204 成功，404 不存在，400 类型不支持
     */
    @PostMapping("/skills/{id}/enable")
    public ApiResponse<?> enableSkill(@PathVariable String id) {
        log.info("启用 Skill: id={}", id);
        toggleSkillStatus(id, "enabled");
        return ApiResponse.ok();
    }

    /**
     * 禁用 Skill（通过 metadata.status=disabled 控制）。
     *
     * <p>TODO Phase B.6: 同 {@link #enableSkill(String)}，当前仅更新内存。</p>
     *
     * @param id Skill ID
     * @return 204 成功，404 不存在，400 类型不支持
     */
    @PostMapping("/skills/{id}/disable")
    public ApiResponse<?> disableSkill(@PathVariable String id) {
        log.info("禁用 Skill: id={}", id);
        toggleSkillStatus(id, "disabled");
        return ApiResponse.ok();
    }

    private void toggleSkillStatus(String id, String status) {
        Optional<SkillDefinition> skillOpt = skillRegistry.find(id);
        if (skillOpt.isEmpty()) {
            log.warn("Skill 不存在: id={}", id);
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Skill 不存在: id=" + id);
        }

        SkillDefinition skill = skillOpt.get();

        // 仅允许用户定义或市场安装的 Skill 修改状态
        if (!(skill.source() instanceof SkillSource.UserDefined)
                && !(skill.source() instanceof SkillSource.Marketplace)) {
            log.warn("尝试变更非用户定义 Skill 状态被拒绝: id={}, status={}", id, status);
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "只能启用/禁用用户创建或市场安装的 Skill");
        }

        Map<String, String> metadata = new HashMap<>(skill.metadata() != null ? skill.metadata() : Map.of());
        metadata.put("status", status);

        SkillDefinition updated = skill.toBuilder()
                .metadata(metadata)
                .build();

        skillRegistry.register(updated);
        log.info("Skill 状态更新成功: id={}, status={}（文件回写待 Phase B.6）", id, status);
    }

    // ── Skill Markdown 端点 ─────────────────────────────────

    /**
     * 获取指定 Skill 的 Markdown 内容。
     *
     * <p>TODO Phase B.6: 原实现通过老 Serializer 序列化，已拆除。</p>
     */
    @GetMapping(value = "/skills/{id}/markdown", produces = "text/markdown")
    public ApiResponse<?> getSkillMarkdown(@PathVariable String id) {
        // TODO Phase B.6: 接入新 Serializer（或直接读文件）
        throw new ResponseStatusException(HttpStatus.NOT_IMPLEMENTED,
                "Skill Markdown 读取端点待 Phase B.6 重接");
    }

    /**
     * 通过 Markdown 内容更新指定 Skill。
     *
     * <p>TODO Phase B.6: 原实现依赖老 Parser/Loader，已拆除。</p>
     */
    @PutMapping(value = "/skills/{id}/markdown", consumes = "text/plain")
    public ApiResponse<?> updateSkillMarkdown(@PathVariable String id,
                                              @RequestBody String content) {
        // TODO Phase B.6: 接入新 MarkdownSkillParser + SkillInstaller
        throw new ResponseStatusException(HttpStatus.NOT_IMPLEMENTED,
                "Skill Markdown 更新端点待 Phase B.6 重接新 parser + SkillInstaller");
    }

    // ── 辅助方法 ──────────────────────────────────────────

    private String getString(Map<String, Object> map, String key) {
        Object value = map.get(key);
        return value != null ? value.toString() : null;
    }

    // ── MCP Server 端点 ─────────────────────────────────────

    /**
     * 获取 MCP 环境状态（npx 可用性等）。
     *
     * <p>前端据此展示环境依赖提示，例如 Node.js 未安装时引导用户安装。</p>
     *
     * @return 包含 npxAvailable 的状态 Map
     */
    @GetMapping("/mcp/status")
    public ApiResponse<?> getMcpStatus() {
        boolean npxAvailable = checkNpxAvailable();
        return ApiResponse.ok(Map.of("npxAvailable", npxAvailable));
    }

    /**
     * 获取所有 MCP Server 列表。
     *
     * @return MCP Server 扁平化 DTO 列表
     */
    @GetMapping("/mcp/servers")
    public ApiResponse<?> listMcpServers() {
        log.debug("查询 MCP Server 列表");
        var dtos = mcpServerRegistry.listServers().stream()
                .map(this::toMcpServerDto)
                .toList();
        return ApiResponse.ok(dtos);
    }

    /**
     * 获取指定 MCP Server 详情。
     *
     * @param name Server 名称
     * @return Server 扁平化 DTO，不存在返回 404
     */
    @GetMapping("/mcp/servers/{name}")
    public ApiResponse<?> getMcpServer(@PathVariable String name) {
        var server = mcpServerRegistry.getServer(name)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "MCP Server 不存在: name=" + name));
        return ApiResponse.ok(toMcpServerDto(server));
    }

    /**
     * 连接指定 MCP Server。
     *
     * @param name Server 名称
     * @return 202 已接受，404 不存在
     */
    @PostMapping("/mcp/servers/{name}/connect")
    public ApiResponse<?> connectMcpServer(@PathVariable String name) {
        var serverOpt = mcpServerRegistry.getServer(name);
        if (serverOpt.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "MCP Server 不存在: name=" + name);
        }

        mcpServerRegistry.connectServer(serverOpt.get().config());
        log.info("MCP Server 连接请求已接受: name={}", name);
        return ApiResponse.ok();
    }

    /**
     * 断开指定 MCP Server。
     *
     * @param name Server 名称
     * @return 204 成功，404 不存在
     */
    @PostMapping("/mcp/servers/{name}/disconnect")
    public ApiResponse<?> disconnectMcpServer(@PathVariable String name) {
        var serverOpt = mcpServerRegistry.getServer(name);
        if (serverOpt.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "MCP Server 不存在: name=" + name);
        }

        mcpServerRegistry.disconnectServer(name);
        log.info("MCP Server 已断开: name={}", name);
        return ApiResponse.ok();
    }

    /**
     * 获取指定 MCP Server 的工具列表。
     *
     * @param name Server 名称
     * @return 工具列表，Server 不存在返回 404
     */
    @GetMapping("/mcp/servers/{name}/tools")
    public ApiResponse<?> getMcpServerTools(@PathVariable String name) {
        var serverOpt = mcpServerRegistry.getServer(name);
        if (serverOpt.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "MCP Server 不存在: name=" + name);
        }

        List<ToolContract> tools = toolRegistry.getToolsByServer(name);
        return ApiResponse.ok(tools);
    }

    /**
     * 获取 MCP Server 连接日志。
     *
     * @param name 服务器名称
     * @return 连接日志列表（按时间倒序）
     */
    @GetMapping("/mcp/servers/{name}/connection-logs")
    public ApiResponse<?> getMcpServerConnectionLogs(@PathVariable String name) {
        var serverOpt = mcpServerRegistry.getServer(name);
        if (serverOpt.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "MCP Server 不存在: name=" + name);
        }

        var logs = mcpServerRegistry.getConnectionLogs(name);
        return ApiResponse.ok(logs);
    }

    /**
     * 创建 MCP Server。
     *
     * @param request 创建请求（包含 name 和 config）
     * @return 201 创建成功，400 参数错误
     */
    @PostMapping("/mcp/servers")
    public ApiResponse<?> createMcpServer(@RequestBody Map<String, Object> request) {
        log.debug("创建 MCP Server: request={}", request);

        try {
            String name = getString(request, "name");
            if (name == null || name.isBlank()) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "name 不能为空");
            }

            // 检查是否已存在
            if (mcpServerRegistry.getServer(name).isPresent()) {
                throw new ResponseStatusException(HttpStatus.CONFLICT, "MCP Server 已存在: name=" + name);
            }

            // 构建配置
            McpServerConfig config = buildMcpServerConfig(name, request);

            // 初始化并连接
            mcpServerRegistry.initializeAll(List.of(config));
            if (config.autoConnect()) {
                mcpServerRegistry.connectServer(config);
            }

            log.info("MCP Server 创建成功: name={}", name);
            return ApiResponse.ok(mcpServerRegistry.getServer(name).orElse(null));
        } catch (IllegalArgumentException e) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, e.getMessage());
        } catch (Exception e) {
            log.error("创建 MCP Server 失败", e);
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "创建失败: " + e.getMessage());
        }
    }

    /**
     * 更新 MCP Server。
     *
     * @param name Server 名称
     * @param request 更新请求（包含 config）
     * @return 200 更新成功，404 不存在，400 参数错误
     */
    @PutMapping("/mcp/servers/{name}")
    public ApiResponse<?> updateMcpServer(@PathVariable String name,
                                          @RequestBody Map<String, Object> request) {
        log.debug("更新 MCP Server: name={}, request={}", name, request);

        // 检查是否存在
        var existingOpt = mcpServerRegistry.getServer(name);
        if (existingOpt.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "MCP Server 不存在: name=" + name);
        }

        try {
            // 先断开连接
            mcpServerRegistry.disconnectServer(name);

            // 构建新配置（保持名称不变）
            McpServerConfig config = buildMcpServerConfig(name, request);

            // 重新初始化并连接
            mcpServerRegistry.initializeAll(List.of(config));
            if (config.autoConnect()) {
                mcpServerRegistry.connectServer(config);
            }

            log.info("MCP Server 更新成功: name={}", name);
            return ApiResponse.ok(mcpServerRegistry.getServer(name).orElse(null));
        } catch (IllegalArgumentException e) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, e.getMessage());
        } catch (Exception e) {
            log.error("更新 MCP Server 失败: name={}", name, e);
            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "更新失败: " + e.getMessage());
        }
    }

    /**
     * 删除 MCP Server。
     *
     * @param name Server 名称
     * @return 204 删除成功，404 不存在
     */
    @DeleteMapping("/mcp/servers/{name}")
    public ApiResponse<?> deleteMcpServer(@PathVariable String name) {
        log.debug("删除 MCP Server: name={}", name);

        var serverOpt = mcpServerRegistry.getServer(name);
        if (serverOpt.isEmpty()) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "MCP Server 不存在: name=" + name);
        }

        // 断开连接（这会注销工具）
        mcpServerRegistry.disconnectServer(name);

        // 注意：McpServerRegistry 没有公开的 remove 方法，但断开连接后工具已注销
        // 如果需要完全移除注册表条目，需要扩展 McpServerRegistry

        log.info("MCP Server 已删除: name={}", name);
        return ApiResponse.ok();
    }

    // ── MCP Server 辅助方法 ──────────────────────────────────────────

    private McpServerConfig buildMcpServerConfig(String name, Map<String, Object> request) {
        @SuppressWarnings("unchecked")
        Map<String, Object> configMap = (Map<String, Object>) request.get("config");
        if (configMap == null) {
            throw new IllegalArgumentException("config 不能为空");
        }

        // 解析 transport
        String transportStr = getString(configMap, "transport");
        if (transportStr == null || transportStr.isBlank()) {
            throw new IllegalArgumentException("transport 不能为空");
        }
        TransportType transport = parseTransportType(transportStr);

        // 解析其他字段
        String command = getString(configMap, "command");
        @SuppressWarnings("unchecked")
        List<String> args = configMap.get("args") instanceof List<?>
                ? (List<String>) configMap.get("args")
                : new ArrayList<>();
        String url = getString(configMap, "url");
        @SuppressWarnings("unchecked")
        Map<String, String> env = configMap.get("env") instanceof Map<?, ?>
                ? (Map<String, String>) configMap.get("env")
                : Map.of();

        // 解析可选字段
        Duration timeout = parseDuration(configMap.get("timeout"), McpServerConfig.DEFAULT_TIMEOUT);
        boolean autoConnect = getBooleanOrDefault(configMap, "autoConnect", false);
        boolean reconnect = getBooleanOrDefault(configMap, "reconnect", true);
        Duration reconnectDelay = parseDuration(configMap.get("reconnectDelay"),
                McpServerConfig.DEFAULT_RECONNECT_DELAY);
        int maxReconnectAttempts = getIntOrDefault(configMap, "maxReconnectAttempts",
                McpServerConfig.DEFAULT_MAX_RECONNECT_ATTEMPTS);
        Duration healthCheckInterval = parseDuration(configMap.get("healthCheckInterval"),
                McpServerConfig.DEFAULT_HEALTH_CHECK_INTERVAL);

        return McpServerConfig.builder()
                .name(name)
                .transport(transport)
                .command(command)
                .args(args)
                .url(url)
                .env(env)
                .timeout(timeout)
                .autoConnect(autoConnect)
                .reconnect(reconnect)
                .reconnectDelay(reconnectDelay)
                .maxReconnectAttempts(maxReconnectAttempts)
                .healthCheckInterval(healthCheckInterval)
                .build();
    }

    private TransportType parseTransportType(String transportStr) {
        return switch (transportStr.toUpperCase()) {
            case "STDIO" -> TransportType.STDIO;
            case "STREAMABLE_HTTP", "HTTP" -> TransportType.STREAMABLE_HTTP;
            case "SSE", "SSE_LEGACY" -> TransportType.SSE_LEGACY;
            default -> throw new IllegalArgumentException("不支持的传输类型: " + transportStr);
        };
    }

    private Duration parseDuration(Object value, Duration defaultValue) {
        if (value == null) return defaultValue;
        if (value instanceof Number) {
            return Duration.ofSeconds(((Number) value).longValue());
        }
        if (value instanceof String str) {
            try {
                return Duration.parse(str);
            } catch (Exception e) {
                return Duration.ofSeconds(Long.parseLong(str));
            }
        }
        return defaultValue;
    }

    private boolean getBooleanOrDefault(Map<String, Object> map, String key, boolean defaultValue) {
        Object value = map.get(key);
        if (value == null) return defaultValue;
        if (value instanceof Boolean) return (Boolean) value;
        return Boolean.parseBoolean(value.toString());
    }

    private int getIntOrDefault(Map<String, Object> map, String key, int defaultValue) {
        Object value = map.get(key);
        if (value == null) return defaultValue;
        if (value instanceof Number) return ((Number) value).intValue();
        try {
            return Integer.parseInt(value.toString());
        } catch (NumberFormatException e) {
            return defaultValue;
        }
    }

    // ── npx 可用性检查 ──────────────────────────────────────────

    /**
     * 检查 npx 是否可用。
     *
     * <p>Windows 上 npx 是 .cmd 批处理脚本，需要通过 {@code cmd /c} 执行。</p>
     */
    private boolean checkNpxAvailable() {
        try {
            ProcessBuilder pb;
            if (System.getProperty("os.name", "").toLowerCase().contains("win")) {
                pb = new ProcessBuilder("cmd", "/c", "npx", "--version");
            } else {
                pb = new ProcessBuilder("npx", "--version");
            }
            var process = pb.redirectErrorStream(true).start();
            boolean finished = process.waitFor(5, TimeUnit.SECONDS);
            if (!finished) {
                process.destroyForcibly();
                return false;
            }
            return process.exitValue() == 0;
        } catch (Exception e) {
            return false;
        }
    }

    // ── McpServerEntry → 前端 DTO 转换 ──────────────────────────────

    /**
     * 将 McpServerEntry 转换为前端期望的扁平 DTO。
     *
     * <p>前端 McpServer 类型期望 name/state/toolCount 等顶层字段，
     * 而 McpServerEntry 的 name 嵌套在 config 中，且 client 字段不应序列化。</p>
     */
    private Map<String, Object> toMcpServerDto(com.lifepilot.mcp.registry.McpServerEntry entry) {
        var dto = new HashMap<String, Object>();
        var config = entry.config();
        dto.put("name", config.name());
        dto.put("state", entry.state().name());
        dto.put("toolCount", toolRegistry.getToolsByServer(config.name()).size());
        dto.put("connectedSince", entry.connectedSince() != null ? entry.connectedSince().toString() : null);
        dto.put("lastError", entry.lastError());

        // 嵌套 config 供前端编辑用
        var configDto = new HashMap<String, Object>();
        // 前端 Select 使用小写值：stdio / sse
        configDto.put("transport", switch (config.transport()) {
            case STDIO -> "stdio";
            case SSE_LEGACY -> "sse";
            case STREAMABLE_HTTP -> "streamable_http";
        });
        configDto.put("command", config.command());
        configDto.put("args", config.args());
        configDto.put("env", config.env());
        configDto.put("url", config.url());
        configDto.put("autoConnect", config.autoConnect());
        configDto.put("reconnect", config.reconnect());
        // 前端期望的字段名和单位
        configDto.put("timeoutSeconds", config.timeout().toSeconds());
        configDto.put("maxRetries", config.maxReconnectAttempts());
        dto.put("config", configDto);

        return dto;
    }
}
