package com.lifepilot.skill.model;

import org.springframework.lang.Nullable;

import java.time.Instant;

/**
 * Skill 来源类型 — 穷举四种来源。
 *
 * <p>优先级：Builtin(3) &gt; UserDefined/Marketplace(2) &gt; AutoGenerated(1)。
 *
 * @author zsg
 * @since 2026-07-28
 */
public sealed interface SkillSource permits SkillSource.Builtin, SkillSource.UserDefined, SkillSource.AutoGenerated, SkillSource.Marketplace {

    /**
     * 来源优先级：Builtin(3) &gt; UserDefined/Marketplace(2) &gt; AutoGenerated(1)。
     *
     * @return 优先级数值
     */
    default int priority() {
        return switch (this) {
            case Builtin _ -> 3;
            case UserDefined _ -> 2;
            case Marketplace _ -> 2;
            case AutoGenerated _ -> 1;
        };
    }

    /** 内置来源 — Java 原生实现。 */
    record Builtin() implements SkillSource {}

    /**
     * 用户定义来源 — Markdown 声明式。
     *
     * @param filePath     Skill 文件夹路径
     * @param lastModified 文件最后修改时间，用于热加载变更检测
     */
    record UserDefined(String filePath, @Nullable Instant lastModified) implements SkillSource {
        /** 兼容旧构造器。 */
        public UserDefined(String filePath) {
            this(filePath, null);
        }
    }

    /**
     * 自动生成来源 — Agent 自生成。
     *
     * @param generatorTraceId 生成时的 traceId
     * @param generatedAt      生成时间
     * @param triggerRequest   触发生成的用户请求
     * @param userConfirmed    用户是否已确认启用
     */
    record AutoGenerated(
            String generatorTraceId,
            @Nullable Instant generatedAt,
            @Nullable String triggerRequest,
            boolean userConfirmed
    ) implements SkillSource {
        /** 兼容旧构造器。 */
        public AutoGenerated(String generatorTraceId) {
            this(generatorTraceId, Instant.now(), null, false);
        }
    }

    /**
     * 市场来源 — 从 Skill 市场安装。
     *
     * @param packageId      市场包 ID
     * @param indexSourceUrl 索引源 URL
     * @param installedAt    安装时间
     */
    record Marketplace(
            String packageId,
            String indexSourceUrl,
            Instant installedAt
    ) implements SkillSource {}
}
