package com.lifepilot.skill.model;

/**
 * Skill 来源类型 — 穷举三种来源。
 *
 * <p>优先级：Builtin(3) &gt; UserDefined(2) &gt; AutoGenerated(1)。
 *
 * @author zsg
 * @since 2026-07-28
 */
public sealed interface SkillSource permits SkillSource.Builtin, SkillSource.UserDefined, SkillSource.AutoGenerated {

    /**
     * 来源优先级：Builtin(3) &gt; UserDefined(2) &gt; AutoGenerated(1)。
     *
     * @return 优先级数值
     */
    default int priority() {
        return switch (this) {
            case Builtin _ -> 3;
            case UserDefined _ -> 2;
            case AutoGenerated _ -> 1;
        };
    }

    /** 内置来源 — Java 原生实现。 */
    record Builtin() implements SkillSource {}

    /** 用户定义来源 — YAML 声明式。 */
    record UserDefined(String filePath) implements SkillSource {}

    /** 自动生成来源 — Agent 自生成。 */
    record AutoGenerated(String generatorTraceId) implements SkillSource {}
}
