package com.lifepilot.skill.generation;

import com.lifepilot.llm.LlmRequest;
import com.lifepilot.llm.LlmResponse;
import com.lifepilot.llm.LlmRouter;
import com.lifepilot.prompt.PromptRegistry;
import com.lifepilot.skill.config.SkillConfigProperties;
import com.lifepilot.skill.markdown.MarkdownSkillParser;
import com.lifepilot.skill.markdown.MarkdownSkillSerializer;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.model.SkillSource;
import com.lifepilot.skill.registry.SkillRegistry;
import com.lifepilot.skill.validation.SkillValidationPipeline;
import com.lifepilot.skill.validation.SkillValidationResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * {@link SkillGenerator} 单元测试。
 *
 * <p>验证生成流程使用新字段名（instructions/suggestedTools），
 * 以及 confirmAndPersist 正确写入文件夹结构。</p>
 *
 * @author zsg
 * @since 2026-07-28
 */
class SkillGeneratorTest {

    private LlmRouter llmRouter;
    private SkillValidationPipeline validationPipeline;
    private MarkdownSkillParser markdownParser;
    private MarkdownSkillSerializer markdownSerializer;
    private SkillRegistry skillRegistry;
    private SkillConfigProperties config;
    private PromptRegistry promptRegistry;
    private SkillGenerator generator;

    @TempDir
    Path tempDir;

    @BeforeEach
    void setUp() {
        llmRouter = mock(LlmRouter.class);
        validationPipeline = mock(SkillValidationPipeline.class);
        markdownParser = mock(MarkdownSkillParser.class);
        markdownSerializer = mock(MarkdownSkillSerializer.class);
        skillRegistry = mock(SkillRegistry.class);
        promptRegistry = mock(PromptRegistry.class);

        config = new SkillConfigProperties();
        config.setDirectory(tempDir.toString());

        when(promptRegistry.render(anyString(), anyMap())).thenReturn("生成 Prompt");
        when(skillRegistry.listSummaries()).thenReturn(List.of());

        generator = new SkillGenerator(
                llmRouter, validationPipeline, markdownParser,
                markdownSerializer, skillRegistry, config, promptRegistry
        );
    }

    // ── 生成成功 ──

    @Test
    void generate_LLM返回有效SKILL_md_生成成功() {
        // 准备
        var gap = new SkillGap(0.8, "writing-assistant", "写作助手",
                "帮我写一篇文章", List.of("search"), "用户需要写作辅助");

        var llmContent = """
                ---
                id: writing-assistant
                name: 写作助手
                description: 辅助用户进行各类写作
                version: 1.0.0
                suggested-tools:
                  - search
                ---
                
                # 写作助手
                
                你是一个专业的写作助手，帮助用户进行各类写作任务。
                """;

        when(llmRouter.call(any(LlmRequest.class)))
                .thenReturn(new LlmResponse(llmContent, 100, 200, "openai", "gpt-4", 500, false));
        when(validationPipeline.validate(anyString()))
                .thenReturn(SkillValidationResult.allPassed());

        var definition = SkillDefinition.builder()
                .id("writing-assistant")
                .name("写作助手")
                .description("辅助用户进行各类写作")
                .version("1.0.0")
                .source(new SkillSource.Builtin())
                .instructions("你是一个专业的写作助手，帮助用户进行各类写作任务。")
                .suggestedTools(List.of("search"))
                .metadata(Map.of())
                .build();

        when(markdownParser.parse(anyString()))
                .thenReturn(new MarkdownSkillParser.ParseResult(true, definition, List.of(), Map.of()));

        // 执行
        var result = generator.generate(gap);

        // 验证
        assertThat(result.success()).isTrue();
        assertThat(result.definition()).isNotNull();
        assertThat(result.definition().id()).isEqualTo("writing-assistant");
        assertThat(result.definition().instructions()).isEqualTo("你是一个专业的写作助手，帮助用户进行各类写作任务。");
        assertThat(result.definition().suggestedTools()).containsExactly("search");
        // source 应被替换为 AutoGenerated
        assertThat(result.definition().source()).isInstanceOf(SkillSource.AutoGenerated.class);
    }

    // ── 验证失败 ──

    @Test
    void generate_三重验证失败_返回失败结果() {
        var gap = new SkillGap(0.7, "bad-skill", "坏Skill",
                "请求", List.of(), "原因");

        when(llmRouter.call(any(LlmRequest.class)))
                .thenReturn(new LlmResponse("内容", 50, 100, "openai", "gpt-4", 300, false));
        when(validationPipeline.validate(anyString()))
                .thenReturn(SkillValidationResult.failed(
                        SkillValidationResult.ValidationStage.FORMAT,
                        List.of("缺少必填字段 id")));

        var result = generator.generate(gap);

        assertThat(result.success()).isFalse();
        assertThat(result.validationResult()).isNotNull();
        assertThat(result.validationResult().failedStage())
                .isEqualTo(SkillValidationResult.ValidationStage.FORMAT);
    }

    // ── LLM 调用失败 ──

    @Test
    void generate_LLM调用异常_返回错误结果() {
        var gap = new SkillGap(0.9, "fail-skill", "失败Skill",
                "请求", List.of(), "原因");

        when(llmRouter.call(any(LlmRequest.class)))
                .thenThrow(new RuntimeException("LLM 服务不可用"));

        var result = generator.generate(gap);

        assertThat(result.success()).isFalse();
        assertThat(result.errorMessage()).contains("LLM 服务不可用");
    }

    // ── confirmAndPersist ──

    @Test
    void confirmAndPersist_写入文件夹结构并注册() throws IOException {
        var autoSource = new SkillSource.AutoGenerated("trace-001", null, "用户请求", false);
        var definition = SkillDefinition.builder()
                .id("auto-skill")
                .name("自动Skill")
                .description("自动生成的Skill")
                .version("1.0.0")
                .source(autoSource)
                .instructions("自动生成的指令内容。")
                .suggestedTools(List.of("tool-a"))
                .metadata(Map.of())
                .build();

        when(markdownSerializer.serialize(any(SkillDefinition.class)))
                .thenReturn("---\nid: auto-skill\n---\n\n# 自动Skill\n\n自动生成的指令内容。\n");
        when(skillRegistry.register(any(SkillDefinition.class))).thenReturn(true);

        boolean result = generator.confirmAndPersist(definition);

        assertThat(result).isTrue();

        // 验证文件夹结构：auto/{skill-id}/SKILL.md
        Path skillFile = tempDir.resolve("auto").resolve("auto-skill").resolve("SKILL.md");
        assertThat(skillFile).exists();
        String content = Files.readString(skillFile);
        assertThat(content).contains("auto-skill");

        // 验证注册时 userConfirmed 为 true
        verify(skillRegistry).register(argThat(def -> {
            if (def.source() instanceof SkillSource.AutoGenerated ag) {
                return ag.userConfirmed();
            }
            return false;
        }));
    }

    // ── extractMarkdown ──

    @Test
    void extractMarkdown_代码块包裹_正确提取() {
        String wrapped = "```markdown\n---\nid: test\n---\n\n# Test\n\nContent\n```";
        String result = SkillGenerator.extractMarkdown(wrapped);
        assertThat(result).startsWith("---");
        assertThat(result).contains("id: test");
        assertThat(result).doesNotContain("```");
    }

    @Test
    void extractMarkdown_无代码块_原样返回() {
        String raw = "---\nid: test\n---\n\n# Test\n\nContent";
        String result = SkillGenerator.extractMarkdown(raw);
        assertThat(result).isEqualTo(raw);
    }
}
