import { describe, expect, it } from 'vitest'
import { isInternalCapabilityId } from './liveCapabilities'

describe('liveCapabilities', () => {
  it('识别内部意图、路由和能力核查标识', () => {
    expect(isInternalCapabilityId(null)).toBe(true)
    expect(isInternalCapabilityId('intent.match')).toBe(true)
    expect(isInternalCapabilityId('router.plan')).toBe(true)
    expect(isInternalCapabilityId('tool.search')).toBe(true)
    expect(isInternalCapabilityId('capability.assess')).toBe(true)
    expect(isInternalCapabilityId('experience.match')).toBe(true)
    expect(isInternalCapabilityId('memory.extract')).toBe(true)
    expect(isInternalCapabilityId('memory.consolidation')).toBe(true)
    expect(isInternalCapabilityId('memory.index')).toBe(true)
    expect(isInternalCapabilityId('memory.revalidation')).toBe(true)
    expect(isInternalCapabilityId('decision.signal')).toBe(true)
    expect(isInternalCapabilityId('context.assemble')).toBe(true)
    expect(isInternalCapabilityId('意图识别')).toBe(true)
    expect(isInternalCapabilityId('经验匹配')).toBe(true)
    expect(isInternalCapabilityId('记忆沉淀')).toBe(true)
    expect(isInternalCapabilityId('记忆索引')).toBe(true)
    expect(isInternalCapabilityId('决策增强')).toBe(true)
    expect(isInternalCapabilityId('上下文装配')).toBe(true)
    expect(isInternalCapabilityId('准备对话上下文')).toBe(true)
    expect(isInternalCapabilityId('loading context')).toBe(true)
    expect(isInternalCapabilityId('Tool Search')).toBe(true)
    expect(isInternalCapabilityId('tool-search')).toBe(true)
    expect(isInternalCapabilityId('Capability Check')).toBe(true)
    expect(isInternalCapabilityId('Capability Registry')).toBe(true)
    expect(isInternalCapabilityId('Experience Matching')).toBe(true)
    expect(isInternalCapabilityId('Context Assembly')).toBe(true)
    expect(isInternalCapabilityId('调用核查')).toBe(true)
    expect(isInternalCapabilityId('检查能力')).toBe(true)
    expect(isInternalCapabilityId('能力注册')).toBe(true)
  })

  it('真实工具和技能不被过滤', () => {
    expect(isInternalCapabilityId('web.search')).toBe(false)
    expect(isInternalCapabilityId('shell.exec')).toBe(false)
    expect(isInternalCapabilityId('knowledge.search')).toBe(false)
    expect(isInternalCapabilityId('skill.load')).toBe(false)
    expect(isInternalCapabilityId('memory.search')).toBe(false)
    expect(isInternalCapabilityId('memory.recall')).toBe(false)
  })
})
