package com.lifepilot.skill;

import com.lifepilot.skill.activation.SkillActivator;
import com.lifepilot.skill.model.SkillActivation;
import com.lifepilot.skill.activation.SkillMetricsTracker;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.model.SkillSource;
import com.lifepilot.skill.registry.SkillRegistry;
import net.jqwik.api.*;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.lang.NonNull;

import java.util.Map;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Property 2+3: 激活内容一致性 + 激活幂等性 属性测试。
 *
 * <p>Property 2: 对任意已注册的非未确认 AutoGenerated SkillDefinition，
 * activate() 返回的 SkillActivation 的 instructions 和 suggestedTools 与原始定义一致。</p>
 *
 * <p>Property 3: 对同一 Skill 多次调用 activate()，返回内容完全相同。</p>
 *
 * @author zsg
 * @since 2026-03-08
 */
class SkillActivator属性测试 {

    // ── Property 2: 激活结果与定义内容一致 ──

    @Property(tries = 100)
    @Label("Feature: skill-system-refactor, Property 2: 激活结果与定义内容一致")
    void 激活结果的instructions和suggestedTools与原始定义一致(
            @ForAll("activatableSkillDefinitions") SkillDefinition definition) {

        // 构建测试环境
        var registry = new StubSkillRegistry();
        registry.addSkill(definition);
        var activator = new SkillActivator(registry, new SkillMetricsTracker(), new NoOpEventPublisher(),
                new com.lifepilot.skill.config.SkillConfigProperties());

        // 激活
        SkillActivation activation = activator.activate(definition.id());

        // **Validates: AC-2.1**
        assertThat(activation.skillId()).isEqualTo(definition.id());
        assertThat(activation.instructions()).isEqualTo(definition.instructions());
        assertThat(activation.suggestedTools()).isEqualTo(definition.suggestedTools());
    }

    // ── Property 3: 激活幂等性 ──

    @Property(tries = 100)
    @Label("Feature: skill-system-refactor, Property 3: 激活幂等性")
    void 多次激活同一Skill_返回内容完全相同(
            @ForAll("activatableSkillDefinitions") SkillDefinition definition) {

        var registry = new StubSkillRegistry();
        registry.addSkill(definition);
        var activator = new SkillActivator(registry, new SkillMetricsTracker(), new NoOpEventPublisher(),
                new com.lifepilot.skill.config.SkillConfigProperties());

        // 多次激活
        SkillActivation first = activator.activate(definition.id());
        SkillActivation second = activator.activate(definition.id());
        SkillActivation third = activator.activate(definition.id());

        // **Validates: P-2**
        assertThat(second.skillId()).isEqualTo(first.skillId());
        assertThat(second.instructions()).isEqualTo(first.instructions());
        assertThat(second.suggestedTools()).isEqualTo(first.suggestedTools());

        assertThat(third.skillId()).isEqualTo(first.skillId());
        assertThat(third.instructions()).isEqualTo(first.instructions());
        assertThat(third.suggestedTools()).isEqualTo(first.suggestedTools());
    }

    // ── 生成器 ──

    @Provide
    Arbitrary<SkillDefinition> activatableSkillDefinitions() {
        // 可激活的来源：UserDefined（排除未确认的 AutoGenerated）
        var sourceArb = Arbitraries.of(
                (SkillSource) new SkillSource.UserDefined("/tmp/skills/test", null),
                new SkillSource.UserDefined("/tmp/skills/test2", null)
        );

        var idArb = Arbitraries.strings()
                .withCharRange('a', 'z')
                .numeric()
                .withChars('-')
                .ofMinLength(1).ofMaxLength(20)
                .filter(s -> !s.isBlank() && s.matches("^[a-z0-9-]+$"));

        var nameArb = safeString(1, 30);
        var descArb = safeString(1, 50);
        var instructionsArb = safeString(1, 100);

        var toolArb = Arbitraries.strings()
                .withCharRange('a', 'z')
                .withChars('-', '_')
                .ofMinLength(1).ofMaxLength(15)
                .filter(s -> !s.isBlank());
        var toolsArb = toolArb.list().ofMinSize(0).ofMaxSize(5);

        return Combinators.combine(idArb, nameArb, descArb, instructionsArb, toolsArb, sourceArb)
                .as((id, name, desc, instructions, tools, source) ->
                        SkillDefinition.builder()
                                .id(id)
                                .name(name)
                                .description(desc)
                                .version("1.0.0")
                                .source(source)
                                .instructions(instructions)
                                .suggestedTools(tools)
                                .metadata(Map.of())
                                .build()
                );
    }

    private Arbitrary<String> safeString(int minLen, int maxLen) {
        return Arbitraries.strings()
                .withCharRange('a', 'z')
                .withCharRange('A', 'Z')
                .withCharRange('0', '9')
                .withChars(' ', '-', '_')
                .ofMinLength(minLen).ofMaxLength(maxLen)
                .filter(s -> !s.isBlank());
    }

    // ── Stub 内部类 ──

    /**
     * 简易 SkillRegistry 桩 — 绕过构造依赖，仅实现 find()。
     */
    private static class StubSkillRegistry extends SkillRegistry {

        private final java.util.concurrent.ConcurrentHashMap<String, SkillDefinition> store =
                new java.util.concurrent.ConcurrentHashMap<>();

        StubSkillRegistry() {
            super(null, null, null, new com.lifepilot.skill.config.SkillConfigProperties());
        }

        void addSkill(SkillDefinition definition) {
            store.put(definition.id(), definition);
        }

        @Override
        public Optional<SkillDefinition> find(String skillId) {
            return Optional.ofNullable(store.get(skillId));
        }
    }

    /** 空操作事件发布器。 */
    private static class NoOpEventPublisher implements ApplicationEventPublisher {
        @Override
        public void publishEvent(@NonNull Object event) {
            // 不做任何操作
        }
    }
}
