package com.lifepilot.skill.config;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Skill 系统配置属性。
 *
 * <p>绑定 {@code lifepilot.skills} 配置前缀。使用 JavaBean 风格以兼容 Spring Boot 配置绑定。</p>
 *
 * @author zsg
 * @since 2026-02-25
 */
@ConfigurationProperties(prefix = "lifepilot.skills")
public class SkillConfigProperties {

    /** Skill 系统总开关，默认 true。 */
    private boolean enabled = true;

    /** 最大并发激活数，默认 5。 */
    private int maxConcurrentActivations = 5;

    /** YAML Skill 文件目录，默认 ~/.lifepilot/skills。 */
    private String directory = System.getProperty("user.home") + "/.lifepilot/skills";

    /** 热加载防抖间隔（毫秒），默认 500。 */
    private long hotReloadDebounceMs = 500;

    /** 校验限制配置。 */
    private Validation validation = new Validation();

    /** 搜索配置。 */
    private Search search = new Search();

    /** Skill 自扩展配置。 */
    private AutoGeneration autoGeneration = new AutoGeneration();

    /** Shell 动作配置。 */
    private ShellAction shellAction = new ShellAction();

    /** 技能串联动作配置。 */
    private ChainAction chainAction = new ChainAction();

    /** HTTP 动作配置。 */
    private HttpAction httpAction = new HttpAction();

    public boolean isEnabled() { return enabled; }
    public void setEnabled(boolean enabled) { this.enabled = enabled; }

    public int getMaxConcurrentActivations() { return maxConcurrentActivations; }
    public void setMaxConcurrentActivations(int maxConcurrentActivations) { this.maxConcurrentActivations = maxConcurrentActivations; }

    public String getDirectory() { return directory; }
    public void setDirectory(String directory) { this.directory = directory; }

    public long getHotReloadDebounceMs() { return hotReloadDebounceMs; }
    public void setHotReloadDebounceMs(long hotReloadDebounceMs) { this.hotReloadDebounceMs = hotReloadDebounceMs; }

    public Validation getValidation() { return validation; }
    public void setValidation(Validation validation) { this.validation = validation; }

    public Search getSearch() { return search; }
    public void setSearch(Search search) { this.search = search; }

    public AutoGeneration getAutoGeneration() { return autoGeneration; }
    public void setAutoGeneration(AutoGeneration autoGeneration) { this.autoGeneration = autoGeneration; }

    public ShellAction getShellAction() { return shellAction; }
    public void setShellAction(ShellAction shellAction) { this.shellAction = shellAction; }

    public ChainAction getChainAction() { return chainAction; }
    public void setChainAction(ChainAction chainAction) { this.chainAction = chainAction; }

    public HttpAction getHttpAction() { return httpAction; }
    public void setHttpAction(HttpAction httpAction) { this.httpAction = httpAction; }

    /**
     * Skill 定义校验限制配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class Validation {

        /** 名称最大长度，默认 128。 */
        private int maxNameLength = 128;

        /** System Prompt 最大长度，默认 10000。 */
        private int maxSystemPromptLength = 10000;

        /** AUTO_GENERATED 来源的 maxTokens 上限，默认 10000。 */
        private int autoGeneratedMaxTokens = 10000;

        /** AUTO_GENERATED 来源的 maxSteps 上限，默认 15。 */
        private int autoGeneratedMaxSteps = 15;

        /** AUTO_GENERATED 来源的 timeoutSeconds 上限，默认 180。 */
        private int autoGeneratedMaxTimeout = 180;

        public int getMaxNameLength() { return maxNameLength; }
        public void setMaxNameLength(int maxNameLength) { this.maxNameLength = maxNameLength; }

        public int getMaxSystemPromptLength() { return maxSystemPromptLength; }
        public void setMaxSystemPromptLength(int maxSystemPromptLength) { this.maxSystemPromptLength = maxSystemPromptLength; }

        public int getAutoGeneratedMaxTokens() { return autoGeneratedMaxTokens; }
        public void setAutoGeneratedMaxTokens(int autoGeneratedMaxTokens) { this.autoGeneratedMaxTokens = autoGeneratedMaxTokens; }

        public int getAutoGeneratedMaxSteps() { return autoGeneratedMaxSteps; }
        public void setAutoGeneratedMaxSteps(int autoGeneratedMaxSteps) { this.autoGeneratedMaxSteps = autoGeneratedMaxSteps; }

        public int getAutoGeneratedMaxTimeout() { return autoGeneratedMaxTimeout; }
        public void setAutoGeneratedMaxTimeout(int autoGeneratedMaxTimeout) { this.autoGeneratedMaxTimeout = autoGeneratedMaxTimeout; }
    }

    /**
     * Skill 搜索配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class Search {

        /** 默认搜索返回数量，默认 10。 */
        private int defaultTopK = 10;

        public int getDefaultTopK() { return defaultTopK; }
        public void setDefaultTopK(int defaultTopK) { this.defaultTopK = defaultTopK; }
    }

    /**
     * Skill 自扩展配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class AutoGeneration {

        /** 自扩展功能开关，默认 true。 */
        private boolean enabled = true;

        /** 缺口检测语义匹配阈值，低于此值判定存在缺口，默认 0.6。 */
        private double gapThreshold = 0.6;

        public boolean isEnabled() { return enabled; }
        public void setEnabled(boolean enabled) { this.enabled = enabled; }

        public double getGapThreshold() { return gapThreshold; }
        public void setGapThreshold(double gapThreshold) { this.gapThreshold = gapThreshold; }
    }

    /**
     * Shell 动作执行配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class ShellAction {

        /** Shell 命令最大超时时间（秒），默认 30。 */
        private int maxTimeoutSeconds = 30;

        public int getMaxTimeoutSeconds() { return maxTimeoutSeconds; }
        public void setMaxTimeoutSeconds(int maxTimeoutSeconds) { this.maxTimeoutSeconds = maxTimeoutSeconds; }
    }

    /**
     * 技能串联动作配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class ChainAction {

        /** 串联步骤数上限，默认 5。 */
        private int maxSteps = 5;

        public int getMaxSteps() { return maxSteps; }
        public void setMaxSteps(int maxSteps) { this.maxSteps = maxSteps; }
    }

    /**
     * HTTP 动作执行配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class HttpAction {

        /** SSRF 防护开关，默认 true。 */
        private boolean ssrfProtectionEnabled = true;

        public boolean isSsrfProtectionEnabled() { return ssrfProtectionEnabled; }
        public void setSsrfProtectionEnabled(boolean ssrfProtectionEnabled) { this.ssrfProtectionEnabled = ssrfProtectionEnabled; }
    }
}
