package com.lifepilot.skill.config;

import lombok.Getter;
import lombok.Setter;
import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Skill 系统配置属性。
 *
 * <p>绑定 {@code lifepilot.skills} 配置前缀。使用 JavaBean 风格以兼容 Spring Boot 配置绑定。</p>
 *
 * @author zsg
 * @since 2026-02-25
 */
@Setter
@Getter
@ConfigurationProperties(prefix = "lifepilot.skills")
public class SkillConfigProperties {

    /** Skill 系统总开关，默认 true。 */
    private boolean enabled = true;

    /** 最大并发激活数，默认 5。 */
    private int maxConcurrentActivations = 5;

    /** YAML Skill 文件目录，默认 ~/.zhiwei/skills。 */
    private String directory = System.getProperty("user.home") + "/.zhiwei/skills";

    /** 热加载防抖间隔（毫秒），默认 500。 */
    private long hotReloadDebounceMs = 500;

    /** Skill 定义文件名，默认 SKILL.md。 */
    private String skillFilename = "SKILL.md";

    /** 校验限制配置。 */
    private Validation validation = new Validation();

    /** 搜索配置。 */
    private Search search = new Search();

    /** Skill 自扩展配置。 */
    private AutoGeneration autoGeneration = new AutoGeneration();

    /** Shell 动作配置。 */
    private ShellAction shellAction = new ShellAction();

    /** 技能串联动作配置。 */
    private ChainAction chainAction = new ChainAction();

    /** HTTP 动作配置。 */
    private HttpAction httpAction = new HttpAction();

    /** 内置 Skill 配置。 */
    private Builtin builtin = new Builtin();

    /** 待办 Skill 扩展配置。 */
    private Todo todo = new Todo();

    public Builtin getBuiltin() { return builtin; }
    public void setBuiltin(Builtin builtin) { this.builtin = builtin; }

    public Todo getTodo() { return todo; }
    public void setTodo(Todo todo) { this.todo = todo; }

    /**
     * 待办 Skill 扩展配置（到期通知等）。
     *
     * @author zsg
     * @since 2026-03-19
     */
    public static class Todo {

        /** 到期通知开关，默认 true。 */
        private boolean dueNotificationEnabled = true;

        /** 到期检查间隔（秒），默认 60。 */
        private int dueCheckIntervalSeconds = 60;

        public boolean isDueNotificationEnabled() { return dueNotificationEnabled; }
        public void setDueNotificationEnabled(boolean dueNotificationEnabled) { this.dueNotificationEnabled = dueNotificationEnabled; }

        public int getDueCheckIntervalSeconds() { return dueCheckIntervalSeconds; }
        public void setDueCheckIntervalSeconds(int dueCheckIntervalSeconds) { this.dueCheckIntervalSeconds = dueCheckIntervalSeconds; }
    }

    /**
     * Skill 定义校验限制配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class Validation {

        /** 名称最大长度，默认 128。 */
        private int maxNameLength = 128;

        /** Instructions 最大长度，默认 10000。 */
        private int maxInstructionsLength = 10000;

        /** AUTO_GENERATED 来源的 maxTokens 上限，默认 10000。 */
        private int autoGeneratedMaxTokens = 10000;

        /** AUTO_GENERATED 来源的 maxSteps 上限，默认 15。 */
        private int autoGeneratedMaxSteps = 15;

        /** AUTO_GENERATED 来源的 timeoutSeconds 上限，默认 180。 */
        private int autoGeneratedMaxTimeout = 180;

        /** YAML Schema 校验的 max-steps 上限，默认 50。 */
        private int schemaMaxSteps = 50;

        /** YAML Schema 校验的 timeout-seconds 上限，默认 600。 */
        private int schemaMaxTimeoutSeconds = 600;

        public int getMaxNameLength() { return maxNameLength; }
        public void setMaxNameLength(int maxNameLength) { this.maxNameLength = maxNameLength; }

        public int getMaxInstructionsLength() { return maxInstructionsLength; }
        public void setMaxInstructionsLength(int maxInstructionsLength) { this.maxInstructionsLength = maxInstructionsLength; }

        public int getAutoGeneratedMaxTokens() { return autoGeneratedMaxTokens; }
        public void setAutoGeneratedMaxTokens(int autoGeneratedMaxTokens) { this.autoGeneratedMaxTokens = autoGeneratedMaxTokens; }

        public int getAutoGeneratedMaxSteps() { return autoGeneratedMaxSteps; }
        public void setAutoGeneratedMaxSteps(int autoGeneratedMaxSteps) { this.autoGeneratedMaxSteps = autoGeneratedMaxSteps; }

        public int getAutoGeneratedMaxTimeout() { return autoGeneratedMaxTimeout; }
        public void setAutoGeneratedMaxTimeout(int autoGeneratedMaxTimeout) { this.autoGeneratedMaxTimeout = autoGeneratedMaxTimeout; }

        public int getSchemaMaxSteps() { return schemaMaxSteps; }
        public void setSchemaMaxSteps(int schemaMaxSteps) { this.schemaMaxSteps = schemaMaxSteps; }

        public int getSchemaMaxTimeoutSeconds() { return schemaMaxTimeoutSeconds; }
        public void setSchemaMaxTimeoutSeconds(int schemaMaxTimeoutSeconds) { this.schemaMaxTimeoutSeconds = schemaMaxTimeoutSeconds; }
    }

    /**
     * Skill 搜索配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class Search {

        /** 默认搜索返回数量，默认 10。 */
        private int defaultTopK = 10;

        public int getDefaultTopK() { return defaultTopK; }
        public void setDefaultTopK(int defaultTopK) { this.defaultTopK = defaultTopK; }
    }

    /**
     * Skill 自扩展配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class AutoGeneration {

        /** 自扩展功能开关，默认 true。 */
        private boolean enabled = true;

        /** 缺口检测语义匹配阈值，低于此值判定存在缺口，默认 0.6。 */
        private double gapThreshold = 0.6;

        /** 自生成 Skill 的 maxCostCents 上限，默认 100。 */
        private int maxCostCents = 100;

        /** 验证失败后最大迭代修正次数，默认 2。 */
        private int maxValidationIterations = 2;

        public boolean isEnabled() { return enabled; }
        public void setEnabled(boolean enabled) { this.enabled = enabled; }

        public double getGapThreshold() { return gapThreshold; }
        public void setGapThreshold(double gapThreshold) { this.gapThreshold = gapThreshold; }

        public int getMaxCostCents() { return maxCostCents; }
        public void setMaxCostCents(int maxCostCents) { this.maxCostCents = maxCostCents; }

        public int getMaxValidationIterations() { return maxValidationIterations; }
        public void setMaxValidationIterations(int maxValidationIterations) { this.maxValidationIterations = maxValidationIterations; }
    }

    /**
     * Shell 动作执行配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class ShellAction {

        /** Shell 命令最大超时时间（秒），默认 30。 */
        private int maxTimeoutSeconds = 30;

        public int getMaxTimeoutSeconds() { return maxTimeoutSeconds; }
        public void setMaxTimeoutSeconds(int maxTimeoutSeconds) { this.maxTimeoutSeconds = maxTimeoutSeconds; }
    }

    /**
     * 技能串联动作配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class ChainAction {

        /** 串联步骤数上限，默认 5。 */
        private int maxSteps = 5;

        public int getMaxSteps() { return maxSteps; }
        public void setMaxSteps(int maxSteps) { this.maxSteps = maxSteps; }
    }

    /**
     * HTTP 动作执行配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class HttpAction {

        /** SSRF 防护开关，默认 true。 */
        private boolean ssrfProtectionEnabled = true;

        /** HTTP 请求超时时间（秒），默认 30。 */
        private int timeoutSeconds = 30;

        public boolean isSsrfProtectionEnabled() { return ssrfProtectionEnabled; }
        public void setSsrfProtectionEnabled(boolean ssrfProtectionEnabled) { this.ssrfProtectionEnabled = ssrfProtectionEnabled; }

        public int getTimeoutSeconds() { return timeoutSeconds; }
        public void setTimeoutSeconds(int timeoutSeconds) { this.timeoutSeconds = timeoutSeconds; }
    }

    /**
     * 内置 Skill 开关配置。
     *
     * <p>通过 {@code lifepilot.skills.builtin.{skill-id}.enabled} 控制各内置 Skill 的启用/禁用。
     * Memory Skill 始终启用，不受配置开关控制。</p>
     *
     * @author zsg
     * @since 2026-03-10
     */
    public static class Builtin {

        private SkillToggle todo = new SkillToggle();
        private SkillToggle schedule = new SkillToggle();
        private SkillToggle habit = new SkillToggle();

        public SkillToggle getTodo() { return todo; }
        public void setTodo(SkillToggle todo) { this.todo = todo; }

        public SkillToggle getSchedule() { return schedule; }
        public void setSchedule(SkillToggle schedule) { this.schedule = schedule; }

        public SkillToggle getHabit() { return habit; }
        public void setHabit(SkillToggle habit) { this.habit = habit; }

        /**
         * 根据 Skill ID 查询是否启用。Memory Skill 始终启用。
         *
         * @param skillId Skill 标识
         * @return 是否启用
         */
        public boolean isEnabled(String skillId) {
            return switch (skillId) {
                case "todo" -> todo.isEnabled();
                case "schedule" -> schedule.isEnabled();
                case "habit" -> habit.isEnabled();
                case "memory" -> true;
                default -> true;
            };
        }

        /**
         * 单个 Skill 的启用/禁用开关。
         *
         * @author zsg
         * @since 2026-03-10
         */
        public static class SkillToggle {

            /** 是否启用，默认 true。 */
            private boolean enabled = true;

            public boolean isEnabled() { return enabled; }
            public void setEnabled(boolean enabled) { this.enabled = enabled; }
        }
    }
}
