package com.lifepilot.skill.config;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Skill 系统配置属性。
 *
 * <p>绑定 {@code lifepilot.skills} 配置前缀。使用 JavaBean 风格以兼容 Spring Boot 配置绑定。</p>
 *
 * @author zsg
 * @since 2026-02-25
 */
@ConfigurationProperties(prefix = "lifepilot.skills")
public class SkillConfigProperties {

    /** Skill 系统总开关，默认 true。 */
    private boolean enabled = true;

    /** 最大并发激活数，默认 5。 */
    private int maxConcurrentActivations = 5;

    public boolean isEnabled() { return enabled; }
    public void setEnabled(boolean enabled) { this.enabled = enabled; }

    public int getMaxConcurrentActivations() { return maxConcurrentActivations; }
    public void setMaxConcurrentActivations(int maxConcurrentActivations) { this.maxConcurrentActivations = maxConcurrentActivations; }

    /** 校验限制配置。 */
    private Validation validation = new Validation();

    /** 搜索配置。 */
    private Search search = new Search();

    public Validation getValidation() { return validation; }
    public void setValidation(Validation validation) { this.validation = validation; }

    public Search getSearch() { return search; }
    public void setSearch(Search search) { this.search = search; }

    /**
     * Skill 定义校验限制配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class Validation {

        /** 名称最大长度，默认 128。 */
        private int maxNameLength = 128;

        /** System Prompt 最大长度，默认 10000。 */
        private int maxSystemPromptLength = 10000;

        /** AUTO_GENERATED 来源的 maxTokens 上限，默认 10000。 */
        private int autoGeneratedMaxTokens = 10000;

        /** AUTO_GENERATED 来源的 maxSteps 上限，默认 15。 */
        private int autoGeneratedMaxSteps = 15;

        /** AUTO_GENERATED 来源的 timeoutSeconds 上限，默认 180。 */
        private int autoGeneratedMaxTimeout = 180;

        public int getMaxNameLength() { return maxNameLength; }
        public void setMaxNameLength(int maxNameLength) { this.maxNameLength = maxNameLength; }

        public int getMaxSystemPromptLength() { return maxSystemPromptLength; }
        public void setMaxSystemPromptLength(int maxSystemPromptLength) { this.maxSystemPromptLength = maxSystemPromptLength; }

        public int getAutoGeneratedMaxTokens() { return autoGeneratedMaxTokens; }
        public void setAutoGeneratedMaxTokens(int autoGeneratedMaxTokens) { this.autoGeneratedMaxTokens = autoGeneratedMaxTokens; }

        public int getAutoGeneratedMaxSteps() { return autoGeneratedMaxSteps; }
        public void setAutoGeneratedMaxSteps(int autoGeneratedMaxSteps) { this.autoGeneratedMaxSteps = autoGeneratedMaxSteps; }

        public int getAutoGeneratedMaxTimeout() { return autoGeneratedMaxTimeout; }
        public void setAutoGeneratedMaxTimeout(int autoGeneratedMaxTimeout) { this.autoGeneratedMaxTimeout = autoGeneratedMaxTimeout; }
    }

    /**
     * Skill 搜索配置。
     *
     * @author zsg
     * @since 2026-02-25
     */
    public static class Search {

        /** 默认搜索返回数量，默认 10。 */
        private int defaultTopK = 10;

        public int getDefaultTopK() { return defaultTopK; }
        public void setDefaultTopK(int defaultTopK) { this.defaultTopK = defaultTopK; }
    }
}
