package com.lifepilot.skill.activation;

import com.lifepilot.skill.event.SkillLifecycleEvent;
import com.lifepilot.skill.model.SkillActivation;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.model.SkillSource;
import com.lifepilot.skill.registry.SkillRegistry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.lang.NonNull;

import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * {@link SkillActivator} 单元测试。
 *
 * <p>覆盖场景：激活成功（Builtin）、skillId 不存在、AutoGenerated 未确认拒绝、AutoGenerated 已确认可激活。</p>
 *
 * @author zsg
 * @since 2026-03-07
 */
class SkillActivatorTest {

    private StubSkillRegistry stubRegistry;
    private SkillMetricsTracker metricsTracker;
    private CapturingEventPublisher eventPublisher;
    private SkillActivator activator;

    @BeforeEach
    void setUp() {
        stubRegistry = new StubSkillRegistry();
        metricsTracker = new SkillMetricsTracker();
        eventPublisher = new CapturingEventPublisher();
        activator = new SkillActivator(stubRegistry, metricsTracker, eventPublisher);
    }

    // ── 激活成功 ──

    @Test
    void activate_Builtin来源_返回正确SkillActivation() {
        var definition = SkillDefinition.builder()
                .id("todo")
                .name("待办管理")
                .description("管理待办事项")
                .version("1.0.0")
                .source(new SkillSource.UserDefined("/test", null))
                .instructions("你是一个待办管理助手，帮助用户管理日常待办事项。")
                .suggestedTools(List.of("todo_add", "todo_list"))
                .metadata(Map.of("category", "productivity"))
                .build();
        stubRegistry.addSkill(definition);

        SkillActivation activation = activator.activate("todo");

        assertThat(activation.skillId()).isEqualTo("todo");
        assertThat(activation.instructions()).isEqualTo("你是一个待办管理助手，帮助用户管理日常待办事项。");
        assertThat(activation.suggestedTools()).containsExactly("todo_add", "todo_list");
    }

    @Test
    void activate_Builtin来源_记录激活指标() {
        var definition = builtinSkill("metrics-test");
        stubRegistry.addSkill(definition);

        activator.activate("metrics-test");

        assertThat(metricsTracker.getActivationCount("metrics-test")).isEqualTo(1);
        assertThat(metricsTracker.getMetrics("metrics-test")).isPresent();
        assertThat(metricsTracker.getMetrics("metrics-test").get().lastActivatedAt()).isNotNull();
    }

    @Test
    void activate_Builtin来源_发布Activated事件() {
        var definition = builtinSkill("event-test");
        stubRegistry.addSkill(definition);

        activator.activate("event-test");

        assertThat(eventPublisher.publishedEvents).hasSize(1);
        assertThat(eventPublisher.publishedEvents.getFirst()).isInstanceOf(SkillLifecycleEvent.Activated.class);
        var event = (SkillLifecycleEvent.Activated) eventPublisher.publishedEvents.getFirst();
        assertThat(event.skillId()).isEqualTo("event-test");
    }

    // ── skillId 不存在 ──

    @Test
    void activate_skillId不存在_抛出SkillActivationException() {
        assertThatThrownBy(() -> activator.activate("non-existent"))
                .isInstanceOf(SkillActivationException.class)
                .hasMessageContaining("Skill 不存在")
                .hasMessageContaining("non-existent");
    }

    // ── AutoGenerated 未确认拒绝 ──

    @Test
    void activate_AutoGenerated未确认_抛出SkillActivationException() {
        var definition = SkillDefinition.builder()
                .id("auto-gen-unconfirmed")
                .name("自动生成Skill")
                .description("未确认的自动生成Skill")
                .version("1.0.0")
                .source(new SkillSource.AutoGenerated("trace-001", Instant.now(), "用户请求", false))
                .instructions("自动生成的指令内容。")
                .suggestedTools(List.of())
                .metadata(Map.of())
                .build();
        stubRegistry.addSkill(definition);

        assertThatThrownBy(() -> activator.activate("auto-gen-unconfirmed"))
                .isInstanceOf(SkillActivationException.class)
                .hasMessageContaining("AutoGenerated Skill 未经用户确认")
                .hasMessageContaining("auto-gen-unconfirmed");
    }

    @Test
    void activate_AutoGenerated未确认_不记录指标也不发布事件() {
        var definition = SkillDefinition.builder()
                .id("auto-no-metrics")
                .name("自动生成Skill")
                .description("未确认")
                .version("1.0.0")
                .source(new SkillSource.AutoGenerated("trace-002", Instant.now(), null, false))
                .instructions("指令内容。")
                .suggestedTools(List.of())
                .metadata(Map.of())
                .build();
        stubRegistry.addSkill(definition);

        try {
            activator.activate("auto-no-metrics");
        } catch (SkillActivationException ignored) {
            // 预期异常
        }

        assertThat(metricsTracker.getActivationCount("auto-no-metrics")).isEqualTo(0);
        assertThat(eventPublisher.publishedEvents).isEmpty();
    }

    // ── AutoGenerated 已确认可激活 ──

    @Test
    void activate_AutoGenerated已确认_激活成功() {
        var definition = SkillDefinition.builder()
                .id("auto-gen-confirmed")
                .name("已确认自动生成Skill")
                .description("用户已确认的自动生成Skill")
                .version("1.0.0")
                .source(new SkillSource.AutoGenerated("trace-003", Instant.now(), "用户请求", true))
                .instructions("已确认的自动生成指令。")
                .suggestedTools(List.of("search"))
                .metadata(Map.of())
                .build();
        stubRegistry.addSkill(definition);

        SkillActivation activation = activator.activate("auto-gen-confirmed");

        assertThat(activation.skillId()).isEqualTo("auto-gen-confirmed");
        assertThat(activation.instructions()).isEqualTo("已确认的自动生成指令。");
        assertThat(activation.suggestedTools()).containsExactly("search");
        assertThat(metricsTracker.getActivationCount("auto-gen-confirmed")).isEqualTo(1);
        assertThat(eventPublisher.publishedEvents).hasSize(1);
    }

    // ── 辅助方法 ──

    private static SkillDefinition builtinSkill(String id) {
        return SkillDefinition.builder()
                .id(id)
                .name(id + "-name")
                .description(id + " 描述")
                .version("1.0.0")
                .source(new SkillSource.UserDefined("/test", null))
                .instructions(id + " 的指令内容。")
                .suggestedTools(List.of())
                .metadata(Map.of())
                .build();
    }

    // ── Stub / Capture 内部类 ──

    /**
     * 简易 SkillRegistry 桩 — 仅实现 find() 方法，绕过 SkillRegistry 的构造依赖。
     */
    private static class StubSkillRegistry extends SkillRegistry {

        private final Map<String, SkillDefinition> store = new java.util.concurrent.ConcurrentHashMap<>();

        StubSkillRegistry() {
            super(null, null, null, createDefaultConfig());
        }

        private static com.lifepilot.skill.config.SkillConfigProperties createDefaultConfig() {
            return new com.lifepilot.skill.config.SkillConfigProperties();
        }

        void addSkill(SkillDefinition definition) {
            store.put(definition.id(), definition);
        }

        @Override
        public Optional<SkillDefinition> find(String skillId) {
            return Optional.ofNullable(store.get(skillId));
        }
    }

    /**
     * 事件发布器捕获器 — 记录所有发布的事件。
     */
    private static class CapturingEventPublisher implements ApplicationEventPublisher {

        final List<Object> publishedEvents = new ArrayList<>();

        @Override
        public void publishEvent(@NonNull Object event) {
            publishedEvents.add(event);
        }
    }
}
