package com.lifepilot.skill.activation;

import com.lifepilot.agent.model.AgentPhase;
import com.lifepilot.agent.model.AgentState;
import com.lifepilot.agent.model.Budget;
import com.lifepilot.skill.action.ActionResult;
import com.lifepilot.skill.action.SkillAction;
import com.lifepilot.skill.action.SkillActionDispatcher;
import com.lifepilot.skill.event.SkillLifecycleEvent;
import com.lifepilot.skill.model.*;
import com.lifepilot.skill.registry.SkillRegistry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.context.ApplicationEventPublisher;

import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;

/**
 * SkillLifecycleManager 单元测试 — L1 回归后使用 SkillActionDispatcher。
 *
 * @author zsg
 * @since 2026-07-28
 */
@ExtendWith(MockitoExtension.class)
class SkillLifecycleManagerTest {

    @Mock
    private SkillRegistry skillRegistry;
    @Mock
    private SkillActionDispatcher actionDispatcher;
    @Mock
    private SkillMetricsTracker metricsTracker;
    @Mock
    private ApplicationEventPublisher eventPublisher;

    private SkillLifecycleManager lifecycleManager;

    @BeforeEach
    void setUp() {
        lifecycleManager = new SkillLifecycleManager(
                5, skillRegistry, actionDispatcher, metricsTracker, eventPublisher);
    }

    @Test
    void activate_成功执行返回SubAgentResult() {
        when(skillRegistry.find("todo")).thenReturn(Optional.of(createSkillDefinition("todo")));
        when(actionDispatcher.dispatch(any(SkillAction.TemplateAction.class), any(), any()))
                .thenReturn(ActionResult.success("待办已创建"));

        AgentState parentState = createParentState();
        SubAgentResult result = lifecycleManager.activate("todo", "创建待办", parentState);

        assertThat(result.success()).isTrue();
        assertThat(result.skillId()).isEqualTo("todo");
        assertThat(result.output()).isEqualTo("待办已创建");
    }

    @Test
    void activate_Skill不存在返回失败结果() {
        when(skillRegistry.find("non-existent")).thenReturn(Optional.empty());

        AgentState parentState = createParentState();
        SubAgentResult result = lifecycleManager.activate("non-existent", "测试", parentState);

        assertThat(result.success()).isFalse();
        assertThat(result.output()).contains("Skill 不存在");
        verifyNoInteractions(actionDispatcher);
    }

    @Test
    void activate_自生成Skill未确认返回失败结果() {
        SkillDefinition autoGenSkill = SkillDefinition.builder()
                .id("auto-skill")
                .name("自动生成")
                .description("测试")
                .version("1.0")
                .source(new SkillSource.AutoGenerated("auto-gen-trace", null, null, false))
                .systemPrompt("测试 Prompt")
                .allowedTools(List.of())
                .execution(ExecutionStrategy.DEFAULT)
                .memoryAccess(MemoryAccessPolicy.none())
                .budget(SkillBudget.DEFAULT)
                .metadata(Map.of())
                .build();
        when(skillRegistry.find("auto-skill")).thenReturn(Optional.of(autoGenSkill));

        AgentState parentState = createParentState();
        SubAgentResult result = lifecycleManager.activate("auto-skill", "测试", parentState);

        assertThat(result.success()).isFalse();
        assertThat(result.output()).contains("未经用户确认");
        verifyNoInteractions(actionDispatcher);
    }

    @Test
    void activate_并发超限返回失败结果() {
        SkillLifecycleManager zeroManager = new SkillLifecycleManager(
                0, skillRegistry, actionDispatcher, metricsTracker, eventPublisher);

        AgentState parentState = createParentState();
        SubAgentResult result = zeroManager.activate("todo", "超限", parentState);

        assertThat(result.success()).isFalse();
        assertThat(result.output()).contains("并发激活超限");
        verifyNoInteractions(skillRegistry);
    }

    @Test
    void activate_发布Activated和Deactivated事件() {
        when(skillRegistry.find("todo")).thenReturn(Optional.of(createSkillDefinition("todo")));
        when(actionDispatcher.dispatch(any(), any(), any()))
                .thenReturn(ActionResult.success("ok"));

        AgentState parentState = createParentState();
        lifecycleManager.activate("todo", "创建待办", parentState);

        ArgumentCaptor<Object> eventCaptor = ArgumentCaptor.forClass(Object.class);
        verify(eventPublisher, times(2)).publishEvent(eventCaptor.capture());

        List<Object> events = eventCaptor.getAllValues();
        assertThat(events.get(0)).isInstanceOf(SkillLifecycleEvent.Activated.class);
        assertThat(events.get(1)).isInstanceOf(SkillLifecycleEvent.Deactivated.class);

        SkillLifecycleEvent.Activated activated = (SkillLifecycleEvent.Activated) events.get(0);
        assertThat(activated.skillId()).isEqualTo("todo");
    }

    @Test
    void activate_记录指标() {
        when(skillRegistry.find("todo")).thenReturn(Optional.of(createSkillDefinition("todo")));
        when(actionDispatcher.dispatch(any(), any(), any()))
                .thenReturn(ActionResult.success("ok"));

        AgentState parentState = createParentState();
        lifecycleManager.activate("todo", "创建待办", parentState);

        verify(metricsTracker).record(eq("todo"), any(SubAgentResult.class));
    }

    @Test
    void activate_异常后仍递减活跃计数() {
        when(skillRegistry.find("error-skill")).thenReturn(Optional.of(createSkillDefinition("error-skill")));
        when(actionDispatcher.dispatch(any(), any(), any()))
                .thenThrow(new RuntimeException("测试异常"));

        AgentState parentState = createParentState();
        lifecycleManager.activate("error-skill", "测试", parentState);

        assertThat(lifecycleManager.getActiveCount()).isEqualTo(0);
    }

    @Test
    void activate_异常后仍记录指标和发布Deactivated事件() {
        when(skillRegistry.find("error-skill")).thenReturn(Optional.of(createSkillDefinition("error-skill")));
        when(actionDispatcher.dispatch(any(), any(), any()))
                .thenThrow(new RuntimeException("测试异常"));

        AgentState parentState = createParentState();
        lifecycleManager.activate("error-skill", "测试", parentState);

        verify(metricsTracker).record(eq("error-skill"), any(SubAgentResult.class));

        ArgumentCaptor<Object> eventCaptor = ArgumentCaptor.forClass(Object.class);
        verify(eventPublisher, times(2)).publishEvent(eventCaptor.capture());

        List<Object> events = eventCaptor.getAllValues();
        assertThat(events.get(0)).isInstanceOf(SkillLifecycleEvent.Activated.class);
        assertThat(events.get(1)).isInstanceOf(SkillLifecycleEvent.Deactivated.class);
    }

    @Test
    void activate_并发超限时不发布事件() {
        SkillLifecycleManager zeroManager = new SkillLifecycleManager(
                0, skillRegistry, actionDispatcher, metricsTracker, eventPublisher);

        AgentState parentState = createParentState();
        zeroManager.activate("todo", "超限", parentState);

        verify(eventPublisher, never()).publishEvent(any(SkillLifecycleEvent.class));
    }

    @Test
    void activate_traceId关联父Agent轨迹() {
        when(skillRegistry.find("todo")).thenReturn(Optional.of(createSkillDefinition("todo")));
        when(actionDispatcher.dispatch(any(), any(), any()))
                .thenReturn(ActionResult.success("ok"));

        AgentState parentState = createParentState();
        SubAgentResult result = lifecycleManager.activate("todo", "测试", parentState);

        assertThat(result.traceId()).startsWith("parent-trace/skill-todo-");
    }

    @Test
    void getActiveCount_初始为零() {
        assertThat(lifecycleManager.getActiveCount()).isEqualTo(0);
    }

    // ─────────────────────────────────────────────
    //  辅助方法
    // ─────────────────────────────────────────────

    private AgentState createParentState() {
        return AgentState.builder()
                .traceId("parent-trace")
                .sessionId("session-1")
                .goal("父目标")
                .phase(AgentPhase.UNDERSTANDING)
                .channel("cli")
                .steps(List.of())
                .stepCount(0)
                .plan(null)
                .planStepIndex(0)
                .revisionCount(0)
                .shortTermMemory(List.of())
                .mentionedEntities(List.of())
                .budget(Budget.defaultBudget())
                .parentTraceId(null)
                .depth(0)
                .done(false)
                .finalOutput(null)
                .terminationReason(null)
                .build();
    }

    private SkillDefinition createSkillDefinition(String id) {
        return SkillDefinition.builder()
                .id(id)
                .name(id + " Skill")
                .description("测试 Skill")
                .version("1.0")
                .source(new SkillSource.Builtin())
                .systemPrompt("你是 " + id + " 助手，输入: ${input}")
                .allowedTools(List.of())
                .execution(ExecutionStrategy.DEFAULT)
                .memoryAccess(MemoryAccessPolicy.none())
                .budget(SkillBudget.DEFAULT)
                .metadata(Map.of())
                .build();
    }
}
