<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { Bot, PencilLine, Puzzle, SlidersHorizontal, Store } from 'lucide-vue-next'
import { useSkillStore } from '@/stores/skill'
import { useUiStore } from '@/stores/ui'
import type { SkillSummary } from '@/types'
import SearchBar from '@/components/common/SearchBar.vue'
import FilterChips from '@/components/common/FilterChips.vue'
import ConfirmDialog from '@/components/common/ConfirmDialog.vue'
import StatePanel from '@/components/common/StatePanel.vue'
import PageContainer from '@/components/layout/PageContainer.vue'
import PageHeader from '@/components/layout/PageHeader.vue'
import PageSection from '@/components/layout/PageSection.vue'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import FormSheetShell from '@/components/common/FormSheetShell.vue'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Skeleton } from '@/components/ui/skeleton'
import { Textarea } from '@/components/ui/textarea'

const router = useRouter()
const store = useSkillStore()
const uiStore = useUiStore()

const showCreateDialog = ref(false)
const showFilters = ref(false)
const deleteTarget = ref<SkillSummary | null>(null)
const skillSearchQuery = ref('')
const skillSourceFilter = ref<'all' | 'Builtin' | 'UserDefined' | 'AutoGenerated' | 'Marketplace'>('all')

const newSkill = ref({
  name: '',
  description: '',
})

const skillSourceOptions = [
  { value: 'all', label: '全部' },
  { value: 'Builtin', label: '内置' },
  { value: 'UserDefined', label: '自定义' },
  { value: 'AutoGenerated', label: '自动生成' },
  { value: 'Marketplace', label: '市场' },
]

const sourceLabel: Record<string, string> = {
  Builtin: '内置',
  UserDefined: '自定义',
  AutoGenerated: '自动生成',
  Marketplace: '市场',
}

const filteredSkills = computed(() => {
  let result = store.skills

  if (skillSearchQuery.value.trim()) {
    const keyword = skillSearchQuery.value.trim().toLowerCase()
    result = result.filter(skill =>
      skill.name.toLowerCase().includes(keyword)
      || (skill.description ?? '').toLowerCase().includes(keyword),
    )
  }

  if (skillSourceFilter.value !== 'all') {
    result = result.filter(skill => skill.source?.type === skillSourceFilter.value)
  }

  return result
})

const enabledSkillCount = computed(() => store.skills.filter(skill => skill.metadata?.status !== 'disabled').length)
const customSkillCount = computed(() => store.skills.filter(skill => skill.source?.type === 'UserDefined').length)
const marketplaceSkillCount = computed(() => store.skills.filter(skill => skill.source?.type === 'Marketplace').length)
const hasFilters = computed(() => Boolean(skillSearchQuery.value.trim()) || skillSourceFilter.value !== 'all')
const skillSourceFilterLabel = computed(() => skillSourceOptions.find(option => option.value === skillSourceFilter.value)?.label || '全部')

const showDeleteConfirm = computed({
  get: () => deleteTarget.value !== null,
  set: (value: boolean) => {
    if (!value) {
      deleteTarget.value = null
    }
  },
})

function showErrorToast(message: string) {
  uiStore.showToast('error', message)
}

function isEnabled(skill: SkillSummary) {
  return skill.metadata?.status !== 'disabled'
}

function clearFilters() {
  skillSearchQuery.value = ''
  skillSourceFilter.value = 'all'
}

async function viewSkillDetail(skill: SkillSummary) {
  await router.push(`/skills/${skill.id}`)
}

async function handleCreate() {
  if (!newSkill.value.name.trim()) {
    showErrorToast('请先填写技能名称。')
    return
  }

  try {
    const skill = await store.createSkill(newSkill.value)
    showCreateDialog.value = false
    newSkill.value = { name: '', description: '' }
    await router.push(`/skills/${skill.id}`)
  } catch (error: any) {
    showErrorToast(error?.message || '创建技能失败。')
  }
}

async function confirmUnregister() {
  if (!deleteTarget.value) return

  try {
    await store.unregisterSkill(deleteTarget.value.id)
    deleteTarget.value = null
  } catch (error: any) {
    showErrorToast(error?.message || '删除技能失败。')
  }
}

async function toggleSkill(skill: SkillSummary, event: Event) {
  event.stopPropagation()

  try {
    if (isEnabled(skill)) {
      await store.disableSkill(skill.id)
    } else {
      await store.enableSkill(skill.id)
    }
  } catch (error: any) {
    showErrorToast(error?.message || '更新技能状态失败。')
  }
}

onMounted(() => {
  void store.fetchSkills()
})
</script>

<template>
  <div class="h-full overflow-y-auto">
    <PageContainer size="wide" class="py-4 sm:py-5">
      <div class="page-stack">
        <PageHeader
          eyebrow="技能"
          title="技能目录"
          :description="`${enabledSkillCount} 个启用中，共 ${store.skills.length} 个`"
        >
          <template #actions>
            <Button @click="showCreateDialog = true">
              <PencilLine class="size-4" />
              新建技能
            </Button>
          </template>
        </PageHeader>

        <section class="toolbar-strip">
          <div class="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
            <div class="flex flex-1 items-center gap-3">
              <SearchBar
                v-model="skillSearchQuery"
                placeholder="按技能名称或说明搜索..."
                class="flex-1"
              />
              <Button variant="outline" size="sm" @click="showFilters = !showFilters">
                <SlidersHorizontal class="size-4" />
                筛选
              </Button>
            </div>

            <div class="flex items-center gap-3">
              <span class="text-sm text-muted-foreground">结果 {{ filteredSkills.length }}</span>
              <Button v-if="hasFilters" variant="ghost" @click="clearFilters">
                清空筛选
              </Button>
            </div>
          </div>

          <div v-if="showFilters" class="mt-sm rounded-xl border border-border/40 bg-card/60 p-md">
            <div class="flex flex-wrap items-center gap-3">
              <span class="surface-label text-[0.68rem]">来源</span>
              <FilterChips v-model="skillSourceFilter" :options="skillSourceOptions" />
            </div>
          </div>
        </section>

        <PageSection
          eyebrow="目录"
          title="已注册技能"
          :description="`当前显示 ${filteredSkills.length} / ${store.skills.length} 个已注册技能。`"
        >
          <div v-if="store.loading" class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
            <div
              v-for="index in 6"
              :key="index"
              class="rounded-[calc(var(--radius)+6px)] border border-border/70 bg-background/72 p-5"
            >
              <div class="space-y-3">
                <div class="flex items-center gap-2">
                  <Skeleton class="h-5 w-28" />
                  <Skeleton class="h-5 w-20 rounded-full" />
                </div>
                <Skeleton class="h-3 w-full" />
                <Skeleton class="h-3 w-2/3" />
                <div class="grid gap-3 sm:grid-cols-2">
                  <Skeleton class="h-16 rounded-[calc(var(--radius)+4px)]" />
                  <Skeleton class="h-16 rounded-[calc(var(--radius)+4px)]" />
                </div>
              </div>
            </div>
          </div>

          <StatePanel
            v-else-if="store.error"
            title="技能目录暂时不可用"
            :description="store.error"
            tone="danger"
          >
            <template #icon>
              <Puzzle class="size-5" />
            </template>
          </StatePanel>

          <StatePanel
            v-else-if="store.skills.length === 0"
            title="暂无已注册技能"
            description="可以先创建第一个自定义技能，或从市场安装可复用能力。"
          >
            <template #icon>
              <Puzzle class="size-5" />
            </template>
            <template #actions>
              <Button @click="showCreateDialog = true">
                创建技能
              </Button>
            </template>
          </StatePanel>

          <StatePanel
            v-else-if="filteredSkills.length === 0"
            title="没有匹配当前筛选条件的技能"
            description="可以放宽来源筛选，或清空搜索关键词后重试。"
          >
            <template #icon>
              <Store class="size-5" />
            </template>
            <template #actions>
              <Button variant="outline" @click="clearFilters">
                清空筛选
              </Button>
            </template>
          </StatePanel>

          <div v-else class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
            <article
              v-for="skill in filteredSkills"
              :key="skill.id"
              class="list-card group cursor-pointer p-4"
              @click="viewSkillDetail(skill)"
            >
              <div class="flex items-start justify-between gap-3">
                <div class="min-w-0 space-y-2">
                  <div class="flex flex-wrap items-center gap-2">
                    <h3 class="truncate text-base font-semibold tracking-tight text-foreground">
                      {{ skill.name }}
                    </h3>
                    <Badge variant="outline">
                      {{ sourceLabel[skill.source?.type] ?? skill.source?.type }}
                    </Badge>
                    <Badge
                      variant="outline"
                      :class="isEnabled(skill)
                        ? 'border-emerald-200/80 bg-emerald-50/80 text-emerald-700 dark:border-emerald-500/20 dark:bg-emerald-500/10 dark:text-emerald-200'
                        : 'border-slate-200/80 bg-slate-50/80 text-slate-700 dark:border-slate-500/20 dark:bg-slate-500/10 dark:text-slate-200'"
                    >
                      {{ isEnabled(skill) ? '已启用' : '已停用' }}
                    </Badge>
                  </div>
                  <p class="line-clamp-3 text-sm leading-6 text-muted-foreground">
                    {{ skill.description || '这个技能暂时还没有说明。' }}
                  </p>
                </div>
                <span class="text-xs text-muted-foreground">
                  v{{ skill.version }}
                </span>
              </div>

              <div class="mt-4 flex flex-wrap gap-2 text-xs text-muted-foreground">
                <span class="surface-chip">来源：{{ sourceLabel[skill.source?.type] ?? skill.source?.type }}</span>
                <span class="surface-chip">{{ skill.source?.type === 'UserDefined' ? '可编辑' : '受管来源' }}</span>
                <span class="surface-chip">版本 v{{ skill.version }}</span>
              </div>

              <div class="mt-4 flex items-center justify-between gap-3 border-t border-border/60 pt-4">
                <div class="min-w-0 text-xs text-muted-foreground">
                  <span class="truncate">技能 ID · </span>
                  <span class="font-mono">{{ skill.id }}</span>
                </div>

                <div class="flex items-center gap-2" @click.stop>
                  <Button
                    variant="ghost"
                    size="sm"
                    @click="viewSkillDetail(skill)"
                  >
                    查看详情
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    @click="toggleSkill(skill, $event)"
                  >
                    {{ isEnabled(skill) ? '停用' : '启用' }}
                  </Button>
                  <Button
                    v-if="skill.source?.type === 'UserDefined'"
                    variant="destructive"
                    size="sm"
                    @click="deleteTarget = skill"
                  >
                    删除
                  </Button>
                </div>
              </div>
            </article>
          </div>
        </PageSection>
      </div>
    </PageContainer>

    <FormSheetShell
      :open="showCreateDialog"
      title="新建技能"
      description="先填写名称和简短说明。创建后，可在详情页继续进行更深入的编辑。"
      @update:open="value => showCreateDialog = value"
      @close="showCreateDialog = false"
    >
      <div class="space-y-4">
        <div class="space-y-2">
          <Label for="skill-name">名称</Label>
          <Input id="skill-name" v-model="newSkill.name" placeholder="例如：研究助手" />
        </div>
        <div class="space-y-2">
          <Label for="skill-description">说明</Label>
          <Textarea
            id="skill-description"
            v-model="newSkill.description"
            rows="4"
            placeholder="这个技能主要帮助用户完成什么任务？"
          />
        </div>
      </div>

      <template #footer>
        <div class="flex items-center justify-end gap-2">
          <Button variant="outline" @click="showCreateDialog = false">
            取消
          </Button>
          <Button @click="handleCreate">
            创建技能
          </Button>
        </div>
      </template>
    </FormSheetShell>

    <ConfirmDialog
      v-if="deleteTarget"
      :show="showDeleteConfirm"
      title="删除技能"
      :message="`确定删除 ${deleteTarget.name} 吗？此操作不可恢复。`"
      confirm-label="删除"
      confirm-variant="destructive"
      @confirm="confirmUnregister"
      @cancel="deleteTarget = null"
      @update:show="showDeleteConfirm = $event"
    />
  </div>
</template>
