<script setup lang="ts">
import { computed, defineAsyncComponent, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import {
  ArrowLeft,
  Blocks,
  Bot,
  FileText,
  Puzzle,
  TestTube2,
  Wrench,
} from 'lucide-vue-next'
import { skillApi } from '@/api/client'
import MetricCard from '@/components/common/MetricCard.vue'
import StatePanel from '@/components/common/StatePanel.vue'
import Breadcrumb from '@/components/global/Breadcrumb.vue'
import type { BreadcrumbItem } from '@/components/global/Breadcrumb.vue'
import PageContainer from '@/components/layout/PageContainer.vue'
import PageHeader from '@/components/layout/PageHeader.vue'
import PageSection from '@/components/layout/PageSection.vue'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Skeleton } from '@/components/ui/skeleton'
import { Textarea } from '@/components/ui/textarea'
import { useSkillStore } from '@/stores/skill'
import { useToolStore } from '@/stores/tool'
import { useUiStore } from '@/stores/ui'

const MarkdownEditor = defineAsyncComponent(() => import('@/components/editor/MarkdownEditor.vue'))

const route = useRoute()
const router = useRouter()
const skillStore = useSkillStore()
const toolStore = useToolStore()
const uiStore = useUiStore()

const skillId = computed(() => route.params.id as string)
const skill = computed(() => skillStore.currentSkill)

const pageLoading = ref(true)
const pageError = ref<string | null>(null)
const editingBasic = ref(false)
const markdownLoading = ref(false)
const markdownContent = ref('')
const basicInfo = ref({
  name: '',
  description: '',
})

const breadcrumbItems = computed<BreadcrumbItem[]>(() => [
  { label: '技能', to: { name: 'skills' } },
  { label: skill.value?.name ?? '详情' },
])

const sourceLabel: Record<string, string> = {
  Builtin: '内置',
  UserDefined: '自定义',
  AutoGenerated: '自动生成',
  Marketplace: '市场',
}

const riskBadge: Record<string, { label: string; variant: 'default' | 'secondary' | 'outline' | 'destructive'; class: string }> = {
  LOW: {
    label: '低风险',
    variant: 'secondary',
    class: 'status-btn-inactive',
  },
  MEDIUM: {
    label: '中风险',
    variant: 'outline',
    class: 'border-amber-200/70 bg-amber-50 text-amber-800 dark:border-amber-500/20 dark:bg-amber-500/10 dark:text-amber-300',
  },
  HIGH: {
    label: '高风险',
    variant: 'destructive',
    class: 'border-destructive/25 bg-destructive/8 text-destructive',
  },
}

const toolSourceLabel: Record<string, string> = {
  PLUGIN: '插件',
  SKILL: '技能',
  MCP: 'MCP',
  builtin: '内置',
  mcp: 'MCP',
}

interface ToolCardInfo {
  id: string
  name: string
  description: string
  riskLevel: string
  source: string
  registered: boolean
}

const isEnabled = computed(() => skill.value?.metadata?.status !== 'disabled')
const sourceValue = computed(() => sourceLabel[skill.value?.source?.type || ''] ?? skill.value?.source?.type ?? '未知')
const editableMarkdown = computed(() => skill.value?.source?.type === 'UserDefined')

const toolCards = computed<ToolCardInfo[]>(() => {
  if (!skill.value) return []

  return (skill.value.suggestedTools ?? []).map(toolId => {
    const found = toolStore.tools.find(tool => tool.id === toolId)
    if (found) {
      return {
        id: toolId,
        name: found.displayName || found.name,
        description: found.description || '',
        riskLevel: found.riskLevel || 'LOW',
        source: found.source || found.type || 'unknown',
        registered: true,
      }
    }

    return {
      id: toolId,
      name: toolId,
      description: '该工具已被当前技能引用，但尚未注册到当前目录中。',
      riskLevel: '',
      source: '',
      registered: false,
    }
  })
})

onMounted(async () => {
  await loadData()
})

watch(() => route.params.id, async () => {
  editingBasic.value = false
  await loadData()
})

watch(() => skill.value, newSkill => {
  if (!newSkill) return
  initFormData()
})

async function loadData() {
  pageLoading.value = true
  pageError.value = null
  markdownContent.value = ''

  try {
    await toolStore.fetchTools()
    await skillStore.fetchSkillDetail(skillId.value)

    if (skill.value) {
      initFormData()
      await loadMarkdown()
    }
  } catch (event: any) {
    pageError.value = event?.message || skillStore.error || '加载技能详情失败。'
  } finally {
    pageLoading.value = false
  }
}

function initFormData() {
  if (!skill.value) return

  basicInfo.value = {
    name: skill.value.name,
    description: skill.value.description || '',
  }
}

async function loadMarkdown() {
  markdownLoading.value = true
  try {
    markdownContent.value = await skillApi.getSkillMarkdown(skillId.value)
  } catch {
    markdownContent.value = ''
  } finally {
    markdownLoading.value = false
  }
}

async function saveBasicInfo() {
  if (!skill.value) return

  try {
    await skillStore.updateSkill(skill.value.id, {
      name: basicInfo.value.name,
      description: basicInfo.value.description,
    })
    editingBasic.value = false
    initFormData()
    uiStore.showToast('success', '技能信息已更新。')
  } catch (event: any) {
    uiStore.showToast('error', event?.message || '保存技能信息失败。')
  }
}

async function toggleSkill() {
  if (!skill.value) return

  try {
    if (isEnabled.value) {
      await skillStore.disableSkill(skill.value.id)
      uiStore.showToast('success', '技能已停用。')
    } else {
      await skillStore.enableSkill(skill.value.id)
      uiStore.showToast('success', '技能已启用。')
    }
  } catch (event: any) {
    uiStore.showToast('error', event?.message || '更新技能状态失败。')
  }
}

function openTool(toolId: string) {
  router.push(`/tools/${toolId}`)
}

function runTest() {
  uiStore.showToast('info', '当前还不支持直接测试技能，请通过智能体对话来验证该技能。')
}
</script>

<template>
  <div class="h-full overflow-y-auto">
    <PageContainer size="wide" class="py-4 sm:py-5">
      <div class="page-stack">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <Breadcrumb :items="breadcrumbItems" class="min-w-0" />
          <Button type="button" variant="ghost" class="w-fit" @click="router.push('/skills')">
            <ArrowLeft class="size-4" />
            返回技能列表
          </Button>
        </div>

        <template v-if="pageLoading">
          <div class="space-y-5">
            <div class="space-y-3 border-b border-border/70 pb-6">
              <Skeleton class="h-5 w-20" />
              <Skeleton class="h-10 w-72" />
              <Skeleton class="h-5 w-full max-w-[42rem]" />
            </div>
            <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
              <Skeleton v-for="index in 4" :key="index" class="h-24 rounded-[calc(var(--radius)+6px)]" />
            </div>
            <div class="grid gap-4 xl:grid-cols-2">
              <Skeleton class="h-[280px] rounded-[calc(var(--radius)+6px)]" />
              <Skeleton class="h-[280px] rounded-[calc(var(--radius)+6px)]" />
            </div>
            <Skeleton class="h-[340px] rounded-[calc(var(--radius)+6px)]" />
          </div>
        </template>

        <StatePanel
          v-else-if="pageError || !skill"
          title="技能详情暂时不可用"
          :description="pageError || skillStore.error || '未找到对应的技能。'"
          tone="danger"
        >
          <template #icon>
            <Puzzle class="size-5" />
          </template>
          <template #actions>
            <Button type="button" variant="outline" @click="router.push('/skills')">
              返回列表
            </Button>
            <Button type="button" @click="loadData">
              重试
            </Button>
          </template>
        </StatePanel>

        <template v-else>
          <PageHeader
            eyebrow="技能详情"
            :title="skill.name"
            :description="skill.description || '查看技能详情和依赖工具。'"
          >
            <template #actions>
              <Button
                v-if="skill.source?.type !== 'Builtin'"
                type="button"
                variant="outline"
                @click="editingBasic = true"
              >
                编辑基本信息
              </Button>
              <Button :variant="isEnabled ? 'destructive' : 'outline'" @click="toggleSkill">
                {{ isEnabled ? '停用技能' : '启用技能' }}
              </Button>
            </template>

            <template #meta>
              <MetricCard label="来源" :value="sourceValue" hint="技能归属">
                <template #icon>
                  <Puzzle class="size-5" />
                </template>
              </MetricCard>
              <MetricCard label="版本" :value="`v${skill.version}`" hint="版本号">
                <template #icon>
                  <FileText class="size-5" />
                </template>
              </MetricCard>
              <MetricCard label="关联工具" :value="toolCards.length" hint="依赖工具">
                <template #icon>
                  <Wrench class="size-5" />
                </template>
              </MetricCard>
              <MetricCard label="定义状态" :value="editableMarkdown ? '可编辑' : '只读'" hint="编辑权限">
                <template #icon>
                  <Blocks class="size-5" />
                </template>
              </MetricCard>
            </template>
          </PageHeader>

          <div class="grid gap-4 xl:grid-cols-2">
            <PageSection
              eyebrow="基础信息"
              title="名称与说明"
              description="查看或编辑技能名称和说明。"
            >
              <div v-if="editingBasic" class="space-y-4">
                <div class="space-y-2">
                  <Label>名称</Label>
                  <Input v-model="basicInfo.name" />
                </div>
                <div class="space-y-2">
                  <Label>说明</Label>
                  <Textarea v-model="basicInfo.description" :rows="4" class="resize-none" />
                </div>
                <div class="flex justify-end gap-3">
                  <Button variant="outline" @click="editingBasic = false; initFormData()">
                    取消
                  </Button>
                  <Button @click="saveBasicInfo">
                    保存
                  </Button>
                </div>
              </div>

              <div v-else class="grid gap-4 lg:grid-cols-[minmax(0,1.15fr)_minmax(240px,0.85fr)]">
                <div class="detail-card p-4 sm:p-5">
                  <div class="space-y-4">
                    <div>
                      <div class="surface-label mb-2 text-[0.68rem]">名称</div>
                      <p class="text-sm text-foreground">{{ skill.name }}</p>
                    </div>
                    <div class="border-t border-border/60 pt-4">
                      <div class="surface-label mb-2 text-[0.68rem]">说明</div>
                      <p class="text-sm leading-6 text-muted-foreground">
                        {{ skill.description || '暂无说明。' }}
                      </p>
                    </div>
                  </div>
                </div>
                <div class="rounded-[calc(var(--radius)+2px)] border border-dashed border-border/60 bg-background/48 p-4">
                  <div class="space-y-4">
                    <div>
                      <div class="surface-label text-[0.68rem]">当前对象</div>
                      <p class="mt-2 break-all font-mono text-sm text-muted-foreground">{{ skill.id }}</p>
                    </div>
                    <div class="flex flex-wrap gap-2 text-xs text-muted-foreground">
                      <span class="surface-chip">{{ isEnabled ? '已启用' : '已停用' }}</span>
                      <span class="surface-chip">来源：{{ sourceValue }}</span>
                      <span class="surface-chip">版本 v{{ skill.version }}</span>
                    </div>
                    <p class="text-sm leading-6 text-muted-foreground">
                      查看来源、启用状态和定义文件。
                    </p>
                  </div>
                </div>
              </div>
            </PageSection>

            <PageSection
              eyebrow="详细设置"
              title="提示词与使用范围"
              description="查看技能提示词和适用范围。"
            >
              <div class="space-y-4">
                <div class="detail-card p-4">
                  <div class="surface-label mb-2 text-[0.68rem]">提示词</div>
                  <pre class="whitespace-pre-wrap break-words text-sm leading-7 text-foreground">{{ skill.instructions }}</pre>
                </div>
                <div class="flex flex-wrap gap-2 text-xs text-muted-foreground">
                  <span class="surface-chip">提示词长度 {{ skill.instructions.length }}</span>
                  <span class="surface-chip">测试方式：挂载到智能体后验证</span>
                </div>
              </div>
            </PageSection>
          </div>

            <PageSection
              eyebrow="依赖"
              :title="`工具关系（${toolCards.length}）`"
              description="查看技能依赖的工具。"
            >
            <StatePanel
              v-if="toolCards.length === 0"
              title="暂无工具依赖"
              description="当前技能定义里没有声明建议工具。"
            >
              <template #icon>
                <Blocks class="size-5" />
              </template>
            </StatePanel>

            <div v-else class="space-y-3">
              <article
                v-for="toolCard in toolCards"
                :key="toolCard.id"
                class="list-card p-4"
                :class="toolCard.registered ? '' : 'border-dashed opacity-75'"
              >
                <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                  <div class="space-y-2">
                    <div class="flex flex-wrap items-center gap-2">
                      <div class="text-sm font-medium text-foreground">{{ toolCard.name }}</div>
                      <Badge v-if="toolCard.source" variant="outline">
                        {{ toolSourceLabel[toolCard.source] ?? toolCard.source }}
                      </Badge>
                      <Badge
                        v-if="toolCard.riskLevel"
                        :variant="riskBadge[toolCard.riskLevel]?.variant ?? 'outline'"
                        :class="riskBadge[toolCard.riskLevel]?.class"
                      >
                        {{ riskBadge[toolCard.riskLevel]?.label ?? toolCard.riskLevel }}
                      </Badge>
                      <Badge v-if="!toolCard.registered" variant="destructive">
                        缺失
                      </Badge>
                    </div>
                    <p class="text-sm leading-6 text-muted-foreground">
                      {{ toolCard.description || '该工具关系暂时没有说明。' }}
                    </p>
                  </div>

                  <Button
                    v-if="toolCard.registered"
                    type="button"
                    variant="outline"
                    @click="openTool(toolCard.id)"
                  >
                    打开工具
                  </Button>
                </div>
              </article>
            </div>
          </PageSection>

          <PageSection
            eyebrow="定义文件"
            title="SKILL.md"
            description="自定义技能可直接编辑，其他来源保持只读。"
          >
            <Skeleton v-if="markdownLoading" class="h-72 w-full rounded-[calc(var(--radius)+6px)]" />
            <MarkdownEditor
              v-else
              v-model="markdownContent"
              :readonly="!editableMarkdown"
              title="SKILL.md"
              :on-save="(content: string) => skillApi.updateSkillMarkdown(skillId, content)"
            />
          </PageSection>

          <PageSection
            eyebrow="验证"
            title="测试方式"
            description="挂载到智能体进行测试。"
          >
            <div class="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(280px,0.9fr)]">
              <div class="rounded-[calc(var(--radius)+6px)] border border-border/70 bg-background/72 p-4">
                <div class="surface-label mb-3 text-[0.68rem]">当前建议</div>
                <ul class="space-y-2 text-sm leading-6 text-muted-foreground">
                  <li class="flex items-start gap-2">
                    <span class="mt-2 size-1.5 rounded-full bg-primary/70" />
                    <span>将技能挂载到智能体，通过对话测试。</span>
                  </li>
                  <li class="flex items-start gap-2">
                    <span class="mt-2 size-1.5 rounded-full bg-primary/70" />
                    <span>如果依赖工具缺失，优先补齐工具注册，再进行测试。</span>
                  </li>
                </ul>
                <Button class="mt-4 w-full sm:w-auto" @click="runTest">
                  <TestTube2 class="size-4" />
                  查看提示
                </Button>
              </div>

              <StatePanel
                title="请通过智能体验证"
                description="将技能挂载到智能体后，通过对话测试效果。"
                tone="warning"
              >
                <template #icon>
                  <Bot class="size-5" />
                </template>
              </StatePanel>
            </div>
          </PageSection>
        </template>
      </div>
    </PageContainer>
  </div>
</template>
