// LifePilot 前端类型定义

/** 会话摘要 */
export interface ChatSession {
  id: string
  title: string
  createdAt: string   // ISO 8601
  updatedAt: string
}

/** 消息 */
export interface Message {
  id: string
  role: 'user' | 'assistant'
  content: string
  a2uiComponents?: A2uiComponent[]
  timestamp: number
  /** 前端侧的发送 / 处理状态标记，用于展示“发送中 / 失败 / 可重试” */
  status?: 'pending' | 'success' | 'error'
  /** 与本条消息相关的错误说明（仅在 status === 'error' 时展示） */
  errorMessage?: string
  /** 后端执行轨迹 ID（如存在），用于跳转到 Trace 详情 */
  traceId?: string
}

/** A2UI 组件节点（邻接表） */
export interface A2uiComponent {
  id: string
  type: string
  properties: Record<string, unknown>
  children: string[]
  signal?: A2uiSignal
}

/** A2UI 信号 */
export interface A2uiSignal {
  name: string
  payload: Record<string, unknown>
}

/** Token 消耗统计 */
export interface TokenUsage {
  promptTokens: number
  completionTokens: number
  totalTokens: number
  modelId: string
}

/** 用户设置 */
export interface UserSettings {
  theme: 'light' | 'dark' | 'system'
  language: string
  llmProvider: string
}

/** SSE token 事件 */
export interface SseTokenEvent {
  content: string
  index: number
}

/** SSE 完成事件 */
export interface SseDoneEvent {
  messageId: string
  tokenUsage: TokenUsage
  /** 可选：本轮执行对应的 Trace Id（如后端有返回） */
  traceId?: string
}

/** SSE 错误事件 */
export interface SseErrorEvent {
  code: number
  message: string
  /** 可选：错误对应的 Trace Id，便于前端跳转调试 */
  traceId?: string
}

/** 非流式聊天响应 */
export interface ChatResponse {
  messageId: string
  content: string
  a2ui?: { components: A2uiComponent[] }
  tokenUsage?: TokenUsage
  /** 本轮对话中使用到的知识库 / 文档来源等（由后端返回，前端只做轻量展示） */
  sources?: Array<{
    type: 'knowledgeBase' | 'document' | 'tool' | 'workflow'
    id: string
    name: string
    extra?: Record<string, unknown>
  }>
}

/** 统一错误响应 */
export interface ErrorResponse {
  code: number
  message: string
  timestamp: string
}

// ========== 模块 19: Web UI 功能页面类型 ==========

/** 知识库 */
export interface KnowledgeBase {
  id: string
  name: string
  description: string
  embeddingModel: string
  documentCount: number
  totalChunks: number
  createdAt: string
  updatedAt: string
}

/** 创建知识库请求 */
export interface CreateKbRequest {
  name: string
  description: string
  embeddingModel?: string
}

/** 知识库文档 */
export interface KbDocument {
  id: string
  knowledgeBaseId: string
  fileName: string
  fileSize: number
  mimeType: string
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'ERROR'
  chunkCount: number
  errorMessage?: string
  createdAt: string
  updatedAt: string
}

/** Skill 摘要 */
export interface SkillSummary {
  id: string
  name: string
  description: string
  version: string
  sourceType: 'Builtin' | 'UserDefined' | 'AutoGenerated'
}

/** Skill 详情 */
export interface SkillDetail extends SkillSummary {
  systemPrompt: string
  allowedTools: string[]
  metadata: Record<string, string>
  preferredProviderId?: string
}

/** MCP Server */
export interface McpServer {
  name: string
  state: 'DISCONNECTED' | 'CONNECTING' | 'CONNECTED' | 'RECONNECTING'
  toolCount: number
  connectedSince?: string
  lastError?: string
}

/** MCP 工具 */
export interface McpTool {
  id: string
  name: string
  description: string
}

/** 轨迹列表项 */
export interface TraceItem {
  id: string
  sessionId: string
  userMessage: string
  success: boolean
  totalSteps: number
  totalTokens: number
  durationMs: number
  createdAt: string
}

/** 轨迹详情 */
export interface TraceDetail extends TraceItem {
  finalOutput?: string
  errorMessage?: string
  terminationReason?: string
  modelId?: string
}

/** 轨迹步骤 */
export interface TraceStep {
  id: string
  stepIndex: number
  phaseBefore: string
  phaseAfter: string
  actionType: string
  actionJson?: string
  toolId?: string
  toolInputJson?: string
  toolOutput?: string
  success: boolean
  blocked: boolean
  blockReason?: string
  tokensUsed: number
  latencyMs: number
  createdAt: string
}

/** 分页结果 */
export interface PageResult<T> {
  items: T[]
  page: number
  size: number
  total: number
}

/** 工作流列表项 */
export interface WorkflowItem {
  id: string
  name: string
  description: string
  enabled: boolean
  triggerTypes: string[]
  version: string
}

/** 工作流详情 */
export interface WorkflowDetail extends WorkflowItem {
  triggers: unknown[]
  inputs: Record<string, unknown>
  steps: unknown[]
  metadata: Record<string, string>
}

/** 工作流执行记录 */
export interface WorkflowExecution {
  id: string
  workflowId: string
  state: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED'
  currentStepIndex: number
  startedAt?: string
  completedAt?: string
  failureReason?: string
  createdAt: string
}
