package com.lifepilot.skill.activation;

import com.lifepilot.skill.event.SkillLifecycleEvent;
import com.lifepilot.skill.model.SkillActivation;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.model.SkillSource;
import com.lifepilot.skill.registry.SkillRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationEventPublisher;

import java.util.UUID;

/**
 * Skill 激活器 — 将 Skill 从注册表中激活为上下文注入包。
 *
 * <p>激活流程：
 * <ol>
 *   <li>从 {@link SkillRegistry} 查找 Skill 定义</li>
 *   <li>检查激活条件（AutoGenerated 未确认则拒绝）</li>
 *   <li>通过 {@link SkillMetricsTracker} 记录激活指标</li>
 *   <li>发布 {@link SkillLifecycleEvent.Activated} 事件</li>
 *   <li>返回 {@link SkillActivation} 供 ContextAssembler 注入上下文</li>
 * </ol>
 *
 * @author zsg
 * @since 2026-03-07
 */
public class SkillActivator {

    private static final Logger log = LoggerFactory.getLogger(SkillActivator.class);

    private final SkillRegistry skillRegistry;
    private final SkillMetricsTracker metricsTracker;
    private final ApplicationEventPublisher eventPublisher;

    public SkillActivator(SkillRegistry skillRegistry,
                          SkillMetricsTracker metricsTracker,
                          ApplicationEventPublisher eventPublisher) {
        this.skillRegistry = skillRegistry;
        this.metricsTracker = metricsTracker;
        this.eventPublisher = eventPublisher;
    }

    /**
     * 激活指定 Skill，返回上下文注入包。
     *
     * @param skillId Skill ID
     * @return 激活结果，包含指令和建议工具
     * @throws SkillActivationException 当 Skill 不存在或不可激活时
     */
    public SkillActivation activate(String skillId) {
        // 1. 查找 Skill
        SkillDefinition definition = skillRegistry.find(skillId)
                .orElseThrow(() -> new SkillActivationException("Skill 不存在: " + skillId));

        // 2. 检查激活条件
        if (!canActivate(definition)) {
            throw new SkillActivationException("AutoGenerated Skill 未经用户确认，无法激活: " + skillId);
        }

        // 3. 记录激活指标
        metricsTracker.recordActivation(skillId);

        // 4. 发布激活事件
        eventPublisher.publishEvent(new SkillLifecycleEvent.Activated(skillId, UUID.randomUUID().toString()));
        log.info("Skill 已激活: skillId={}", skillId);

        // 5. 返回激活结果
        return new SkillActivation(definition.id(), definition.instructions(), definition.suggestedTools());
    }

    /**
     * 检查 Skill 是否可激活。
     *
     * <p>AutoGenerated 来源且用户未确认的 Skill 不可激活。</p>
     *
     * @param definition Skill 定义
     * @return true 可激活，false 不可激活
     */
    private boolean canActivate(SkillDefinition definition) {
        if (definition.source() instanceof SkillSource.AutoGenerated ag && !ag.userConfirmed()) {
            return false;
        }
        return true;
    }
}
