package com.lifepilot.skill.activation;

import com.lifepilot.agent.model.AgentState;
import com.lifepilot.skill.action.ActionResult;
import com.lifepilot.skill.action.SkillAction;
import com.lifepilot.skill.action.SkillActionDispatcher;
import com.lifepilot.skill.event.SkillLifecycleEvent;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.model.SkillSource;
import com.lifepilot.skill.model.SubAgentResult;
import com.lifepilot.skill.registry.SkillRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationEventPublisher;

import java.util.Map;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Skill 生命周期管理器 — 协调并发控制、L1 确定性执行和指标追踪。
 *
 * <p>核心职责：
 * <ul>
 *   <li>通过 {@link AtomicInteger} 控制最大并发激活数</li>
 *   <li>委托 {@link SkillActionDispatcher} 执行 L1 确定性动作（TemplateAction）</li>
 *   <li>发布 {@link SkillLifecycleEvent} 生命周期事件</li>
 *   <li>通过 {@link SkillMetricsTracker} 记录激活指标</li>
 * </ul>
 *
 * <p>L1 回归：移除 SubAgent 委托路径，所有 Skill 激活通过 SkillActionDispatcher
 * 以 TemplateAction 模式执行（将 systemPrompt 作为模板渲染）。</p>
 *
 * <p>并发超限时返回 success=false 的 {@link SubAgentResult}，不抛出异常。</p>
 *
 * @author zsg
 * @since 2026-07-28
 */
public class SkillLifecycleManager {

    private static final Logger log = LoggerFactory.getLogger(SkillLifecycleManager.class);

    private final AtomicInteger activeCount = new AtomicInteger(0);
    private final int maxConcurrentActivations;
    private final SkillRegistry skillRegistry;
    private final SkillActionDispatcher actionDispatcher;
    private final SkillMetricsTracker metricsTracker;
    private final ApplicationEventPublisher eventPublisher;

    public SkillLifecycleManager(int maxConcurrentActivations,
                                 SkillRegistry skillRegistry,
                                 SkillActionDispatcher actionDispatcher,
                                 SkillMetricsTracker metricsTracker,
                                 ApplicationEventPublisher eventPublisher) {
        this.maxConcurrentActivations = maxConcurrentActivations;
        this.skillRegistry = skillRegistry;
        this.actionDispatcher = actionDispatcher;
        this.metricsTracker = metricsTracker;
        this.eventPublisher = eventPublisher;
    }

    /**
     * 激活 Skill，检查并发限制后委托 SkillActionDispatcher 执行 L1 确定性动作。
     *
     * <p>执行策略：将 Skill 的 systemPrompt 作为 TemplateAction 渲染，
     * 用户输入通过 params 传入模板变量。自生成 Skill 未确认时拒绝激活。</p>
     *
     * @param skillId     Skill ID
     * @param input       用户输入
     * @param parentState 父 Agent 状态（保留用于轨迹关联）
     * @return SubAgentResult 执行结果
     */
    public SubAgentResult activate(String skillId, String input, AgentState parentState) {
        // 1. 检查并发限制
        if (activeCount.get() >= maxConcurrentActivations) {
            log.warn("Skill 并发激活超限: skillId={}, activeCount={}, maxConcurrent={}",
                    skillId, activeCount.get(), maxConcurrentActivations);
            return buildFailResult(skillId, "Skill 并发激活超限，当前活跃数: " + activeCount.get(),
                    "并发激活超限");
        }

        // 2. 查找 SkillDefinition
        SkillDefinition skill = skillRegistry.find(skillId).orElse(null);
        if (skill == null) {
            log.warn("Skill 不存在: skillId={}", skillId);
            return buildFailResult(skillId, "Skill 不存在: " + skillId, "Skill 不存在");
        }

        // 3. 检查自生成 Skill 是否已确认
        if (skill.source() instanceof SkillSource.AutoGenerated autoGen && !autoGen.userConfirmed()) {
            log.warn("自生成 Skill 未经用户确认，拒绝激活: skillId={}", skillId);
            return buildFailResult(skillId, "自生成 Skill 未经用户确认: " + skillId,
                    "自生成 Skill 未确认");
        }

        // 4. 递增活跃计数
        activeCount.incrementAndGet();

        String traceId = buildTraceId(skillId, parentState);

        // 5. 发布 Activated 事件
        eventPublisher.publishEvent(new SkillLifecycleEvent.Activated(skillId, traceId));

        SubAgentResult result = null;
        long startTime = System.currentTimeMillis();
        try {
            // 6. 委托 SkillActionDispatcher 执行 L1 确定性动作
            //    将 systemPrompt 作为 TemplateAction 渲染，input 作为模板变量
            var action = new SkillAction.TemplateAction(skill.systemPrompt());
            ActionResult actionResult = actionDispatcher.dispatch(
                    action,
                    Map.of("input", input),
                    null);

            long durationMs = System.currentTimeMillis() - startTime;

            result = SubAgentResult.builder()
                    .skillId(skillId)
                    .success(actionResult.success())
                    .output(actionResult.output())
                    .terminationReason(actionResult.success() ? null : "动作执行失败")
                    .tokensUsed(0)
                    .stepsExecuted(1)
                    .durationMs(durationMs)
                    .traceId(traceId)
                    .build();
        } catch (Exception e) {
            long durationMs = System.currentTimeMillis() - startTime;
            log.warn("Skill 激活执行异常: skillId={}, error={}", skillId, e.getMessage(), e);
            result = SubAgentResult.builder()
                    .skillId(skillId)
                    .success(false)
                    .output("Skill 执行失败: " + e.getMessage())
                    .terminationReason(e.getMessage())
                    .tokensUsed(0)
                    .stepsExecuted(0)
                    .durationMs(durationMs)
                    .traceId(traceId)
                    .build();
        } finally {
            // 7. 递减活跃计数
            activeCount.decrementAndGet();

            // 8. 记录指标
            if (result != null) {
                metricsTracker.record(skillId, result);
            }

            // 9. 发布 Deactivated 事件
            if (result != null) {
                eventPublisher.publishEvent(
                        new SkillLifecycleEvent.Deactivated(skillId, result.traceId(), result));
            }
        }

        return result;
    }

    /**
     * 获取当前活跃的 Skill 激活数。
     *
     * @return 当前活跃数
     */
    public int getActiveCount() {
        return activeCount.get();
    }

    /**
     * 构建失败结果。
     */
    private SubAgentResult buildFailResult(String skillId, String output, String reason) {
        return SubAgentResult.builder()
                .skillId(skillId)
                .success(false)
                .output(output)
                .terminationReason(reason)
                .tokensUsed(0)
                .stepsExecuted(0)
                .durationMs(0)
                .traceId("skill-" + skillId)
                .build();
    }

    /**
     * 构建 traceId，关联父 Agent 轨迹。
     */
    private String buildTraceId(String skillId, AgentState parentState) {
        String randomSuffix = UUID.randomUUID().toString().substring(0, 8);
        if (parentState != null && parentState.traceId() != null) {
            return parentState.traceId() + "/skill-" + skillId + "-" + randomSuffix;
        }
        return "skill-" + skillId + "-" + randomSuffix;
    }
}
