package com.lifepilot.skill.activation;

import com.lifepilot.skill.event.SkillLifecycleEvent;
import com.lifepilot.skill.install.SkillInstallation;
import com.lifepilot.skill.install.SkillInstallationRepository;
import com.lifepilot.skill.model.SkillActivation;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.registry.SkillRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationEventPublisher;

import java.time.Instant;
import java.util.List;

/**
 * Skill 激活器 — 将 Skill 从注册表中激活为上下文注入包。
 *
 * <p>v2 激活流程：
 * <ol>
 *   <li>查 {@link SkillInstallationRepository#findByName(String)} 事实源元数据</li>
 *   <li>校验 {@code enabled == true}，否则拒绝</li>
 *   <li>从 {@link SkillRegistry} 拿内存中的 {@link SkillDefinition}（body 已解析）</li>
 *   <li>替换 instructions 中的 3 个占位符为实际路径</li>
 *   <li>异步更新 {@code last_activated_at}、记录指标、发布激活事件</li>
 *   <li>返回 {@link SkillActivation} 供 ContextAssembler 注入上下文</li>
 * </ol>
 *
 * <p>v2 相对于 v1 的变化：
 * <ul>
 *   <li>去除 {@code AutoGenerated.userConfirmed} 检查；启用状态完全由 DB 的 {@code skills.enabled} 管</li>
 *   <li>占位符从 1 个 ({@code skill_scripts_dir}) 扩展到 3 个</li>
 *   <li>路径来源从 {@code SkillSource} switch 改为 {@link SkillInstallation#filePath()}</li>
 * </ul>
 *
 * @author zsg
 * @since 2026-04-24
 */
public class SkillActivator {

    private static final Logger log = LoggerFactory.getLogger(SkillActivator.class);

    /** instructions 中引用 Skill 根目录的占位符。 */
    private static final String SKILL_DIR_PLACEHOLDER = "{skill_dir}";
    /** instructions 中引用 references 目录的占位符。 */
    private static final String REFERENCES_DIR_PLACEHOLDER = "{skill_references_dir}";
    /** instructions 中引用 scripts 目录的占位符。 */
    private static final String SCRIPTS_DIR_PLACEHOLDER = "{skill_scripts_dir}";

    private final SkillRegistry skillRegistry;
    private final SkillInstallationRepository installationRepository;
    private final SkillMetricsTracker metricsTracker;
    private final ApplicationEventPublisher eventPublisher;

    public SkillActivator(SkillRegistry skillRegistry,
                          SkillInstallationRepository installationRepository,
                          SkillMetricsTracker metricsTracker,
                          ApplicationEventPublisher eventPublisher) {
        this.skillRegistry = skillRegistry;
        this.installationRepository = installationRepository;
        this.metricsTracker = metricsTracker;
        this.eventPublisher = eventPublisher;
    }

    /**
     * 激活指定 Skill，返回上下文注入包。
     *
     * @param name Skill 名称（v2 规范：name 取代旧的 id）
     * @return 激活结果，包含指令和建议工具
     * @throws IllegalArgumentException 当 Skill 在 skills 表中不存在
     * @throws IllegalStateException    当 Skill 已被禁用（{@code enabled=0}），或内存注册表尚未加载
     */
    public SkillActivation activate(String name) {
        // 1. 查事实源元数据
        SkillInstallation install = installationRepository.findByName(name)
                .orElseThrow(() -> new IllegalArgumentException("未知 skill: " + name));

        // 2. 校验启用状态
        if (!install.enabled()) {
            throw new IllegalStateException("skill '" + name + "' 已被禁用");
        }

        // 3. 拿内存 SkillDefinition（含解析后的 body 与 suggestedTools）
        SkillDefinition definition = skillRegistry.find(name)
                .orElseThrow(() -> new IllegalStateException(
                        "skill '" + name + "' 已登记但未加载到注册表，可能需要触发热加载"));

        // 4. 占位符替换
        String resolvedInstructions = resolvePlaceholders(definition.instructions(), install.filePath());

        // 5. 异步更新 last_activated_at（不阻塞激活返回 —— 用 virtual thread 避免占用公共 ForkJoinPool 资源）
        Thread.startVirtualThread(() -> {
            try {
                installationRepository.updateLastActivatedAt(name, Instant.now());
            } catch (Exception e) {
                log.warn("更新 last_activated_at 失败: name={}, error={}", name, e.getMessage());
            }
        });

        // 6. 记录激活指标
        metricsTracker.recordActivation(name);

        // 7. 发布激活事件
        eventPublisher.publishEvent(new SkillLifecycleEvent.Activated(name));
        log.info("Skill 已激活: name={}", name);

        return new SkillActivation(name, resolvedInstructions, definition.suggestedTools());
    }

    /**
     * 按顺序批量激活多个 Skill。
     *
     * @param names Skill 名称列表
     * @return 激活结果列表，顺序与输入保持一致
     */
    public List<SkillActivation> activateMany(List<String> names) {
        if (names == null || names.isEmpty()) {
            return List.of();
        }
        return names.stream()
                .map(this::activate)
                .toList();
    }

    /**
     * 替换 instructions 中的 3 个占位符为 {@link SkillInstallation#filePath()} 推导的实际路径。
     *
     * <p>占位符规则：
     * <ul>
     *   <li>{@code {skill_dir}} → {@code filePath}</li>
     *   <li>{@code {skill_references_dir}} → {@code filePath + "/references"}</li>
     *   <li>{@code {skill_scripts_dir}} → {@code filePath + "/scripts"}</li>
     * </ul>
     *
     * <p>顺序不敏感：先替换 references/scripts 再替换 skill_dir 亦可，因为 3 个 key 互不包含。
     * 实现上先替换 2 个子目录占位符，再替换根目录占位符，以避免 {@code {skill_dir}} 过早匹配子目录字符串。
     *
     * @param instructions 原始指令（可能不含任何占位符）
     * @param filePath     Skill 根目录绝对路径
     * @return 替换后的指令
     */
    private String resolvePlaceholders(String instructions, String filePath) {
        if (instructions == null || instructions.isEmpty()) {
            return instructions;
        }
        String referencesDir = filePath + "/references";
        String scriptsDir = filePath + "/scripts";
        return instructions
                .replace(REFERENCES_DIR_PLACEHOLDER, referencesDir)
                .replace(SCRIPTS_DIR_PLACEHOLDER, scriptsDir)
                .replace(SKILL_DIR_PLACEHOLDER, filePath);
    }
}
