package com.lifepilot.skill.disclosure;

import com.lifepilot.skill.activation.SkillActivationException;
import com.lifepilot.skill.activation.SkillActivator;
import com.lifepilot.skill.activation.SkillMetricsTracker;
import com.lifepilot.skill.generation.SkillGap;
import com.lifepilot.skill.generation.SkillGapDetector;
import com.lifepilot.skill.generation.SkillGenerator;
import com.lifepilot.skill.model.SkillActivation;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.model.SkillSource;
import com.lifepilot.tool.BuiltinTool;
import com.lifepilot.tool.model.ToolInput;
import com.lifepilot.tool.model.ToolResult;
import com.lifepilot.tool.registry.DynamicToolRegistry;
import com.lifepilot.tool.schema.JsonSchema;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * SkillDisclosureTool 单元测试 — 验证 load_skill 工具注册和执行逻辑。
 *
 * @author zsg
 * @since 2026-03-19
 */
class SkillDisclosureToolTest {

    private DynamicToolRegistry toolRegistry;
    private SkillActivator skillActivator;
    private SkillMetricsTracker metricsTracker;
    private SkillGapDetector gapDetector;
    private SkillGenerator skillGenerator;

    @BeforeEach
    void setUp() {
        toolRegistry = mock(DynamicToolRegistry.class);
        skillActivator = mock(SkillActivator.class);
        metricsTracker = new SkillMetricsTracker();
        gapDetector = mock(SkillGapDetector.class);
        skillGenerator = mock(SkillGenerator.class);
    }

    // ─────────────────────────────────────────────
    //  registerTools
    // ─────────────────────────────────────────────

    @Test
    void registerTools_注册load_skill到DynamicToolRegistry() {
        var tool = new SkillDisclosureTool(toolRegistry, skillActivator, metricsTracker,
                gapDetector, skillGenerator);

        tool.registerTools();

        var captor = ArgumentCaptor.forClass(BuiltinTool.class);
        verify(toolRegistry).registerBuiltinTool(captor.capture());
        BuiltinTool registered = captor.getValue();
        assertThat(registered.id()).isEqualTo("load_skill");
        assertThat(registered.idempotent()).isTrue();
    }

    // ─────────────────────────────────────────────
    //  load_skill 正常加载
    // ─────────────────────────────────────────────

    @Test
    void loadSkill_正常加载_返回指令和建议工具() {
        var activation = new SkillActivation("todo-manager", "请按以下步骤操作...",
                List.of("builtin.datastore.query"));
        when(skillActivator.activate("todo-manager")).thenReturn(activation);

        ToolResult result = executeLoadSkill("todo-manager");

        assertThat(result.ok()).isTrue();
        assertThat((String) result.getData("skill_id")).isEqualTo("todo-manager");
        assertThat((String) result.getData("instructions")).isEqualTo("请按以下步骤操作...");
    }

    // ─────────────────────────────────────────────
    //  load_skill — Skill 不存在，自扩展未启用
    // ─────────────────────────────────────────────

    @Test
    void loadSkill_不存在且自扩展未启用_返回错误() {
        when(skillActivator.activate("nonexistent"))
                .thenThrow(new SkillActivationException("Skill 不存在: nonexistent"));

        // 自扩展未启用：gapDetector 和 skillGenerator 为 null
        var tool = new SkillDisclosureTool(toolRegistry, skillActivator, metricsTracker,
                null, null);
        captureAndInvoke(tool);

        ToolResult result = invokeLoadSkill(tool, "nonexistent");

        assertThat(result.ok()).isFalse();
        assertThat(result.error()).contains("Skill 不存在");
    }

    // ─────────────────────────────────────────────
    //  load_skill — 被动自扩展触发
    // ─────────────────────────────────────────────

    @Test
    void loadSkill_不存在_被动自扩展生成成功() {
        when(skillActivator.activate("auto-cooking"))
                .thenThrow(new SkillActivationException("Skill 不存在: auto-cooking"));

        var gap = new SkillGap(0.9, "auto-cooking", "烹饪助手",
                "auto-cooking", List.of(), "注册表为空");
        when(gapDetector.detectGap("auto-cooking")).thenReturn(Optional.of(gap));

        var definition = SkillDefinition.builder()
                .id("auto-cooking").name("烹饪助手").description("帮助烹饪")
                .version("1.0").instructions("烹饪指南").suggestedTools(List.of())
                .source(new SkillSource.AutoGenerated("trace-1", Instant.now(), "auto-cooking", false))
                .metadata(Map.of()).build();
        when(skillGenerator.generate(any()))
                .thenReturn(SkillGenerator.GenerationResult.success(definition, "# 烹饪助手"));
        when(skillGenerator.confirmAndPersist(any())).thenReturn(true);

        ToolResult result = executeLoadSkill("auto-cooking");

        assertThat(result.ok()).isTrue();
        assertThat((String) result.getData("status")).isEqualTo("auto_generated");
    }

    @Test
    void loadSkill_不存在_被动自扩展生成失败() {
        when(skillActivator.activate("bad-skill"))
                .thenThrow(new SkillActivationException("Skill 不存在: bad-skill"));

        var gap = new SkillGap(0.9, "bad-skill", "坏技能",
                "bad-skill", List.of(), "测试");
        when(gapDetector.detectGap("bad-skill")).thenReturn(Optional.of(gap));
        when(skillGenerator.generate(any()))
                .thenReturn(SkillGenerator.GenerationResult.error("LLM 调用失败"));

        ToolResult result = executeLoadSkill("bad-skill");

        assertThat(result.ok()).isFalse();
        assertThat(result.error()).contains("自动生成失败");
    }

    @Test
    void loadSkill_不存在_未检测到缺口() {
        when(skillActivator.activate("no-gap"))
                .thenThrow(new SkillActivationException("Skill 不存在: no-gap"));
        when(gapDetector.detectGap("no-gap")).thenReturn(Optional.empty());

        ToolResult result = executeLoadSkill("no-gap");

        assertThat(result.ok()).isFalse();
        assertThat(result.error()).contains("未检测到能力缺口");
    }

    // ─────────────────────────────────────────────
    //  辅助方法
    // ─────────────────────────────────────────────

    /** 使用完整依赖创建工具并执行 load_skill。 */
    private ToolResult executeLoadSkill(String skillId) {
        var tool = new SkillDisclosureTool(toolRegistry, skillActivator, metricsTracker,
                gapDetector, skillGenerator);
        return invokeLoadSkill(tool, skillId);
    }

    /** 捕获注册的 BuiltinTool 并通过其 executor 调用。 */
    private ToolResult invokeLoadSkill(SkillDisclosureTool disclosureTool, String skillId) {
        var captor = ArgumentCaptor.forClass(BuiltinTool.class);
        disclosureTool.registerTools();
        verify(toolRegistry, atLeastOnce()).registerBuiltinTool(captor.capture());
        BuiltinTool registered = captor.getValue();

        var input = new ToolInput("load_skill",
                Map.of("skill_id", skillId),
                JsonSchema.empty(), null, null);
        return registered.execute(input);
    }

    /** 预先注册工具以便后续 verify 不冲突。 */
    private void captureAndInvoke(SkillDisclosureTool tool) {
        // 重置 mock 以避免之前的交互干扰
        reset(toolRegistry);
    }
}
