package com.lifepilot.skill.disclosure;

import com.lifepilot.skill.generation.SkillGenerator;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.model.SkillSource;
import com.lifepilot.tool.BuiltinTool;
import com.lifepilot.tool.model.ToolInput;
import com.lifepilot.tool.model.ToolResult;
import com.lifepilot.tool.registry.DynamicToolRegistry;
import com.lifepilot.tool.schema.JsonSchema;
import com.lifepilot.observability.guardrail.RiskLevel;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

import java.time.Instant;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * SkillGenerationTool 单元测试 — 验证 generate_skill 工具注册和执行逻辑。
 *
 * @author zsg
 * @since 2026-03-19
 */
class SkillGenerationToolTest {

    private DynamicToolRegistry toolRegistry;
    private SkillGenerator skillGenerator;

    @BeforeEach
    void setUp() {
        toolRegistry = mock(DynamicToolRegistry.class);
        skillGenerator = mock(SkillGenerator.class);
    }

    // ─────────────────────────────────────────────
    //  registerTools
    // ─────────────────────────────────────────────

    @Test
    void registerTools_注册generate_skill为HIGH风险() {
        var tool = new SkillGenerationTool(toolRegistry, skillGenerator);
        tool.registerTools();

        var captor = ArgumentCaptor.forClass(BuiltinTool.class);
        verify(toolRegistry).registerBuiltinTool(captor.capture());
        BuiltinTool registered = captor.getValue();
        assertThat(registered.id()).isEqualTo("generate_skill");
        assertThat(registered.riskLevel()).isEqualTo(RiskLevel.HIGH);
        assertThat(registered.idempotent()).isFalse();
    }

    // ─────────────────────────────────────────────
    //  generate_skill 正常生成
    // ─────────────────────────────────────────────

    @Test
    void generateSkill_正常生成并注册() {
        var definition = SkillDefinition.builder()
                .id("auto-123").name("测试技能").description("测试描述")
                .version("1.0").instructions("测试指令").suggestedTools(List.of("tool-a"))
                .source(new SkillSource.AutoGenerated("trace", Instant.now(), "测试", false))
                .metadata(Map.of()).build();
        when(skillGenerator.generate(any()))
                .thenReturn(SkillGenerator.GenerationResult.success(definition, "# 测试"));
        when(skillGenerator.persistAndRegister(any())).thenReturn(true);

        ToolResult result = invokeGenerateSkill("帮我创建一个测试技能", null);

        assertThat(result.ok()).isTrue();
        assertThat((String) result.getData("skill_id")).isEqualTo("auto-123");
        assertThat((String) result.getData("status")).isEqualTo("registered");
    }

    // ─────────────────────────────────────────────
    //  generate_skill 生成失败
    // ─────────────────────────────────────────────

    @Test
    void generateSkill_LLM生成失败_返回错误() {
        when(skillGenerator.generate(any()))
                .thenReturn(SkillGenerator.GenerationResult.error("LLM 超时"));

        ToolResult result = invokeGenerateSkill("帮我创建技能", null);

        assertThat(result.ok()).isFalse();
        assertThat(result.error()).contains("生成失败");
    }

    @Test
    void generateSkill_持久化失败_返回错误() {
        var definition = SkillDefinition.builder()
                .id("auto-456").name("失败技能").description("测试")
                .version("1.0").instructions("指令").suggestedTools(List.of())
                .source(new SkillSource.AutoGenerated("trace", Instant.now(), "测试", false))
                .metadata(Map.of()).build();
        when(skillGenerator.generate(any()))
                .thenReturn(SkillGenerator.GenerationResult.success(definition, "# 失败"));
        when(skillGenerator.persistAndRegister(any())).thenReturn(false);

        ToolResult result = invokeGenerateSkill("帮我创建技能", null);

        assertThat(result.ok()).isFalse();
        assertThat(result.error()).contains("持久化失败");
    }

    // ─────────────────────────────────────────────
    //  辅助方法
    // ─────────────────────────────────────────────

    private ToolResult invokeGenerateSkill(String description, String suggestedName) {
        var tool = new SkillGenerationTool(toolRegistry, skillGenerator);
        tool.registerTools();

        var captor = ArgumentCaptor.forClass(BuiltinTool.class);
        verify(toolRegistry).registerBuiltinTool(captor.capture());
        BuiltinTool registered = captor.getValue();

        var params = new java.util.HashMap<String, Object>();
        params.put("description", description);
        if (suggestedName != null) {
            params.put("suggested_name", suggestedName);
        }

        var input = new ToolInput("generate_skill", params, JsonSchema.empty(), null, null);
        return registered.execute(input);
    }
}
