package com.lifepilot.skill.registry;

import com.lifepilot.skill.config.SkillConfigProperties;
import com.lifepilot.skill.model.SkillDefinition;
import com.lifepilot.skill.model.SkillSource;
import com.lifepilot.tool.registry.DynamicToolRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

/**
 * Skill 定义校验器 — 在注册前校验 {@link SkillDefinition} 的合法性。
 *
 * <p>校验规则：
 * <ul>
 *   <li>ID 格式：{@code ^[a-z0-9-]{1,64}$}</li>
 *   <li>名称长度 ≤ 配置的 maxNameLength</li>
 *   <li>System Prompt 长度 ≤ 配置的 maxSystemPromptLength</li>
 *   <li>工具列表非空，且每个工具 ID 在 {@link DynamicToolRegistry} 中存在</li>
 *   <li>AUTO_GENERATED 来源额外限制：maxTokens、maxSteps、timeoutSeconds 不超过配置上限</li>
 * </ul>
 *
 * @author zsg
 * @since 2026-07-28
 */
public class SkillDefinitionValidator {

    private static final Logger log = LoggerFactory.getLogger(SkillDefinitionValidator.class);

    /** Skill ID 合法格式：小写字母、数字和连字符，长度 1-64。 */
    private static final Pattern ID_PATTERN = Pattern.compile("^[a-z0-9-]{1,64}$");

    private final DynamicToolRegistry toolRegistry;
    private final SkillConfigProperties.Validation validationConfig;

    public SkillDefinitionValidator(DynamicToolRegistry toolRegistry,
                                    SkillConfigProperties skillConfig) {
        this.toolRegistry = toolRegistry;
        this.validationConfig = skillConfig.getValidation();
    }

    /**
     * 校验 Skill 定义的合法性。
     *
     * @param definition 待校验的 Skill 定义
     * @return 校验结果，包含是否合法和错误信息列表
     */
    public ValidationResult validate(SkillDefinition definition) {
        var errors = new ArrayList<String>();

        // 校验 ID 格式
        if (definition.id() == null || !ID_PATTERN.matcher(definition.id()).matches()) {
            errors.add("Skill ID 格式不合法，必须匹配 ^[a-z0-9-]{1,64}$: " + definition.id());
        }

        // 校验名称长度
        if (definition.name() != null && definition.name().length() > validationConfig.getMaxNameLength()) {
            errors.add("Skill 名称长度超过限制: " + definition.name().length() + " > " + validationConfig.getMaxNameLength());
        }

        // 校验 System Prompt 长度
        if (definition.systemPrompt() != null && definition.systemPrompt().length() > validationConfig.getMaxSystemPromptLength()) {
            errors.add("System Prompt 长度超过限制: " + definition.systemPrompt().length() + " > " + validationConfig.getMaxSystemPromptLength());
        }

        // 校验工具列表非空
        if (definition.allowedTools() == null || definition.allowedTools().isEmpty()) {
            errors.add("工具列表不能为空");
        } else {
            // 校验每个工具 ID 在 DynamicToolRegistry 中存在
            for (String toolId : definition.allowedTools()) {
                if (toolRegistry.resolve(toolId).isEmpty()) {
                    errors.add("工具未注册: " + toolId);
                }
            }
        }

        // AUTO_GENERATED 来源额外限制
        if (definition.source() instanceof SkillSource.AutoGenerated) {
            if (definition.budget() != null) {
                if (definition.budget().maxTokens() > validationConfig.getAutoGeneratedMaxTokens()) {
                    errors.add("AUTO_GENERATED Skill 的 maxTokens 超过限制: "
                            + definition.budget().maxTokens() + " > " + validationConfig.getAutoGeneratedMaxTokens());
                }
                if (definition.budget().maxSteps() > validationConfig.getAutoGeneratedMaxSteps()) {
                    errors.add("AUTO_GENERATED Skill 的 maxSteps 超过限制: "
                            + definition.budget().maxSteps() + " > " + validationConfig.getAutoGeneratedMaxSteps());
                }
                if (definition.budget().timeoutSeconds() > validationConfig.getAutoGeneratedMaxTimeout()) {
                    errors.add("AUTO_GENERATED Skill 的 timeoutSeconds 超过限制: "
                            + definition.budget().timeoutSeconds() + " > " + validationConfig.getAutoGeneratedMaxTimeout());
                }
            }
        }

        boolean valid = errors.isEmpty();
        if (!valid) {
            log.debug("Skill 定义校验失败: id={}, errors={}", definition.id(), errors);
        }
        return new ValidationResult(valid, errors);
    }

    /**
     * 校验结果 — 包含是否合法和错误信息列表。
     *
     * @param valid  是否校验通过
     * @param errors 错误信息列表（不可变）
     */
    public record ValidationResult(boolean valid, List<String> errors) {
        /** 紧凑构造器 — 防御性拷贝。 */
        public ValidationResult {
            errors = List.copyOf(errors);
        }
    }
}
