CREATE TABLE model_service_vendor_templates (
    vendor_key                            TEXT PRIMARY KEY,
    display_name                          TEXT NOT NULL,
    provider_type                         TEXT NOT NULL,
    description                           TEXT NOT NULL,
    default_api_url                       TEXT NOT NULL,
    supported_kinds_json                  TEXT NOT NULL DEFAULT '[]',
    default_timeout_seconds               INTEGER NOT NULL DEFAULT 60,
    default_generation_capabilities_json  TEXT NOT NULL DEFAULT '[]',
    default_generation_scenes_json        TEXT NOT NULL DEFAULT '[]',
    default_supports_streaming            INTEGER NOT NULL DEFAULT 0,
    default_max_context_window            INTEGER,
    sort_order                            INTEGER NOT NULL DEFAULT 0,
    created_at                            TEXT NOT NULL,
    updated_at                            TEXT NOT NULL
);

CREATE TABLE model_service_model_presets (
    vendor_key            TEXT NOT NULL,
    kind                  TEXT NOT NULL CHECK (kind IN ('GENERATION', 'EMBEDDING', 'RERANK')),
    model_value           TEXT NOT NULL,
    label                 TEXT NOT NULL,
    recommended           INTEGER NOT NULL DEFAULT 0,
    capabilities_json     TEXT NOT NULL DEFAULT '[]',
    scenes_json           TEXT NOT NULL DEFAULT '[]',
    supports_streaming    INTEGER NOT NULL DEFAULT 0,
    max_context_window    INTEGER,
    embedding_dimension   INTEGER,
    sort_order            INTEGER NOT NULL DEFAULT 0,
    created_at            TEXT NOT NULL,
    updated_at            TEXT NOT NULL,
    PRIMARY KEY (vendor_key, kind, model_value),
    FOREIGN KEY (vendor_key) REFERENCES model_service_vendor_templates(vendor_key) ON DELETE CASCADE
);

INSERT INTO model_service_vendor_templates (
    vendor_key,
    display_name,
    provider_type,
    description,
    default_api_url,
    supported_kinds_json,
    default_timeout_seconds,
    default_generation_capabilities_json,
    default_generation_scenes_json,
    default_supports_streaming,
    default_max_context_window,
    sort_order,
    created_at,
    updated_at
) VALUES
('openai', 'OpenAI', 'OPENAI_COMPATIBLE',
 '官方 API，预置 GPT-5.4 与 text-embedding-3 系列。',
 'https://api.openai.com/v1',
 '["GENERATION","EMBEDDING"]',
 60,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1,
 400000,
 10,
 datetime('now'),
 datetime('now')),
('anthropic', 'Claude / Anthropic', 'ANTHROPIC',
 '原生 Anthropic 接口，预置 Claude 4.6 系列。',
 'https://api.anthropic.com',
 '["GENERATION"]',
 60,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING","VISION"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1,
 200000,
 20,
 datetime('now'),
 datetime('now')),
('deepseek', 'DeepSeek', 'OPENAI_COMPATIBLE',
 'OpenAI 兼容 API，预置 deepseek-chat 与 deepseek-reasoner。',
 'https://api.deepseek.com/v1',
 '["GENERATION"]',
 60,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1,
 128000,
 30,
 datetime('now'),
 datetime('now')),
('qwen', '阿里云百炼 / Qwen', 'OPENAI_COMPATIBLE',
 'DashScope OpenAI 兼容接口，预置 Qwen 文本、视觉、向量与排序模型。',
 'https://dashscope.aliyuncs.com/compatible-mode/v1',
 '["GENERATION","EMBEDDING","RERANK"]',
 60,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1,
 131072,
 40,
 datetime('now'),
 datetime('now')),
('custom-openai', '自定义 OpenAI 兼容', 'OPENAI_COMPATIBLE',
 '适合代理网关、自建兼容层或其他 OpenAI 风格接口。',
 'https://api.example.com/v1',
 '["GENERATION","EMBEDDING","RERANK"]',
 60,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1,
 131072,
 50,
 datetime('now'),
 datetime('now')),
('ollama', 'Ollama（本地）', 'OLLAMA',
 '本地模型服务，模型名称按你本机实际 tag 填写。',
 'http://localhost:11434',
 '["GENERATION","EMBEDDING"]',
 120,
 '["CHAT","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1,
 32768,
 60,
 datetime('now'),
 datetime('now')),
('tei', 'TEI / 本地推理', 'TEI',
 '本地 Embedding 或 Rerank 推理服务，模型名称按部署服务填写。',
 'http://localhost:8080',
 '["EMBEDDING","RERANK"]',
 60,
 '[]',
 '[]',
 0,
 NULL,
 70,
 datetime('now'),
 datetime('now'));

INSERT INTO model_service_model_presets (
    vendor_key,
    kind,
    model_value,
    label,
    recommended,
    capabilities_json,
    scenes_json,
    supports_streaming,
    max_context_window,
    embedding_dimension,
    sort_order,
    created_at,
    updated_at
) VALUES
('openai', 'GENERATION', 'gpt-5.4', 'GPT-5.4（推荐）', 1,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 400000, NULL, 10, datetime('now'), datetime('now')),
('openai', 'GENERATION', 'gpt-5.4-mini', 'GPT-5.4 Mini', 0,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 400000, NULL, 20, datetime('now'), datetime('now')),
('openai', 'GENERATION', 'gpt-4.1', 'GPT-4.1', 0,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 1048576, NULL, 30, datetime('now'), datetime('now')),
('openai', 'EMBEDDING', 'text-embedding-3-large', 'text-embedding-3-large（推荐）', 1,
 '[]', '[]', 0, NULL, 3072, 40, datetime('now'), datetime('now')),
('openai', 'EMBEDDING', 'text-embedding-3-small', 'text-embedding-3-small', 0,
 '[]', '[]', 0, NULL, 1536, 50, datetime('now'), datetime('now')),
('anthropic', 'GENERATION', 'claude-sonnet-4-6', 'Claude Sonnet 4.6（推荐）', 1,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING","VISION"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 200000, NULL, 10, datetime('now'), datetime('now')),
('anthropic', 'GENERATION', 'claude-opus-4-6', 'Claude Opus 4.6', 0,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING","VISION"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 200000, NULL, 20, datetime('now'), datetime('now')),
('anthropic', 'GENERATION', 'claude-haiku-4-5', 'Claude Haiku 4.5', 0,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING","VISION"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 200000, NULL, 30, datetime('now'), datetime('now')),
('deepseek', 'GENERATION', 'deepseek-chat', 'DeepSeek Chat（推荐）', 1,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 128000, NULL, 10, datetime('now'), datetime('now')),
('deepseek', 'GENERATION', 'deepseek-reasoner', 'DeepSeek Reasoner', 0,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 128000, NULL, 20, datetime('now'), datetime('now')),
('qwen', 'GENERATION', 'qwen-plus', 'Qwen-Plus（推荐）', 1,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 131072, NULL, 10, datetime('now'), datetime('now')),
('qwen', 'GENERATION', 'qwen-flash', 'Qwen-Flash', 0,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 131072, NULL, 20, datetime('now'), datetime('now')),
('qwen', 'GENERATION', 'qwen-vl-max', 'Qwen-VL-Max', 0,
 '["CHAT","STRUCTURED_OUTPUT","FUNCTION_CALLING","STREAMING","VISION"]',
 '["chat","agent_react","knowledge_extraction","memory_compression","skill_generation"]',
 1, 131072, NULL, 30, datetime('now'), datetime('now')),
('qwen', 'EMBEDDING', 'text-embedding-v4', 'text-embedding-v4（推荐）', 1,
 '[]', '[]', 0, NULL, 1024, 40, datetime('now'), datetime('now')),
('qwen', 'RERANK', 'qwen3-rerank', 'qwen3-rerank（推荐）', 1,
 '[]', '[]', 0, NULL, NULL, 50, datetime('now'), datetime('now')),
('qwen', 'RERANK', 'gte-rerank-v2', 'gte-rerank-v2', 0,
 '[]', '[]', 0, NULL, NULL, 60, datetime('now'), datetime('now'));
