-- Skill 注册信息持久化表
-- 存储 AutoGenerated 和 Marketplace 来源的 Skill 定义
-- UserDefined 和 Builtin 来源的 Skill 从文件系统/代码加载，不写入此表
CREATE TABLE IF NOT EXISTS skills (
    id                   TEXT PRIMARY KEY,          -- Skill ID (UUID)
    name                 TEXT NOT NULL,              -- Skill 名称
    description          TEXT,                       -- Skill 描述
    version              TEXT,                       -- 版本号
    source_type          TEXT NOT NULL,              -- 来源类型: BUILTIN / USER_DEFINED / AUTO_GENERATED / MARKETPLACE
    source_json          TEXT,                       -- 来源详情 JSON (e.g., folderPath for UserDefined)
    instructions         TEXT NOT NULL,              -- Skill 指令 (原 systemPrompt)
    suggested_tools_json TEXT,                       -- 建议工具列表 JSON 数组
    metadata_json        TEXT,                       -- 元数据 JSON
    created_at           TEXT NOT NULL,              -- ISO 8601 创建时间
    updated_at           TEXT NOT NULL               -- ISO 8601 更新时间
);

-- source_type 索引（按来源类型筛选）
CREATE INDEX IF NOT EXISTS idx_skills_source_type
    ON skills(source_type);

-- name 索引（按名称查询）
CREATE INDEX IF NOT EXISTS idx_skills_name
    ON skills(name);
