<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useSkillStore } from '@/stores/skill'
import type { SkillDetail } from '@/types'

const route = useRoute()
const router = useRouter()
const skillStore = useSkillStore()

const skillId = computed(() => route.params.id as string)
const skill = computed(() => skillStore.currentSkill)

const editingBasic = ref(false)
const basicInfo = ref({
  name: '',
  description: '',
  tags: [] as string[]
})

const yamlContent = ref('')
const yamlDirty = ref(false)
const yamlSaving = ref(false)

const testInput = ref('')
const testContext = ref('{}')
const testLoading = ref(false)
const testResult = ref<any>(null)

onMounted(async () => {
  await skillStore.fetchSkillDetail(skillId.value)
  if (skill.value) {
    initFormData()
  }
})

watch(() => skill.value, (newSkill) => {
  if (newSkill) {
    initFormData()
  }
})

function initFormData() {
  if (!skill.value) return
  
  basicInfo.value = {
    name: skill.value.name,
    description: skill.value.description || '',
    tags: [] // Skill 类型中没有 tags 字段，这里预留
  }
  
  // 如果是 YAML Skill，尝试从 metadata 中获取 YAML 内容
  if (skill.value.sourceType === 'UserDefined' && skill.value.metadata) {
    yamlContent.value = JSON.stringify(skill.value.metadata, null, 2)
  } else {
    yamlContent.value = ''
  }
  yamlDirty.value = false
}

const isYamlEditable = computed(() => {
  return skill.value?.sourceType === 'UserDefined'
})

async function saveBasicInfo() {
  if (!skill.value) return
  try {
    await skillStore.updateSkill(skill.value.id, {
      name: basicInfo.value.name,
      description: basicInfo.value.description
    })
    editingBasic.value = false
  } catch (e: any) {
    alert(e.message || '保存失败')
  }
}

async function saveYaml() {
  if (!skill.value || !yamlDirty.value || !isYamlEditable.value) return
  
  yamlSaving.value = true
  try {
    let parsedMetadata: Record<string, string> = {}
    try {
      parsedMetadata = JSON.parse(yamlContent.value)
    } catch {
      alert('YAML 格式错误')
      return
    }
    
    await skillStore.updateSkill(skill.value.id, {
      metadata: parsedMetadata
    })
    yamlDirty.value = false
  } catch (e: any) {
    alert(e.message || '保存失败')
  } finally {
    yamlSaving.value = false
  }
}

watch(yamlContent, () => {
  if (isYamlEditable.value) {
    yamlDirty.value = true
  }
})

async function runTest() {
  if (!skill.value || !testInput.value.trim() || testLoading.value) return
  
  testLoading.value = true
  testResult.value = null
  
  try {
    let context: Record<string, unknown> = {}
    try {
      context = JSON.parse(testContext.value || '{}')
    } catch {
      alert('上下文 JSON 格式错误')
      return
    }
    
    const result = await skillStore.testSkill(skill.value.id, {
      userMessage: testInput.value,
      context
    })
    testResult.value = result
  } catch (e: any) {
    testResult.value = {
      error: e.message || '测试失败'
    }
  } finally {
    testLoading.value = false
  }
}

const sourceLabel: Record<string, string> = {
  Builtin: '内置',
  UserDefined: '用户定义',
  AutoGenerated: '自动生成',
}
</script>

<template>
  <div class="flex flex-col h-full overflow-hidden">
    <!-- 头部 -->
    <div class="flex-shrink-0 p-6 border-b border-border">
      <div class="flex items-center justify-between mb-4">
        <div class="flex items-center gap-3">
          <button
            class="text-sm text-muted-foreground hover:text-foreground transition-colors"
            @click="router.push('/skills')"
          >
            ← 返回列表
          </button>
          <h2 class="text-2xl font-semibold text-foreground">
            {{ skill?.name || '加载中...' }}
          </h2>
          <span class="text-xs px-2 py-0.5 rounded-full bg-accent text-accent-foreground">
            {{ sourceLabel[skill?.sourceType || ''] ?? skill?.sourceType }}
          </span>
        </div>
      </div>
    </div>

    <!-- 内容区域 -->
    <div class="flex-1 overflow-y-auto p-6">
      <div v-if="!skill" class="text-sm text-muted-foreground">加载中...</div>
      <div v-else class="max-w-4xl mx-auto space-y-6">
        <!-- 基本信息 -->
        <div class="border border-border rounded-lg p-6">
          <div class="flex items-center justify-between mb-4">
            <h3 class="text-lg font-semibold text-foreground">基本信息</h3>
            <button
              v-if="!editingBasic && skill.sourceType !== 'Builtin'"
              class="text-sm text-muted-foreground hover:text-foreground transition-colors"
              @click="editingBasic = true"
            >
              编辑
            </button>
          </div>
          
          <div v-if="editingBasic" class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-foreground mb-1">名称</label>
              <input
                v-model="basicInfo.name"
                type="text"
                class="w-full px-3 py-2 rounded-md border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-foreground mb-1">描述</label>
              <textarea
                v-model="basicInfo.description"
                rows="3"
                class="w-full px-3 py-2 rounded-md border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring resize-none"
              />
            </div>
            <div class="flex justify-end gap-2">
              <button
                class="px-4 py-2 rounded-md border border-input hover:bg-accent transition-colors"
                @click="editingBasic = false"
              >
                取消
              </button>
              <button
                class="px-4 py-2 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
                @click="saveBasicInfo"
              >
                保存
              </button>
            </div>
          </div>
          <div v-else class="space-y-2 text-sm">
            <div>
              <span class="text-muted-foreground">描述：</span>
              <p class="mt-1">{{ skill.description || '无描述' }}</p>
            </div>
            <div>
              <span class="text-muted-foreground">版本：</span>
              <span>{{ skill.version }}</span>
            </div>
            <div v-if="skill.allowedTools.length > 0">
              <span class="text-muted-foreground">允许工具：</span>
              <div class="flex flex-wrap gap-1 mt-1">
                <span
                  v-for="tool in skill.allowedTools"
                  :key="tool"
                  class="text-xs px-2 py-0.5 rounded-full bg-accent text-accent-foreground"
                >
                  {{ tool }}
                </span>
              </div>
            </div>
            <div v-if="skill.systemPrompt">
              <span class="text-muted-foreground">系统提示词：</span>
              <pre class="mt-1 p-3 rounded-md bg-muted text-xs whitespace-pre-wrap break-words">{{ skill.systemPrompt }}</pre>
            </div>
          </div>
        </div>

        <!-- YAML 编辑器（仅 UserDefined 类型可编辑） -->
        <div v-if="isYamlEditable" class="border border-border rounded-lg p-6">
          <div class="flex items-center justify-between mb-4">
            <h3 class="text-lg font-semibold text-foreground">YAML 配置</h3>
            <div class="flex items-center gap-2">
              <span
                v-if="yamlDirty"
                class="text-xs text-muted-foreground"
              >
                未保存
              </span>
              <button
                v-if="yamlDirty"
                class="text-sm px-3 py-1 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
                :disabled="yamlSaving"
                @click="saveYaml"
              >
                {{ yamlSaving ? '保存中...' : '保存' }}
              </button>
            </div>
          </div>
          <textarea
            v-model="yamlContent"
            rows="15"
            placeholder="输入 YAML 配置..."
            class="w-full px-3 py-2 rounded-md border border-input bg-background text-foreground font-mono text-sm focus:outline-none focus:ring-2 focus:ring-ring resize-none"
          />
          <p class="text-xs text-muted-foreground mt-2">
            提示：YAML 配置以 JSON 格式存储，请使用有效的 JSON 格式
          </p>
        </div>

        <!-- 调试区域 -->
        <div class="border border-border rounded-lg p-6">
          <h3 class="text-lg font-semibold text-foreground mb-4">调试测试</h3>
          <div class="space-y-4">
            <div>
              <label class="block text-sm font-medium text-foreground mb-1">输入消息</label>
              <input
                v-model="testInput"
                type="text"
                placeholder="输入测试消息..."
                class="w-full px-3 py-2 rounded-md border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
              />
            </div>
            <div>
              <label class="block text-sm font-medium text-foreground mb-1">上下文 (JSON)</label>
              <textarea
                v-model="testContext"
                rows="4"
                placeholder='{"key": "value"}'
                class="w-full px-3 py-2 rounded-md border border-input bg-background text-foreground font-mono text-sm focus:outline-none focus:ring-2 focus:ring-ring resize-none"
              />
            </div>
            <button
              class="w-full px-4 py-2 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 transition-colors disabled:opacity-50"
              :disabled="!testInput.trim() || testLoading"
              @click="runTest"
            >
              {{ testLoading ? '测试中...' : '运行测试' }}
            </button>
            <div v-if="testResult" class="mt-4 p-4 rounded-md bg-muted">
              <h4 class="text-sm font-medium text-foreground mb-2">测试结果</h4>
              <pre v-if="testResult.error" class="text-sm text-destructive whitespace-pre-wrap break-words">
                {{ testResult.error }}
              </pre>
              <pre v-else class="text-sm text-foreground whitespace-pre-wrap break-words">
                {{ JSON.stringify(testResult, null, 2) }}
              </pre>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
