<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useSkillStore } from '@/stores/skill'
import { skillApi } from '@/api/client'
import type { SkillDetail } from '@/types'
import Breadcrumb from '@/components/global/Breadcrumb.vue'
import type { BreadcrumbItem } from '@/components/global/Breadcrumb.vue'
import MarkdownEditor from '@/components/editor/MarkdownEditor.vue'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import {
  Accordion, AccordionContent, AccordionItem, AccordionTrigger,
} from '@/components/ui/accordion'

const route = useRoute()
const router = useRouter()
const skillStore = useSkillStore()

const skillId = computed(() => route.params.id as string)
const skill = computed(() => skillStore.currentSkill)

// 面包屑导航
const breadcrumbItems = computed<BreadcrumbItem[]>(() => [
  { label: 'Skills', to: { name: 'skills' } },
  { label: skill.value?.name ?? '...' }
])

const editingBasic = ref(false)
const basicInfo = ref({
  name: '',
  description: '',
  tags: [] as string[]
})

// Markdown 编辑器状态
const markdownContent = ref('')
const markdownLoading = ref(true)

const testInput = ref('')
const testContext = ref('{}')
const testLoading = ref(false)
const testResult = ref<any>(null)

onMounted(async () => {
  await skillStore.fetchSkillDetail(skillId.value)
  if (skill.value) {
    initFormData()
    // 加载 Skill Markdown 定义
    try {
      markdownContent.value = await skillApi.getSkillMarkdown(skillId.value)
    } catch {
      markdownContent.value = ''
    }
    markdownLoading.value = false
  }
})

watch(() => skill.value, (newSkill) => {
  if (newSkill) {
    initFormData()
  }
})

function initFormData() {
  if (!skill.value) return

  basicInfo.value = {
    name: skill.value.name,
    description: skill.value.description || '',
    tags: []
  }
}

const isEnabled = computed(() => {
  return (skill.value as any)?.enabled ?? true
})

async function saveBasicInfo() {
  if (!skill.value) return
  try {
    await skillStore.updateSkill(skill.value.id, {
      name: basicInfo.value.name,
      description: basicInfo.value.description
    })
    editingBasic.value = false
  } catch (e: any) {
    alert(e.message || '保存失败')
  }
}

async function runTest() {
  if (!skill.value) return
  alert('当前版本暂未开放 Skill 独立测试接口，请在 Agent 中关联该 Skill 后通过对话进行验证。')
}

const sourceLabel: Record<string, string> = {
  Builtin: '内置',
  UserDefined: '用户定义',
  AutoGenerated: '自动生成',
}
</script>

<template>
  <div class="flex flex-col h-full overflow-hidden">
    <!-- 头部 -->
    <div class="flex-shrink-0 px-lg py-md border-b border-border bg-background/60 backdrop-blur-sm">
      <div class="max-w-[1200px] mx-auto">
        <!-- 面包屑导航 -->
        <Breadcrumb :items="breadcrumbItems" class="mb-2" />
        <div class="flex items-center justify-between gap-md">
          <div class="flex items-center gap-sm">
            <div class="flex flex-col gap-xs">
              <div class="flex items-center gap-sm">
                <h2 class="text-2xl font-semibold text-foreground leading-tight">
                  {{ skill?.name || '加载中...' }}
                </h2>
                <Badge variant="secondary">
                  {{ sourceLabel[skill?.sourceType || ''] ?? skill?.sourceType }}
                </Badge>
              </div>
              <p class="text-sm text-muted-foreground">
                了解这个能力能为你做什么，以及它在对话中的使用方式。
              </p>
            </div>
          </div>
          <div v-if="skill" class="flex items-center gap-sm">
            <span class="text-xs text-muted-foreground">
              当前状态：{{ isEnabled ? '启用中' : '已关闭' }}
            </span>
            <Button
              variant="outline"
              @click="isEnabled ? skillStore.disableSkill(skill.id) : skillStore.enableSkill(skill.id)"
            >
              {{ isEnabled ? '关闭此能力' : '启用此能力' }}
            </Button>
          </div>
        </div>
      </div>
    </div>

    <!-- 内容区域 -->
    <div class="flex-1 overflow-y-auto px-lg py-lg">
      <!-- Skeleton 加载占位符 -->
      <div v-if="!skill" class="max-w-[768px] mx-auto space-y-lg">
        <Card>
          <CardHeader>
            <Skeleton class="h-6 w-1/3" />
          </CardHeader>
          <CardContent class="space-y-3">
            <Skeleton class="h-4 w-full" />
            <Skeleton class="h-4 w-4/5" />
            <Skeleton class="h-4 w-2/3" />
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <Skeleton class="h-6 w-1/4" />
          </CardHeader>
          <CardContent class="space-y-3">
            <Skeleton class="h-4 w-1/2" />
            <Skeleton class="h-4 w-1/3" />
          </CardContent>
        </Card>
      </div>

      <div v-else class="max-w-[768px] mx-auto space-y-lg">
        <!-- 使用说明 -->
        <Card>
          <CardHeader>
            <CardTitle class="text-lg">这个能力能为你做什么</CardTitle>
          </CardHeader>
          <CardContent>
            <p class="text-sm text-muted-foreground leading-normal mb-md">
              {{ skill.description || '这个能力还没有详细描述，你可以先在对话中试着让它帮你完成一些任务。' }}
            </p>
            <div class="space-y-sm">
              <h4 class="text-sm font-medium text-foreground">你可以这样向它提问</h4>
              <ul class="list-disc list-inside space-y-xs text-sm text-muted-foreground">
                <li>用自己的语言描述你希望它帮你完成的事情，例如："帮我整理一下这周的重要待办。"</li>
                <li>如果有上下文信息，可以在同一条消息中一并提供。</li>
                <li>遇到不符合预期的结果，可以补充说明你的期望，它会尝试调整行为。</li>
              </ul>
            </div>
          </CardContent>
        </Card>

        <!-- 行为与数据概览 -->
        <Card>
          <CardHeader>
            <CardTitle class="text-lg">行为与数据概览</CardTitle>
          </CardHeader>
          <CardContent>
            <div class="space-y-sm text-sm text-muted-foreground">
              <div class="flex items-center justify-between">
                <span>版本</span>
                <span class="text-foreground">v{{ skill.version }}</span>
              </div>
              <div v-if="skill.allowedTools.length > 0" class="space-y-xs">
                <span class="block">可能会使用到的内部能力（工具）</span>
                <div class="flex flex-wrap gap-xs mt-xs">
                  <Badge
                    v-for="tool in skill.allowedTools"
                    :key="tool"
                    variant="secondary"
                  >
                    {{ tool }}
                  </Badge>
                </div>
              </div>
              <div class="pt-sm border-t border-border">
                <p class="text-xs text-muted-foreground">
                  数据安全：此能力只会在你发起请求时工作，不会在未征得你同意的情况下主动对外发送消息。
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <!-- 高级设置 — Accordion -->
        <Card>
          <Accordion type="single" collapsible>
            <AccordionItem value="advanced" class="border-b-0">
              <AccordionTrigger class="px-6 py-4 text-sm font-medium">
                高级设置（仅在你了解含义时再修改）
              </AccordionTrigger>
              <AccordionContent class="px-6 pb-6">
                <div class="space-y-md">
                  <!-- 基本信息编辑 -->
                  <div class="border border-dashed border-border rounded-lg p-md">
                    <div class="flex items-center justify-between mb-sm">
                      <h4 class="text-sm font-medium text-foreground">基础配置</h4>
                      <Button
                        v-if="!editingBasic && skill.sourceType !== 'Builtin'"
                        variant="ghost"
                        size="sm"
                        @click="editingBasic = true"
                      >
                        编辑
                      </Button>
                    </div>
                    <div v-if="editingBasic" class="space-y-sm">
                      <div class="space-y-1.5">
                        <Label for="edit-name" class="text-xs">名称</Label>
                        <Input
                          id="edit-name"
                          v-model="basicInfo.name"
                        />
                      </div>
                      <div class="space-y-1.5">
                        <Label for="edit-desc" class="text-xs">描述</Label>
                        <Textarea
                          id="edit-desc"
                          v-model="basicInfo.description"
                          :rows="3"
                          class="resize-none"
                        />
                      </div>
                      <div class="flex justify-end gap-sm mt-sm">
                        <Button variant="outline" size="sm" @click="editingBasic = false">
                          取消
                        </Button>
                        <Button size="sm" @click="saveBasicInfo">
                          保存
                        </Button>
                      </div>
                    </div>
                    <div v-else class="space-y-xs text-xs text-muted-foreground">
                      <div>
                        <span class="mr-xs text-muted-foreground">名称：</span>
                        <span class="text-foreground">{{ skill.name }}</span>
                      </div>
                      <div>
                        <span class="mr-xs text-muted-foreground">描述：</span>
                        <span class="text-foreground">{{ skill.description || '无描述' }}</span>
                      </div>
                    </div>
                  </div>

                  <!-- 系统提示词 -->
                  <div class="border border-dashed border-border rounded-lg p-md">
                    <h4 class="text-sm font-medium text-foreground mb-xs">系统提示词（System Prompt）</h4>
                    <p class="text-xs text-muted-foreground mb-sm">
                      这里定义了 LifePilot 在使用此能力时的内部说明。修改不当可能导致行为异常，请谨慎调整。
                    </p>
                    <pre class="mt-xs px-md py-sm rounded-md bg-muted text-xs whitespace-pre-wrap break-words leading-normal">{{ skill.systemPrompt }}</pre>
                  </div>

                  <!-- Skill 定义（SKILL.md）— 替换原 JSON 编辑区域 -->
                  <div class="border border-dashed border-border rounded-lg p-md">
                    <h4 class="text-sm font-medium text-foreground mb-xs">Skill 定义（SKILL.md）</h4>
                    <Skeleton v-if="markdownLoading" class="h-64 w-full" />
                    <MarkdownEditor
                      v-else
                      v-model="markdownContent"
                      :readonly="skill.sourceType !== 'UserDefined'"
                      title="SKILL.md"
                      :on-save="(content: string) => skillApi.updateSkillMarkdown(skillId, content)"
                    />
                  </div>

                  <!-- 调试测试 -->
                  <div class="border border-dashed border-border rounded-lg p-md">
                    <h4 class="text-sm font-medium text-foreground mb-xs">调试测试</h4>
                    <p class="text-xs text-muted-foreground mb-sm">
                      后续版本会在这里开放直接测试能力的功能。当前请在 Agent 中关联该能力后，通过对话进行验证。
                    </p>
                    <div class="space-y-sm opacity-70 pointer-events-none">
                      <div class="space-y-1.5">
                        <Label class="text-xs">输入消息</Label>
                        <Input
                          v-model="testInput"
                          placeholder="输入测试消息..."
                        />
                      </div>
                      <div class="space-y-1.5">
                        <Label class="text-xs">上下文 (JSON)</Label>
                        <Textarea
                          v-model="testContext"
                          :rows="4"
                          placeholder='{"key": "value"}'
                          class="font-mono text-xs resize-none"
                        />
                      </div>
                      <Button class="w-full" disabled>
                        运行测试（即将上线）
                      </Button>
                    </div>
                  </div>
                </div>
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </Card>
      </div>
    </div>
  </div>
</template>
