<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useSkillStore } from '@/stores/skill'
import type { SkillSummary, McpServer } from '@/types'
import SearchBar from '@/components/common/SearchBar.vue'
import FilterChips from '@/components/common/FilterChips.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import ErrorState from '@/components/common/ErrorState.vue'
import ConfirmDialog from '@/components/common/ConfirmDialog.vue'
import ToolSchemaCollapse from '@/components/mcp/ToolSchemaCollapse.vue'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from '@/components/ui/dialog'

const router = useRouter()
const store = useSkillStore()

const activeTab = ref<string>('skills')
const showCreateDialog = ref(false)
const deleteTarget = ref<SkillSummary | null>(null)
const selectedServer = ref<McpServer | null>(null)

// Skill 搜索筛选状态
const skillSearchQuery = ref('')
const skillSourceFilter = ref<'all' | 'Builtin' | 'UserDefined' | 'AutoGenerated'>('all')

// MCP 搜索状态
const mcpSearchQuery = ref('')

const newSkill = ref({
  name: '',
  description: '',
  sourceType: 'UserDefined' as 'Builtin' | 'UserDefined' | 'AutoGenerated'
})

// Skill 来源筛选选项
const skillSourceOptions = [
  { value: 'all', label: '全部' },
  { value: 'Builtin', label: '内置' },
  { value: 'UserDefined', label: '用户定义' },
  { value: 'AutoGenerated', label: '自动生成' },
]

// Skill 搜索 + 来源类型交集过滤
const filteredSkills = computed(() => {
  let result = store.skills

  if (skillSearchQuery.value.trim()) {
    const q = skillSearchQuery.value.toLowerCase()
    result = result.filter(s =>
      s.name.toLowerCase().includes(q) ||
      (s.description ?? '').toLowerCase().includes(q)
    )
  }

  if (skillSourceFilter.value !== 'all') {
    result = result.filter(s => s.sourceType === skillSourceFilter.value)
  }

  return result
})

// MCP Server 名称模糊搜索
const filteredMcpServers = computed(() => {
  if (!mcpSearchQuery.value.trim()) return store.mcpServers
  const q = mcpSearchQuery.value.toLowerCase()
  return store.mcpServers.filter(s => s.name.toLowerCase().includes(q))
})

onMounted(() => {
  store.fetchSkills()
  store.fetchMcpServers()
})

async function viewSkillDetail(skill: SkillSummary) {
  router.push(`/skills/${skill.id}`)
}

async function handleCreate() {
  if (!newSkill.value.name.trim()) {
    alert('请为能力填写名称')
    return
  }
  try {
    const skill = await store.createSkill(newSkill.value)
    showCreateDialog.value = false
    newSkill.value = { name: '', description: '', sourceType: 'UserDefined' }
    router.push(`/skills/${skill.id}`)
  } catch (e: any) {
    alert(e.message || '创建失败')
  }
}

async function confirmUnregister() {
  if (!deleteTarget.value) return
  try {
    await store.unregisterSkill(deleteTarget.value.id)
    deleteTarget.value = null
  } catch (e: any) {
    alert(e.message || '删除失败')
  }
}

async function toggleSkill(skill: SkillSummary, e: Event) {
  e.stopPropagation()
  try {
    const enabled = (skill as any).enabled ?? true
    if (enabled) {
      await store.disableSkill(skill.id)
    } else {
      await store.enableSkill(skill.id)
    }
  } catch (e: any) {
    alert(e.message || '操作失败')
  }
}

async function selectServer(server: McpServer) {
  if (selectedServer.value?.name === server.name) {
    selectedServer.value = null
    return
  }
  selectedServer.value = server
  await store.fetchServerTools(server.name)
}

function handleRetry() {
  store.fetchSkills()
  store.fetchMcpServers()
}

// 删除确认对话框状态
const showDeleteConfirm = computed({
  get: () => deleteTarget.value !== null,
  set: (val: boolean) => { if (!val) deleteTarget.value = null }
})

const sourceLabel: Record<string, string> = {
  Builtin: '内置',
  UserDefined: '用户定义',
  AutoGenerated: '自动生成',
}

const stateLabel: Record<string, { label: string; variant: 'default' | 'secondary' | 'outline' | 'destructive' }> = {
  CONNECTED: { label: '已连接', variant: 'default' },
  CONNECTING: { label: '连接中', variant: 'secondary' },
  DISCONNECTED: { label: '未连接', variant: 'outline' },
  RECONNECTING: { label: '重连中', variant: 'secondary' },
}
</script>

<template>
  <div class="flex flex-col h-full">
    <div class="flex-1 overflow-y-auto">
      <div class="max-w-[1200px] mx-auto px-md md:px-lg py-lg">

        <div class="flex items-center justify-between mb-md gap-sm">
          <div class="space-y-xs">
            <h2 class="text-2xl font-semibold text-foreground leading-tight">
              我的智能能力
            </h2>
            <p class="text-sm text-muted-foreground">
              在这里管理 LifePilot 能为你做的事情，你可以随时开启或关闭这些能力。
            </p>
          </div>
          <Button
            v-if="activeTab === 'skills'"
            @click="showCreateDialog = true"
          >
            新建能力（高级）
          </Button>
        </div>

        <!-- Tab 切换 — shadcn-vue Tabs -->
        <Tabs v-model="activeTab" class="mb-lg">
          <TabsList>
            <TabsTrigger value="skills">Skill 列表</TabsTrigger>
            <TabsTrigger value="mcp">MCP Server</TabsTrigger>
          </TabsList>

          <!-- Skill 列表 Tab -->
          <TabsContent value="skills">
            <!-- Skeleton 加载占位符 -->
            <div v-if="store.loading" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-md mt-md">
              <Card v-for="i in 6" :key="i" class="overflow-hidden">
                <CardHeader class="pb-2">
                  <div class="flex items-start justify-between gap-sm">
                    <Skeleton class="h-5 w-3/5" />
                    <Skeleton class="h-5 w-16 rounded-full" />
                  </div>
                </CardHeader>
                <CardContent class="pb-2">
                  <Skeleton class="h-4 w-full mb-2" />
                  <Skeleton class="h-4 w-2/3" />
                </CardContent>
                <CardFooter>
                  <Skeleton class="h-3 w-1/3" />
                </CardFooter>
              </Card>
            </div>

            <!-- 错误状态 -->
            <ErrorState
              v-else-if="store.error"
              title="加载失败"
              :description="store.error"
              action-label="重试"
              :show-action="true"
              @action="handleRetry"
            />

            <!-- 有数据时展示搜索筛选 + 列表 -->
            <template v-else-if="store.skills.length > 0">
              <!-- 搜索栏 + 来源筛选 -->
              <div class="flex flex-col sm:flex-row items-start sm:items-center gap-sm mb-md mt-md">
                <SearchBar
                  v-model="skillSearchQuery"
                  placeholder="搜索能力名称或描述..."
                  class="w-full sm:w-64"
                />
                <FilterChips
                  v-model="skillSourceFilter"
                  :options="skillSourceOptions"
                />
              </div>

              <!-- 过滤结果为空 -->
              <EmptyState
                v-if="filteredSkills.length === 0"
                icon="🔍"
                title="未找到匹配的能力"
                description="尝试调整搜索关键词或筛选条件"
              />

              <!-- Skill 卡片网格 -->
              <div
                v-else
                class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-md"
              >
                <Card
                  v-for="skill in filteredSkills"
                  :key="skill.id"
                  class="hover:-translate-y-0.5 hover:shadow-md hover:border-primary/50 transition-all duration-200 group"
                >
                  <CardHeader class="pb-2">
                    <div class="flex items-start justify-between gap-sm">
                      <div class="flex-1 min-w-0">
                        <CardTitle
                          class="text-sm leading-snug truncate cursor-pointer"
                          @click="viewSkillDetail(skill)"
                        >
                          {{ skill.name }}
                        </CardTitle>
                      </div>
                      <div class="flex flex-col items-end gap-xs shrink-0">
                        <Badge variant="secondary">
                          {{ sourceLabel[skill.sourceType] ?? skill.sourceType }}
                        </Badge>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent class="pb-2">
                    <p class="text-xs text-muted-foreground line-clamp-2 leading-normal">
                      {{ skill.description || '这个能力还没有添加描述。' }}
                    </p>
                    <div class="mt-sm text-xs text-muted-foreground">
                      <span class="mr-xs">适合用来：</span>
                      <span>{{ skill.description || '根据你的需求为你提供帮助' }}</span>
                    </div>
                  </CardContent>
                  <CardFooter class="pt-0">
                    <div class="flex items-center justify-between w-full">
                      <span class="text-xs text-muted-foreground">v{{ skill.version }}</span>
                      <div class="flex items-center gap-xs">
                        <Button
                          variant="outline"
                          size="sm"
                          @click="toggleSkill(skill, $event)"
                        >
                          {{ (skill as any).enabled ?? true ? '启用中' : '已关闭' }}
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          @click="viewSkillDetail(skill)"
                        >
                          了解详情
                        </Button>
                        <Button
                          v-if="skill.sourceType === 'UserDefined'"
                          variant="destructive"
                          size="sm"
                          @click.stop="deleteTarget = skill"
                        >
                          删除
                        </Button>
                      </div>
                    </div>
                  </CardFooter>
                </Card>
              </div>
            </template>

            <!-- 空列表引导状态 -->
            <EmptyState
              v-else
              icon="◎"
              title="还没有可用的智能能力"
              description="LifePilot 可以通过不同的能力帮助你管理任务、规划时间或整理信息。你可以先从系统推荐的能力开始使用，或者为自己创建一个专属能力。"
              action-label="创建能力"
              :show-action="true"
              @action="showCreateDialog = true"
            />
          </TabsContent>

          <!-- MCP Server Tab -->
          <TabsContent value="mcp">
            <!-- Skeleton 加载占位符 -->
            <div v-if="store.loading" class="space-y-sm mt-md">
              <Card v-for="i in 3" :key="i">
                <CardHeader class="pb-2">
                  <div class="flex items-center gap-sm">
                    <Skeleton class="h-5 w-1/4" />
                    <Skeleton class="h-5 w-16 rounded-full" />
                    <Skeleton class="h-4 w-20" />
                  </div>
                </CardHeader>
              </Card>
            </div>

            <!-- 错误状态 -->
            <ErrorState
              v-else-if="store.error"
              title="加载失败"
              :description="store.error"
              action-label="重试"
              :show-action="true"
              @action="handleRetry"
            />

            <!-- 有数据时展示搜索 + 列表 -->
            <template v-else-if="store.mcpServers.length > 0">
              <!-- MCP 搜索栏 -->
              <div class="mb-md mt-md">
                <SearchBar
                  v-model="mcpSearchQuery"
                  placeholder="搜索 MCP Server 名称..."
                  class="w-full sm:w-64"
                />
              </div>

              <!-- 过滤结果为空 -->
              <EmptyState
                v-if="filteredMcpServers.length === 0"
                icon="🔍"
                title="未找到匹配的 MCP Server"
                description="尝试调整搜索关键词"
              />

              <div v-else class="space-y-sm">
                <Card
                  v-for="server in filteredMcpServers"
                  :key="server.name"
                >
                  <CardHeader class="pb-2">
                    <div class="flex items-center gap-sm">
                      <CardTitle class="text-sm leading-snug">
                        {{ server.name }}
                      </CardTitle>
                      <Badge
                        :variant="stateLabel[server.state]?.variant ?? 'outline'"
                      >
                        {{ stateLabel[server.state]?.label ?? server.state }}
                      </Badge>
                      <span class="text-xs text-muted-foreground">
                        {{ server.toolCount }} 个工具
                      </span>
                      <div class="ml-auto flex gap-xs">
                        <Button
                          v-if="server.state === 'DISCONNECTED'"
                          size="sm"
                          @click="store.connectServer(server.name)"
                        >
                          连接
                        </Button>
                        <Button
                          v-if="server.state === 'CONNECTED'"
                          variant="outline"
                          size="sm"
                          @click="store.disconnectServer(server.name)"
                        >
                          断开
                        </Button>
                        <Button
                          variant="outline"
                          size="sm"
                          @click="selectServer(server)"
                        >
                          {{ selectedServer?.name === server.name ? '收起工具' : '查看工具' }}
                        </Button>
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent v-if="server.lastError || (selectedServer?.name === server.name && store.serverTools.length > 0)" class="pt-0">
                    <div
                      v-if="server.lastError"
                      class="text-xs text-destructive mb-sm"
                    >
                      {{ server.lastError }}
                    </div>

                    <!-- 工具列表（展开），集成 ToolSchemaCollapse -->
                    <div
                      v-if="selectedServer?.name === server.name && store.serverTools.length > 0"
                      class="border-t border-border pt-sm space-y-xs"
                    >
                      <ToolSchemaCollapse
                        v-for="tool in store.serverTools"
                        :key="tool.id"
                        :name="tool.name"
                        :description="tool.description"
                        :input-schema="tool.inputSchema"
                      />
                    </div>
                  </CardContent>
                </Card>
              </div>
            </template>

            <!-- 空列表引导状态 -->
            <EmptyState
              v-else
              icon="🔌"
              title="暂无 MCP Server"
              description="MCP Server 可以为 LifePilot 提供更多外部工具能力。你可以添加一个 MCP Server 来扩展功能。"
            />
          </TabsContent>
        </Tabs>
      </div>
    </div>

    <!-- 新建对话框 — shadcn-vue Dialog -->
    <Dialog v-model:open="showCreateDialog">
      <DialogContent class="sm:max-w-[448px]">
        <DialogHeader>
          <DialogTitle>新建能力（高级）</DialogTitle>
          <DialogDescription>
            适合熟悉 AI 配置的高级用户，创建一个完全自定义的智能能力。普通使用场景通常无需手动创建。
          </DialogDescription>
        </DialogHeader>
        <form class="space-y-4" @submit.prevent="handleCreate">
          <div class="space-y-1.5">
            <Label for="skill-name">名称 *</Label>
            <Input
              id="skill-name"
              v-model="newSkill.name"
              placeholder="例如：帮我规划本周目标"
            />
          </div>
          <div class="space-y-1.5">
            <Label for="skill-desc">描述</Label>
            <Textarea
              id="skill-desc"
              v-model="newSkill.description"
              placeholder="简单描述这个能力可以帮你做什么，便于后续识别和使用"
              :rows="3"
              class="resize-none"
            />
          </div>
          <DialogFooter>
            <Button type="button" variant="outline" @click="showCreateDialog = false">取消</Button>
            <Button type="submit">创建</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>

    <!-- 注销确认对话框 — 使用重构后的 ConfirmDialog（基于 AlertDialog） -->
    <ConfirmDialog
      v-model:show="showDeleteConfirm"
      title="确认注销"
      :message="deleteTarget ? `确定要注销 Skill「${deleteTarget.name}」吗？此操作不可撤销。` : ''"
      confirm-label="注销"
      confirm-variant="destructive"
      @confirm="confirmUnregister"
      @cancel="deleteTarget = null"
    />
  </div>
</template>
