<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useSkillStore } from '@/stores/skill'
import type { SkillSummary, McpServer } from '@/types'

const router = useRouter()
const store = useSkillStore()

const activeTab = ref<'skills' | 'mcp'>('skills')
const showDetail = ref(false)
const showCreateDialog = ref(false)
const deleteTarget = ref<SkillSummary | null>(null)
const selectedServer = ref<McpServer | null>(null)

const newSkill = ref({
  name: '',
  description: '',
  sourceType: 'UserDefined' as 'Builtin' | 'UserDefined' | 'AutoGenerated'
})

onMounted(() => {
  store.fetchSkills()
  store.fetchMcpServers()
})

async function viewSkillDetail(skill: SkillSummary) {
  router.push(`/skills/${skill.id}`)
}

async function confirmUnregister() {
  if (!deleteTarget.value) return
  try {
    await store.unregisterSkill(deleteTarget.value.id)
    deleteTarget.value = null
    showDetail.value = false
  } catch (e: any) {
    alert(e.message || '注销失败')
  }
}

async function handleCreate() {
  if (!newSkill.value.name.trim()) {
    alert('请输入 Skill 名称')
    return
  }
  try {
    const skill = await store.createSkill(newSkill.value)
    showCreateDialog.value = false
    router.push(`/skills/${skill.id}`)
  } catch (e: any) {
    alert(e.message || '创建失败')
  }
}

async function toggleSkill(skill: SkillSummary, e: Event) {
  e.stopPropagation()
  try {
    // 这里需要后端返回 enabled 状态，暂时使用占位逻辑
    // 实际应该根据 skill.enabled 判断
    await store.enableSkill(skill.id)
  } catch (e: any) {
    alert(e.message || '操作失败')
  }
}

async function selectServer(server: McpServer) {
  selectedServer.value = server
  await store.fetchServerTools(server.name)
}

const sourceLabel: Record<string, string> = {
  Builtin: '内置',
  UserDefined: '用户定义',
  AutoGenerated: '自动生成',
}

const stateLabel: Record<string, { label: string; class: string }> = {
  CONNECTED: { label: '已连接', class: 'bg-green-100 text-green-800' },
  CONNECTING: { label: '连接中', class: 'bg-blue-100 text-blue-800' },
  DISCONNECTED: { label: '未连接', class: 'bg-gray-100 text-gray-800' },
  RECONNECTING: { label: '重连中', class: 'bg-yellow-100 text-yellow-800' },
}
</script>

<template>
  <div class="flex flex-col h-full p-6">
    <!-- 错误提示 -->
    <div v-if="store.error" class="mb-4 p-3 rounded-md bg-destructive/10 text-destructive text-sm">
      {{ store.error }}
    </div>

    <div class="flex items-center justify-between mb-4">
      <h2 class="text-xl font-semibold text-foreground">技能管理</h2>
      <button
        v-if="activeTab === 'skills'"
        class="px-4 py-2 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
        @click="showCreateDialog = true"
      >
        新建 Skill
      </button>
    </div>

    <!-- Tab 切换 -->
    <div class="flex gap-1 mb-6 border-b border-border">
      <button
        class="px-4 py-2 text-sm transition-colors"
        :class="activeTab === 'skills' ? 'border-b-2 border-primary text-foreground' : 'text-muted-foreground hover:text-foreground'"
        @click="activeTab = 'skills'"
      >Skill 列表</button>
      <button
        class="px-4 py-2 text-sm transition-colors"
        :class="activeTab === 'mcp' ? 'border-b-2 border-primary text-foreground' : 'text-muted-foreground hover:text-foreground'"
        @click="activeTab = 'mcp'"
      >MCP Server</button>
    </div>

    <!-- Skill 列表 -->
    <template v-if="activeTab === 'skills'">
      <div v-if="store.loading" class="text-sm text-muted-foreground">加载中...</div>
      <div v-else-if="store.skills.length === 0" class="text-sm text-muted-foreground">暂无 Skill</div>
      <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <div
          v-for="skill in store.skills"
          :key="skill.id"
          class="border border-border rounded-lg p-4 hover:border-primary/50 transition-colors"
        >
          <div class="flex items-start justify-between mb-2">
            <h3
              class="font-medium text-foreground truncate cursor-pointer flex-1"
              @click="viewSkillDetail(skill)"
            >
              {{ skill.name }}
            </h3>
            <span class="text-xs px-2 py-0.5 rounded-full bg-accent text-accent-foreground shrink-0 ml-2">
              {{ sourceLabel[skill.sourceType] ?? skill.sourceType }}
            </span>
          </div>
          <p class="text-sm text-muted-foreground mb-2 line-clamp-2">{{ skill.description || '无描述' }}</p>
          <div class="flex items-center justify-between">
            <div class="text-xs text-muted-foreground">v{{ skill.version }}</div>
            <div class="flex gap-2">
              <button
                class="text-xs px-2 py-1 rounded-md border border-input hover:bg-accent transition-colors"
                @click="viewSkillDetail(skill)"
              >
                查看
              </button>
              <button
                v-if="skill.sourceType !== 'Builtin'"
                class="text-xs px-2 py-1 rounded-md bg-destructive text-destructive-foreground hover:bg-destructive/90 transition-colors"
                @click.stop="deleteTarget = skill"
              >
                删除
              </button>
            </div>
          </div>
        </div>
      </div>
    </template>

    <!-- MCP Server 列表 -->
    <template v-if="activeTab === 'mcp'">
      <div v-if="store.loading" class="text-sm text-muted-foreground">加载中...</div>
      <div v-else-if="store.mcpServers.length === 0" class="text-sm text-muted-foreground">暂无 MCP Server</div>
      <div v-else class="space-y-3">
        <div
          v-for="server in store.mcpServers"
          :key="server.name"
          class="border border-border rounded-lg p-4"
        >
          <div class="flex items-center gap-3">
            <h3 class="font-medium text-foreground">{{ server.name }}</h3>
            <span
              class="text-xs px-2 py-0.5 rounded-full shrink-0"
              :class="stateLabel[server.state]?.class ?? 'bg-gray-100 text-gray-800'"
            >{{ stateLabel[server.state]?.label ?? server.state }}</span>
            <span class="text-xs text-muted-foreground">{{ server.toolCount }} 个工具</span>
            <div class="ml-auto flex gap-2">
              <button
                v-if="server.state === 'DISCONNECTED'"
                class="text-xs px-3 py-1 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
                @click="store.connectServer(server.name)"
              >连接</button>
              <button
                v-if="server.state === 'CONNECTED'"
                class="text-xs px-3 py-1 rounded-md border border-input hover:bg-accent transition-colors"
                @click="store.disconnectServer(server.name)"
              >断开</button>
              <button
                class="text-xs px-3 py-1 rounded-md border border-input hover:bg-accent transition-colors"
                @click="selectServer(server)"
              >查看工具</button>
            </div>
          </div>
          <div v-if="server.lastError" class="text-xs text-destructive mt-2">{{ server.lastError }}</div>

          <!-- 工具列表（展开） -->
          <div v-if="selectedServer?.name === server.name && store.serverTools.length > 0" class="mt-3 border-t border-border pt-3 space-y-1">
            <div
              v-for="tool in store.serverTools"
              :key="tool.id"
              class="text-sm flex gap-2"
            >
              <span class="font-mono text-foreground">{{ tool.name }}</span>
              <span class="text-muted-foreground">{{ tool.description }}</span>
            </div>
          </div>
        </div>
      </div>
    </template>

    <!-- Skill 详情抽屉 -->
    <div v-if="showDetail && store.currentSkill" class="fixed inset-0 bg-black/50 flex justify-end z-50" @click.self="showDetail = false">
      <div class="bg-card border-l border-border w-full max-w-md h-full overflow-y-auto p-6">
        <div class="flex items-center justify-between mb-4">
          <h3 class="text-lg font-semibold text-foreground">{{ store.currentSkill.name }}</h3>
          <button class="text-muted-foreground hover:text-foreground" @click="showDetail = false">×</button>
        </div>
        <div class="space-y-4 text-sm">
          <div>
            <span class="text-muted-foreground">来源：</span>
            <span>{{ sourceLabel[store.currentSkill.sourceType] ?? store.currentSkill.sourceType }}</span>
          </div>
          <div>
            <span class="text-muted-foreground">版本：</span>
            <span>{{ store.currentSkill.version }}</span>
          </div>
          <div>
            <span class="text-muted-foreground">描述：</span>
            <p class="mt-1">{{ store.currentSkill.description || '无描述' }}</p>
          </div>
          <div v-if="store.currentSkill.allowedTools.length > 0">
            <span class="text-muted-foreground">允许工具：</span>
            <div class="flex flex-wrap gap-1 mt-1">
              <span
                v-for="tool in store.currentSkill.allowedTools"
                :key="tool"
                class="text-xs px-2 py-0.5 rounded-full bg-accent text-accent-foreground"
              >{{ tool }}</span>
            </div>
          </div>
          <div v-if="store.currentSkill.systemPrompt">
            <span class="text-muted-foreground">系统提示词：</span>
            <pre class="mt-1 p-3 rounded-md bg-muted text-xs whitespace-pre-wrap break-words">{{ store.currentSkill.systemPrompt }}</pre>
          </div>
          <!-- 注销按钮（非 Builtin） -->
          <button
            v-if="store.currentSkill.sourceType !== 'Builtin'"
            class="w-full h-9 rounded-md text-sm bg-destructive text-destructive-foreground hover:bg-destructive/90 transition-colors"
            @click="deleteTarget = store.currentSkill"
          >注销此 Skill</button>
        </div>
      </div>
    </div>

    <!-- 新建对话框 -->
    <div
      v-if="showCreateDialog"
      class="fixed inset-0 bg-black/50 flex items-center justify-center z-50"
      @click.self="showCreateDialog = false"
    >
      <div class="bg-card border border-border rounded-lg p-6 w-full max-w-md shadow-lg">
        <h3 class="text-lg font-semibold text-foreground mb-4">新建 Skill</h3>
        <div class="space-y-4">
          <div>
            <label class="block text-sm font-medium text-foreground mb-1">名称 *</label>
            <input
              v-model="newSkill.name"
              type="text"
              placeholder="输入 Skill 名称"
              class="w-full px-3 py-2 rounded-md border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-foreground mb-1">描述</label>
            <textarea
              v-model="newSkill.description"
              placeholder="输入 Skill 描述"
              rows="3"
              class="w-full px-3 py-2 rounded-md border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring resize-none"
            />
          </div>
        </div>
        <div class="flex justify-end gap-2 mt-6">
          <button
            class="px-4 py-2 rounded-md border border-input hover:bg-accent transition-colors"
            @click="showCreateDialog = false"
          >
            取消
          </button>
          <button
            class="px-4 py-2 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
            @click="handleCreate"
          >
            创建
          </button>
        </div>
      </div>
    </div>

    <!-- 注销确认对话框 -->
    <div v-if="deleteTarget" class="fixed inset-0 bg-black/50 flex items-center justify-center z-[60]" @click.self="deleteTarget = null">
      <div class="bg-card border border-border rounded-lg p-6 w-full max-w-sm shadow-lg">
        <h3 class="text-lg font-semibold text-foreground mb-2">确认注销</h3>
        <p class="text-sm text-muted-foreground mb-4">
          确定要注销 Skill「{{ deleteTarget.name }}」吗？此操作不可撤销。
        </p>
        <div class="flex justify-end gap-2">
          <button
            class="h-9 px-4 rounded-md text-sm border border-input hover:bg-accent transition-colors"
            @click="deleteTarget = null"
          >取消</button>
          <button
            class="h-9 px-4 rounded-md text-sm bg-destructive text-destructive-foreground hover:bg-destructive/90 transition-colors"
            @click="confirmUnregister"
          >注销</button>
        </div>
      </div>
    </div>
  </div>
</template>
