<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useSkillStore } from '@/stores/skill'
import type { SkillSummary, McpServer } from '@/types'
import SearchBar from '@/components/common/SearchBar.vue'
import FilterChips from '@/components/common/FilterChips.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import ErrorState from '@/components/common/ErrorState.vue'
import LoadingSpinner from '@/components/common/LoadingSpinner.vue'
import ToolSchemaCollapse from '@/components/mcp/ToolSchemaCollapse.vue'

const router = useRouter()
const store = useSkillStore()

const activeTab = ref<'skills' | 'mcp'>('skills')
const showCreateDialog = ref(false)
const deleteTarget = ref<SkillSummary | null>(null)
const selectedServer = ref<McpServer | null>(null)

// Skill 搜索筛选状态
const skillSearchQuery = ref('')
const skillSourceFilter = ref<'all' | 'Builtin' | 'UserDefined' | 'AutoGenerated'>('all')

// MCP 搜索状态
const mcpSearchQuery = ref('')

const newSkill = ref({
  name: '',
  description: '',
  sourceType: 'UserDefined' as 'Builtin' | 'UserDefined' | 'AutoGenerated'
})

// Skill 来源筛选选项
const skillSourceOptions = [
  { value: 'all', label: '全部' },
  { value: 'Builtin', label: '内置' },
  { value: 'UserDefined', label: '用户定义' },
  { value: 'AutoGenerated', label: '自动生成' },
]

// Skill 搜索 + 来源类型交集过滤
const filteredSkills = computed(() => {
  let result = store.skills

  if (skillSearchQuery.value.trim()) {
    const q = skillSearchQuery.value.toLowerCase()
    result = result.filter(s =>
      s.name.toLowerCase().includes(q) ||
      (s.description ?? '').toLowerCase().includes(q)
    )
  }

  if (skillSourceFilter.value !== 'all') {
    result = result.filter(s => s.sourceType === skillSourceFilter.value)
  }

  return result
})

// MCP Server 名称模糊搜索
const filteredMcpServers = computed(() => {
  if (!mcpSearchQuery.value.trim()) return store.mcpServers
  const q = mcpSearchQuery.value.toLowerCase()
  return store.mcpServers.filter(s => s.name.toLowerCase().includes(q))
})

onMounted(() => {
  store.fetchSkills()
  store.fetchMcpServers()
})

async function viewSkillDetail(skill: SkillSummary) {
  router.push(`/skills/${skill.id}`)
}

async function handleCreate() {
  if (!newSkill.value.name.trim()) {
    alert('请为能力填写名称')
    return
  }
  try {
    const skill = await store.createSkill(newSkill.value)
    showCreateDialog.value = false
    router.push(`/skills/${skill.id}`)
  } catch (e: any) {
    alert(e.message || '创建失败')
  }
}

async function confirmUnregister() {
  if (!deleteTarget.value) return
  try {
    await store.unregisterSkill(deleteTarget.value.id)
    deleteTarget.value = null
  } catch (e: any) {
    alert(e.message || '删除失败')
  }
}

async function toggleSkill(skill: SkillSummary, e: Event) {
  e.stopPropagation()
  try {
    const enabled = (skill as any).enabled ?? true
    if (enabled) {
      await store.disableSkill(skill.id)
    } else {
      await store.enableSkill(skill.id)
    }
  } catch (e: any) {
    alert(e.message || '操作失败')
  }
}

async function selectServer(server: McpServer) {
  if (selectedServer.value?.name === server.name) {
    selectedServer.value = null
    return
  }
  selectedServer.value = server
  await store.fetchServerTools(server.name)
}

function handleRetry() {
  store.fetchSkills()
  store.fetchMcpServers()
}

const sourceLabel: Record<string, string> = {
  Builtin: '内置',
  UserDefined: '用户定义',
  AutoGenerated: '自动生成',
}

const stateLabel: Record<string, { label: string; class: string }> = {
  CONNECTED: { label: '已连接', class: 'bg-primary/10 text-primary' },
  CONNECTING: { label: '连接中', class: 'bg-accent text-accent-foreground' },
  DISCONNECTED: { label: '未连接', class: 'bg-muted text-muted-foreground' },
  RECONNECTING: { label: '重连中', class: 'bg-accent/70 text-accent-foreground' },
}
</script>

<template>
  <div class="flex flex-col h-full">
    <div class="flex-1 overflow-y-auto">
      <div class="max-w-[1200px] mx-auto px-md md:px-lg py-lg">

        <div class="flex items-center justify-between mb-md gap-sm">
          <div class="space-y-xs">
            <h2 class="text-2xl font-semibold text-foreground leading-tight">
              我的智能能力
            </h2>
            <p class="text-sm text-muted-foreground">
              在这里管理 LifePilot 能为你做的事情，你可以随时开启或关闭这些能力。
            </p>
          </div>
          <button
            v-if="activeTab === 'skills'"
            class="px-md py-sm rounded-lg bg-primary text-primary-foreground text-sm font-medium hover:bg-primary/90 hover:shadow-md transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
            @click="showCreateDialog = true"
          >
            新建能力（高级）
          </button>
        </div>

        <!-- Tab 切换 -->
        <div class="flex gap-xs mb-lg border-b border-border text-sm">
          <button
            class="px-md py-sm -mb-px border-b-2 transition-colors"
            :class="activeTab === 'skills'
              ? 'border-primary text-foreground'
              : 'border-transparent text-muted-foreground hover:text-foreground'"
            @click="activeTab = 'skills'"
          >
            Skill 列表
          </button>
          <button
            class="px-md py-sm -mb-px border-b-2 transition-colors"
            :class="activeTab === 'mcp'
              ? 'border-primary text-foreground'
              : 'border-transparent text-muted-foreground hover:text-foreground'"
            @click="activeTab = 'mcp'"
          >
            MCP Server
          </button>
        </div>

        <!-- Skill 列表 -->
        <template v-if="activeTab === 'skills'">
          <!-- 加载状态 -->
          <LoadingSpinner v-if="store.loading" text="加载能力列表..." />

          <!-- 错误状态 -->
          <ErrorState
            v-else-if="store.error"
            title="加载失败"
            :description="store.error"
            action-label="重试"
            :show-action="true"
            @action="handleRetry"
          />

          <!-- 有数据时展示搜索筛选 + 列表 -->
          <template v-else-if="store.skills.length > 0">
            <!-- 搜索栏 + 来源筛选 -->
            <div class="flex flex-col sm:flex-row items-start sm:items-center gap-sm mb-md">
              <SearchBar
                v-model="skillSearchQuery"
                placeholder="搜索能力名称或描述..."
                class="w-full sm:w-64"
              />
              <FilterChips
                v-model="skillSourceFilter"
                :options="skillSourceOptions"
              />
            </div>

            <!-- 过滤结果为空 -->
            <EmptyState
              v-if="filteredSkills.length === 0"
              icon="🔍"
              title="未找到匹配的能力"
              description="尝试调整搜索关键词或筛选条件"
            />

            <!-- Skill 卡片网格 -->
            <div
              v-else
              class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-md"
            >
              <div
                v-for="skill in filteredSkills"
                :key="skill.id"
                class="border border-border rounded-lg p-md hover:border-primary/50 hover:shadow-sm transition-all duration-200 bg-card"
              >
                <div class="flex items-start justify-between mb-xs gap-sm">
                  <div class="flex-1 min-w-0">
                    <h3
                      class="font-medium text-foreground truncate cursor-pointer text-sm leading-snug"
                      @click="viewSkillDetail(skill)"
                    >
                      {{ skill.name }}
                    </h3>
                    <p class="mt-xs text-xs text-muted-foreground line-clamp-2 leading-normal">
                      {{ skill.description || '这个能力还没有添加描述。' }}
                    </p>
                  </div>
                  <div class="flex flex-col items-end gap-xs shrink-0 ml-sm">
                    <span class="text-xs px-sm py-xs rounded-full bg-accent text-accent-foreground">
                      {{ sourceLabel[skill.sourceType] ?? skill.sourceType }}
                    </span>
                    <button
                      class="mt-xs inline-flex items-center gap-xs px-sm py-xs rounded-full text-xs border border-input hover:bg-accent transition-colors"
                      @click="toggleSkill(skill, $event)"
                    >
                      <span>
                        {{ (skill as any).enabled ?? true ? '启用中' : '已关闭' }}
                      </span>
                    </button>
                  </div>
                </div>
                <div class="mt-sm space-y-xs text-xs text-muted-foreground">
                  <div>
                    <span class="mr-xs text-muted-foreground">适合用来：</span>
                    <span>{{ skill.description || '根据你的需求为你提供帮助' }}</span>
                  </div>
                  <div class="flex items-center justify-between">
                    <span>v{{ skill.version }}</span>
                    <div class="flex items-center gap-xs">
                      <button
                        class="text-xs px-sm py-xs rounded-lg border border-input hover:bg-accent hover:text-accent-foreground transition-colors"
                        @click="viewSkillDetail(skill)"
                      >
                        了解详情
                      </button>
                      <button
                        v-if="skill.sourceType === 'UserDefined'"
                        class="text-xs px-sm py-xs rounded-lg bg-destructive text-destructive-foreground hover:bg-destructive/90 transition-colors"
                        @click.stop="deleteTarget = skill"
                      >
                        删除
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </template>

          <!-- 空列表引导状态 -->
          <EmptyState
            v-else
            icon="◎"
            title="还没有可用的智能能力"
            description="LifePilot 可以通过不同的能力帮助你管理任务、规划时间或整理信息。你可以先从系统推荐的能力开始使用，或者为自己创建一个专属能力。"
            action-label="创建能力"
            :show-action="true"
            @action="showCreateDialog = true"
          />
        </template>

        <!-- MCP Server 列表 -->
        <template v-if="activeTab === 'mcp'">
          <!-- 加载状态 -->
          <LoadingSpinner v-if="store.loading" text="加载 MCP Server..." />

          <!-- 错误状态 -->
          <ErrorState
            v-else-if="store.error"
            title="加载失败"
            :description="store.error"
            action-label="重试"
            :show-action="true"
            @action="handleRetry"
          />

          <!-- 有数据时展示搜索 + 列表 -->
          <template v-else-if="store.mcpServers.length > 0">
            <!-- MCP 搜索栏 -->
            <div class="mb-md">
              <SearchBar
                v-model="mcpSearchQuery"
                placeholder="搜索 MCP Server 名称..."
                class="w-full sm:w-64"
              />
            </div>

            <!-- 过滤结果为空 -->
            <EmptyState
              v-if="filteredMcpServers.length === 0"
              icon="🔍"
              title="未找到匹配的 MCP Server"
              description="尝试调整搜索关键词"
            />

            <div v-else class="space-y-sm">
              <div
                v-for="server in filteredMcpServers"
                :key="server.name"
                class="border border-border rounded-lg p-md bg-card"
              >
                <div class="flex items-center gap-sm">
                  <h3 class="font-medium text-foreground text-sm leading-snug">
                    {{ server.name }}
                  </h3>
                  <span
                    class="text-xs px-sm py-xs rounded-full shrink-0"
                    :class="stateLabel[server.state]?.class ?? 'bg-muted text-foreground'"
                  >
                    {{ stateLabel[server.state]?.label ?? server.state }}
                  </span>
                  <span class="text-xs text-muted-foreground">
                    {{ server.toolCount }} 个工具
                  </span>
                  <div class="ml-auto flex gap-xs">
                    <button
                      v-if="server.state === 'DISCONNECTED'"
                      class="text-xs px-md py-xs rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors"
                      @click="store.connectServer(server.name)"
                    >
                      连接
                    </button>
                    <button
                      v-if="server.state === 'CONNECTED'"
                      class="text-xs px-md py-xs rounded-lg border border-input hover:bg-accent transition-colors"
                      @click="store.disconnectServer(server.name)"
                    >
                      断开
                    </button>
                    <button
                      class="text-xs px-md py-xs rounded-lg border border-input hover:bg-accent transition-colors"
                      @click="selectServer(server)"
                    >
                      {{ selectedServer?.name === server.name ? '收起工具' : '查看工具' }}
                    </button>
                  </div>
                </div>
                <div
                  v-if="server.lastError"
                  class="text-xs text-destructive mt-xs"
                >
                  {{ server.lastError }}
                </div>

                <!-- 工具列表（展开），集成 ToolSchemaCollapse -->
                <div
                  v-if="selectedServer?.name === server.name && store.serverTools.length > 0"
                  class="mt-sm border-t border-border pt-sm space-y-xs"
                >
                  <ToolSchemaCollapse
                    v-for="tool in store.serverTools"
                    :key="tool.id"
                    :name="tool.name"
                    :description="tool.description"
                    :input-schema="tool.inputSchema"
                  />
                </div>
              </div>
            </div>
          </template>

          <!-- 空列表引导状态 -->
          <EmptyState
            v-else
            icon="🔌"
            title="暂无 MCP Server"
            description="MCP Server 可以为 LifePilot 提供更多外部工具能力。你可以添加一个 MCP Server 来扩展功能。"
          />
        </template>
      </div>
    </div>

    <!-- 新建对话框 -->
    <div
      v-if="showCreateDialog"
      class="fixed inset-0 bg-black/50 flex items-center justify-center z-50"
      @click.self="showCreateDialog = false"
    >
      <div class="bg-card border border-border rounded-lg p-lg w-full max-w-[448px] shadow-lg">
        <h3 class="text-lg font-semibold text-foreground mb-sm">新建能力（高级）</h3>
        <p class="text-sm text-muted-foreground mb-md">
          适合熟悉 AI 配置的高级用户，创建一个完全自定义的智能能力。普通使用场景通常无需手动创建。
        </p>
        <div class="space-y-md">
          <div>
            <label class="block text-sm font-medium text-foreground mb-1">名称 *</label>
            <input
              v-model="newSkill.name"
              type="text"
              placeholder="例如：帮我规划本周目标"
              class="w-full px-md py-sm rounded-2xl border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring"
            />
          </div>
          <div>
            <label class="block text-sm font-medium text-foreground mb-1">描述</label>
            <textarea
              v-model="newSkill.description"
              placeholder="简单描述这个能力可以帮你做什么，便于后续识别和使用"
              rows="3"
              class="w-full px-md py-sm rounded-2xl border border-input bg-background text-foreground focus:outline-none focus:ring-2 focus:ring-ring resize-none"
            />
          </div>
        </div>
        <div class="flex justify-end gap-sm mt-lg">
          <button
            class="px-md py-sm rounded-lg border border-input text-sm hover:bg-accent transition-colors"
            @click="showCreateDialog = false"
          >
            取消
          </button>
          <button
            class="px-md py-sm rounded-lg bg-primary text-primary-foreground text-sm hover:bg-primary/90 transition-colors"
            @click="handleCreate"
          >
            创建
          </button>
        </div>
      </div>
    </div>

    <!-- 注销确认对话框 -->
    <div
      v-if="deleteTarget"
      class="fixed inset-0 bg-black/50 flex items-center justify-center z-[60]"
      @click.self="deleteTarget = null"
    >
      <div class="bg-card border border-border rounded-lg p-6 w-full max-w-[384px] shadow-lg">
        <h3 class="text-lg font-semibold text-foreground mb-2">确认注销</h3>
        <p class="text-sm text-muted-foreground mb-4">
          确定要注销 Skill「{{ deleteTarget.name }}」吗？此操作不可撤销。
        </p>
        <div class="flex justify-end gap-2">
          <button
            class="h-9 px-4 rounded-md text-sm border border-input hover:bg-accent transition-colors"
            @click="deleteTarget = null"
          >
            取消
          </button>
          <button
            class="h-9 px-4 rounded-md text-sm bg-destructive text-destructive-foreground hover:bg-destructive/90 transition-colors"
            @click="confirmUnregister"
          >
            注销
          </button>
        </div>
      </div>
    </div>
  </div>
</template>
